export default {
    bulgarian: 'български',
    croatian: 'хърватски',
    czech: 'чешки', 
    danish: 'датски', 
    dutch: 'нидерландски',
    english: 'английски',
    estonian: 'естонски',
    finnish: 'фински',
    french: 'френски',
    german: 'немски', 
    greek: 'гръцки',
    hungarian: 'унгарски',
    irish: 'ирландски',
    italian: 'италиански',
    latvian: 'латвийски',
    lithuanian: 'литовски',
    maltese: 'малтийски',
    norwegian: 'норвежки',
    polish: 'полски',
    portuguese: 'португалски',
    romanian:'румънски',
    slovak: 'словашки',
    slovenian: 'словенски',
    spanish: 'испански',
    swedish: 'шведски'
}