export default {
    bg: 'bulharština',
    hr: 'chorvatština',
    cs: 'čeština', 
    da: 'dánština', 
    nl: 'nizozemština',
    en: 'angličtina',
    et: 'estonština',
    fi: 'finština',
    fr: 'francouzština',
    de: 'němčina', 
    el: 'řečtina',
    hu: 'maďarština',
    ga: 'irština',
    it: 'italština',
    lv: 'lotyština',
    lt: 'litevština',
    mt: 'maltština',
    no: 'norský',
    pl: 'polština',
    pt: 'portugalština',
    ro:'rumunština',
    sk: 'slovenština',
    sl: 'slovinština',
    es: 'španělština',
    sv: 'švédština',
};