export default {
    bulgarian: 'bulharština',
    croatian: 'chorvatština',
    czech: 'čeština', 
    danish: 'dánština', 
    dutch: 'nizozemština',
    english: 'angličtina',
    estonian: 'estonština',
    finnish: 'finština',
    french: 'francouzština',
    german: 'němčina', 
    greek: 'řečtina',
    hungarian: 'maďarština',
    irish: 'irština',
    italian: 'italština',
    latvian: 'lotyština',
    lithuanian: 'litevština',
    maltese: 'maltština',
    norwegian: 'norský',
    polish: 'polština',
    portuguese: 'portugalština',
    romanian:'rumunština',
    slovak: 'slovenština',
    slovenian: 'slovinština',
    spanish: 'španělština',
    swedish: 'švédština'
}