export default {
    bulgarian: 'βουλγαρικά',
    croatian: 'κροατικά',
    czech: 'τσεχικά', 
    danish: 'δανικά', 
    dutch: 'ολλανδικά',
    english: 'αγγλικά',
    estonian: 'εσθονικά',
    finnish: 'φινλανδικά',
    french: 'γαλλικά',
    german: 'γερμανικά', 
    greek: 'ελληνικά',
    hungarian: 'ουγγρικά',
    irish: 'ιρλανδικά',
    italian: 'ιταλικά',
    latvian: 'λετονικά',
    lithuanian: 'λιθουανικά',
    maltese: 'μαλτέζικα',
    norwegian: 'norwegisch',
    polish: 'πολωνικά',
    portuguese: 'πορτογαλικά',
    romanian:'ρουμανικά',
    slovak: 'σλοβακικά',
    slovenian: 'σλοβενικά',
    spanish: 'ισπανικά',
    swedish: 'σουηδικά'
}