export default {
    bg: 'bulgarian',
    hr: 'croatian',
    cs: 'czech', 
    da: 'danish', 
    nl: 'dutch',
    en: 'english',
    et: 'estonian',
    fi: 'finnish',
    fr: 'french',
    de: 'german', 
    el: 'greek',
    hu: 'hungarian',
    ga: 'irish', 
    it: 'italian',
    lv: 'latvian',
    lt: 'lithuanian',
    mt: 'maltese',
    no: 'norwegian',
    pl: 'polish',
    pt: 'portuguese',
    ro:'romanian',
    sk: 'slovak',
    sl: 'slovenian',
    es: 'spanish',
    sv: 'swedish',
    LanguagePriorityInfo:'Here you can prioritize languages ​according to which ones you want results in. What you put at the top is the language the page is displayed in. You will receive policy documents in the highest priority language that the document is available in.',
    NoDocuments:'Sorry, there are no documents in any of your selected languages',
    AboutProject:'About the project',
    AboutText:'This is a further development of a prototype made for Trondheim municipality. The work is done in connection with the subject IT2901 Informatics Project work II. The further development realizes a multilingual user interface, as well as a document page for viewing documents related to the various targets. The further development has taken place on top of an existing prototype developed as part of a master`s thesis in informatics.',
    About:'About',
    Home:'Home',
    Close:'Close',
    GoTo:'Go to',
    TheRelation:'The relation',
    hasDevelopmentArea:'hasDevelopmentArea',
    hasTradeoffTo:'hasTradeOffTo',
    hasContributionTo:'hasContrubutionTo',
    Correlation:'Correlation',
    Contribution:'Contribution',
    TradeOff: 'TradeOff',
    DevelopmentAreaCamel:'DevelopmentArea',
    For:'For',
    To:'To',
    isA:'is a',
    binaryPositiveRelation:'binary relation that describes that one class / instance has a positive influence on another class / instance. The strength of this relationship is not defined, where a relationship between two classes / instances where only "hasContributionTo" is defined, means that the amount of contributions is undefined. See respectively "have (High / Moderate / Low) - Correlation To" - under the relationships of have Contribution To for more well-defined positive influences.',
    ShowTargets:'Show targets',
    developmentAreaRelation:'binary relation for concepts that have areas of development. According to Statistics Norway`s taxonomy, a development area is defined under perspectives. Where a development area is a concept that wants to be improved. For example, the concepts: Economy and Nature.',
    binaryNegativeRelation:'binary relation that describes that one class / instance has a negative impact on another class / instance. The strength of this relationship is not defined, where a relationship between two classes / instances where only "hasContributionTo" is defined, means that the amount of contributions is undefined. See respectively "have (High / Moderate / Low) - Correlation To" - under the relationships of have Contribution To for more well-defined positive influences.',
    uknownMunicipality:'Uknown municipality',
    Loading:'Loading',
    BackToHomePage:'Back to homepage',
    Fullscreen:'Fullscreen',
    StandardColor:'Standard color',
    Targets:'Targets',
    Target:'Target',
    Tbl:'Triple bottom line',
    DevelopmentArea:'Development area',
    ShowEdgeLabels:'Show edge labels',
    NameMissing:'Name missing',
    HasPositiveEffectOn: 'Has a positive effect on',
    HasNoEstablishedPositiveContributions: 'Has no established positive contributions yet',
    HasNegativeEffectOn: 'Has a negative effect on',
    HasNoEstablishedNegativeContributions: 'Has no established negative contributions yet',
    HasDevelopmentAreasFor: 'Has a development area to',
    HasNoDevelopmentAreas: 'Has no development areas',
    has:'has',
    aHigh:'a high',
    High:'High',
    Low:'Low',
    Moderate:'Moderate',
    aModerate:'a moderate',
    aLow:'a low',
    to:'to',
    on: 'on',
    UnlockNodes:'Unlock nodes',
    Sdg: 'Sustainable development goal',
    positiveEffect:'positive effect',
    negativeEffect:'negative effect',
    ConceptUnderDevelopment:'Concept under development',
    ChangeLanguage:'Change language',
    effects:'effects',
    PositivePlural:'Positive',
    NegativePlural:'Negative',
    DataUpload:'Data Upload',
    ShowDocuments:'Show documents',
    Show:'Show',
    GoalDistanceComputation:'Goal distance computations',
    SearchDocuments:'Search documents',
    Documents: 'Documents',
    ToTop: 'To the top',
    SeeMoreDocuments: 'See more documents',
    YourSearchReturned: 'Your search returned',
    results: 'results',
    LanguagePriority:'Language priority',
    SearchLanguages:'Search languages',
    Multilingual:'Multilingual',
    MoreInfo:'More info',
    OpenAs:'Open as',
    Active:'Active',
    SeeRelatedGoals:'See related goals',
    Sdgs:'Sustainable development goals',
    SdgOntology:'SDG Ontology',
    Search:'Search',
    desc1:'Globally, the number of people living in extreme poverty declined from 36 per cent in 1990 to 10 per cent in 2015. But the pace of change is decelerating and the COVID-19 crisis risks reversing decades of progress in the fight against poverty. New research published by the UNU World Institute for Development Economics Research warns that the economic fallout from the global pandemic could increase global poverty by as much as half a billion people, or 8% of the total human population. This would be the first time that poverty has increased globally in thirty years, since 1990.',
    1:'No poverty',
    target1_1:'By 2030, eradicate extreme poverty for all people everywhere, currently measured as people living on less than $1.25 a day',
    target1_2:'By 2030, reduce at least by half the proportion of men, women and children of all ages living in poverty in all its dimensions according to national definitions',
    target1_3:'Implement nationally appropriate social protection systems and measures for all, including floors, and by 2030 achieve substantial coverage of the poor and the vulnerable',
    target1_4:'By 2030, ensure that all men and women, in particular the poor and the vulnerable, have equal rights to economic resources, as well as access to basic services, ownership and control over land and other forms of property, inheritance, natural resources, appropriate new technology and financial services, including microfinance',
    target1_5:'By 2030, build the resilience of the poor and those in vulnerable situations and reduce their exposure and vulnerability to climate-related extreme events and other economic, social and environmental shocks and disasters',
    target1_a:'Ensure significant mobilization of resources from a variety of sources, including through enhanced development cooperation, in order to provide adequate and predictable means for developing countries, in particular least developed countries, to implement programmes and policies to end poverty in all its dimensions',
    target1_b:'Create sound policy frameworks at the national, regional and international levels, based on pro-poor and gender-sensitive development strategies, to support accelerated investment in poverty eradication actions',
    desc2:'After decades of steady decline, the number of people who suffer from hunger - as measured by the prevalence of undernourishment - began to slowly increase again in 2015. Current estimates show that nearly 690 million people are hungry, or 8.9 percent of the world population - up by 10 million people in one year and by nearly 60 million in five years. The world is not on track to achieve Zero Hunger by 2030. If recent trends continue, the number of people affected by hunger would surpass 840 million by 2030.',
    2:'Zero Hunger',
    target2_1:'By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round.',
    target2_2:'By 2030, end all forms of malnutrition, including achieving, by 2025, the internationally agreed targets on stunting and wasting in children under 5 years of age, and address the nutritional needs of adolescent girls, pregnant and lactating women and older persons.',
    target2_3:'By 2030, double the agricultural productivity and incomes of small-scale food producers, in particular women, indigenous peoples, family farmers, pastoralists and fishers, including through secure and equal access to land, other productive resources and inputs, knowledge, financial services, markets and opportunities for value addition and non-farm employment.',
    target2_4:'By 2030, ensure sustainable food production systems and implement resilient agricultural practices that increase productivity and production, that help maintain ecosystems, that strengthen capacity for adaptation to climate change, extreme weather, drought, flooding and other disasters and that progressively improve land and soil quality.',
    target2_5:'By 2020, maintain the genetic diversity of seeds, cultivated plants and farmed and domesticated animals and their related wild species, including through soundly managed and diversified seed and plant banks at the national, regional and international levels, and promote access to and fair and equitable sharing of benefits arising from the utilization of genetic resources and associated traditional knowledge, as internationally agreed.',
    target2_a:'Increase investment, including through enhanced international cooperation, in rural infrastructure, agricultural research and extension services, technology development and plant and livestock gene banks in order to enhance agricultural productive capacity in developing countries, in particular least developed countries.',
    target2_b:'Correct and prevent trade restrictions and distortions in world agricultural markets, including through the parallel elimination of all forms of agricultural export subsidies and all export measures with equivalent effect, in accordance with the mandate of the Doha Development Round.',
    target2_c:'Adopt measures to ensure the proper functioning of food commodity markets and their derivatives and facilitate timely access to market information, including on food reserves, in order to help limit extreme food price volatility.',
    desc3:'Ensuring healthy lives and promoting well-being at all ages is essential to sustainable development. Currently, the world is facing a global health crisis unlike any other — COVID-19 is spreading human suffering, destabilizing the global economy and upending the lives of billions of people around the globe.',
    3:'Good health and well-being',
    target3_1:'By 2030, reduce the global maternal mortality ratio to less than 70 per 100,000 live births.',
    target3_2:'By 2030, end preventable deaths of newborns and children under 5 years of age, with all countries aiming to reduce neonatal mortality to at least as low as 12 per 1,000 live births and under-5 mortality to at least as low as 25 per 1,000 live births.',
    target3_3:'By 2030, end the epidemics of AIDS, tuberculosis, malaria and neglected tropical diseases and combat hepatitis, water-borne diseases and other communicable diseases.',
    target3_4:'By 2030, reduce by one third premature mortality from non-communicable diseases through prevention and treatment and promote mental health and well-being.',
    target3_5:'Strengthen the prevention and treatment of substance abuse, including narcotic drug abuse and harmful use of alcohol.',
    target3_6:'By 2020, halve the number of global deaths and injuries from road traffic accidents.',
    target3_7:'By 2030, ensure universal access to sexual and reproductive health-care services, including for family planning, information and education, and the integration of reproductive health into national strategies and programmes.',
    target3_8:'Achieve universal health coverage, including financial risk protection, access to quality essential health-care services and access to safe, effective, quality and affordable essential medicines and vaccines for all.',
    target3_9:'By 2030, substantially reduce the number of deaths and illnesses from hazardous chemicals and air, water and soil pollution and contamination.',
    target3_a:'Strengthen the implementation of the World Health Organization Framework Convention on Tobacco Control in all countries, as appropriate.',
    target3_b:'Support the research and development of vaccines and medicines for the communicable and noncommunicable diseases that primarily affect developing countries, provide access to affordable essential medicines and vaccines, in accordance with the Doha Declaration on the TRIPS Agreement and Public Health, which affirms the right of developing countries to use to the full the provisions in the Agreement on Trade Related Aspects of Intellectual Property Rights regarding flexibilities to protect public health, and, in particular, provide access to medicines for all.',
    target3_c:'Substantially increase health financing and the recruitment, development, training and retention of the health workforce in developing countries, especially in least developed countries and small island developing States.',
    target3_d:'Strengthen the capacity of all countries, in particular developing countries, for early warning, risk reduction and management of national and global health risks.',
    desc4:'Education enables upward socioeconomic mobility and is a key to escaping poverty. Over the past decade, major progress was made towards increasing access to education and school enrollment rates at all levels, particularly for girls. Nevertheless, about 260 million children were still out of school in 2018 — nearly one fifth of the global population in that age group. And more than half of all children and adolescents worldwide are not meeting minimum proficiency standards in reading and mathematics.',
    4:'Quality education',
    target4_1:'By 2030, ensure that all girls and boys complete free, equitable and quality primary and secondary education leading to relevant and Goal-4 effective learning outcomes',
    target4_2:'By 2030, ensure that all girls and boys have access to quality early childhood development, care and preprimary education so that they are ready for primary education',
    target4_3:'By 2030, ensure equal access for all women and men to affordable and quality technical, vocational and tertiary education, including university',
    target4_4:'By 2030, substantially increase the number of youth and adults who have relevant skills, including technical and vocational skills, for employment, decent jobs and entrepreneurship',
    target4_5:'By 2030, eliminate gender disparities in education and ensure equal access to all levels of education and vocational training for the vulnerable, including persons with disabilities, indigenous peoples and children in vulnerable situations',
    target4_6:'By 2030, ensure that all youth and a substantial proportion of adults, both men and women, achieve literacy and numeracy',
    target4_7:'By 2030, ensure that all learners acquire the knowledge and skills needed to promote sustainable development, including, among others, through education for sustainable development and sustainable lifestyles, human rights, gender equality, promotion of a culture of peace and non-violence, global citizenship and appreciation of cultural diversity and of culture`s contribution to sustainable development',
    target4_a:'Build and upgrade education facilities that are child, disability and gender sensitive and provide safe, nonviolent, inclusive and effective learning environments for all',
    target4_b:'By 2020, substantially expand globally the number of scholarships available to developing countries, in particular least developed countries, small island developing States and African countries, for enrolment in higher education, including vocational training and information and communications technology, technical, engineering and scientific programmes, in developed countries and other developing countries',
    target4_c:'By 2030, substantially increase the supply of qualified teachers, including through international cooperation for teacher training in developing countries, especially least developed countries and small island developing states',
    desc5:'Gender equality is not only a fundamental human right, but a necessary foundation for a peaceful, prosperous and sustainable world. There has been progress over the last decades: More girls are going to school, fewer girls are forced into early marriage, more women are serving in parliament and positions of leadership, and laws are being reformed to advance gender equality. Despite these gains, many challenges remain: discriminatory laws and social norms remain pervasive, women continue to be underrepresented at all levels of political leadership, and 1 in 5 women and girls between the ages of 15 and 49 report experiencing physical or sexual violence by an intimate partner within a 12-month period.',
    5:'Gender equality',
    target5_1:'End all forms of discrimination against all women and girls everywhere',
    target5_2:'Eliminate all forms of violence against all women and girls in the public and private spheres, including trafficking and sexual and other types of exploitation',
    target5_3:'Eliminate all harmful practices, such as child, early and forced marriage and female genital mutilation',
    target5_4:'Recognize and value unpaid care and domestic work through the provision of public services, infrastructure and social protection policies and the promotion of shared responsibility within the household and the family as nationally appropriate',
    target5_5:'Ensure women`s full and effective participation and equal opportunities for leadership at all levels of decisionmaking in political, economic and public life',
    target5_6:'Ensure universal access to sexual and reproductive health and reproductive rights as agreed in accordance with the Programme of Action of the International Conference on Population and Development and the Beijing Platform for Action and the outcome documents of their review conferences',
    target5_a:'Undertake reforms to give women equal rights to economic resources, as well as access to ownership and control over land and other forms of property, financial services, inheritance and natural resources, in accordance with national laws',
    target5_b:' Enhance the use of enabling technology, in particular information and communications technology, to promote the empowerment of women',
    target5_c:'Adopt and strengthen sound policies and enforceable legislation for the promotion of gender equality and the empowerment of all women and girls at all levels',
    desc6:'While substantial progress has been made in increasing access to clean drinking water and sanitation, billions of people—mostly in rural areas—still lack these basic services. Worldwide, one in three people do not have access to safe drinking water, two out of five people do not have a basic hand-washing facility with soap and water, and more than 673 million people still practice open defecation.',
    6:'Clean water and sanitation',
    target6_1:'By 2030, achieve universal and equitable access to safe and affordable drinking water for all',
    target6_2:'By 2030, achieve access to adequate and equitable sanitation and hygiene for all and end open defecation, paying special attention to the needs of women and girls and those in vulnerable situations',
    target6_3:'By 2030, improve water quality by reducing pollution, eliminating dumping and minimizing release of hazardous chemicals and materials, halving the proportion of untreated wastewater and substantially increasing recycling and safe reuse globally',
    target6_4:'By 2030, substantially increase water-use efficiency across all sectors and ensure sustainable withdrawals and supply of freshwater to address water scarcity and substantially reduce the number of people suffering from water scarcity',
    target6_5:'By 2030, implement integrated water resources management at all levels, including through transboundary cooperation as appropriate',
    target6_6:'By 2020, protect and restore water-related ecosystems, including mountains, forests, wetlands, rivers, aquifers and lakes',
    target6_a:'By 2030, expand international cooperation and capacity-building support to developing countries in water- and sanitation-related activities and programmes, including water harvesting, desalination, water efficiency, wastewater treatment, recycling and reuse technologies',
    target6_b:'Support and strengthen the participation of local communities in improving water and sanitation management',
    desc7:'The world is making progress towards Goal 7, with encouraging signs that energy is becoming more sustainable and widely available. Access to electricity in poorer countries has begun to accelerate, energy efficiency continues to improve, and renewable energy is making impressive gains in the electricity sector. Nevertheless, more focused attention is needed to improve access to clean and safe cooking fuels and technologies for 3 billion people, to expand the use of renewable energy beyond the electricity sector, and to increase electrification in sub-Saharan Africa.',
    7:'Affordable and clean energy',
    target7_1:'By 2030, ensure universal access to affordable, reliable and modern energy services',
    target7_2:'By 2030, increase substantially the share of renewable energy in the global energy mix',
    target7_3:'By 2030, double the global rate of improvement in energy efficiency',
    target7_a:'By 2030, enhance international cooperation to facilitate access to clean energy research and technology, including renewable energy, energy efficiency and advanced and cleaner fossil-fuel technology, and promote investment in energy infrastructure and clean energy technology',
    target7_b:'By 2030, expand infrastructure and upgrade technology for supplying modern and sustainable energy services for all in developing countries, in particular least developed countries, small island developing States, and land-locked developing countries, in accordance with their respective programmes of support',
    desc8:'Sustained and inclusive economic growth can drive progress, create decent jobs for all and improve living standards.',
    8:'Decent work and economic growth',
    target8_1:'Sustain per capita economic growth in accordance with national circumstances and, in particular, at least 7 per cent gross domestic product growth per annum in the least developed countries',
    target8_2:'Achieve higher levels of economic productivity through diversification, technological upgrading and innovation, including through a focus on high-value added and labour-intensive sectors',
    target8_3:'Promote development-oriented policies that support productive activities, decent job creation, entrepreneurship, creativity and innovation, and encourage the formalization and growth of micro-, small- and medium-sized enterprises, including through access to financial services',
    target8_4:'Improve progressively, through 2030, global resource efficiency in consumption and production and endeavour to decouple economic growth from environmental degradation, in accordance with the 10-year framework of programmes on sustainable consumption and production, with developed countries taking the lead',
    target8_5:'By 2030, achieve full and productive employment and decent work for all women and men, including for young people and persons with disabilities, and equal pay for work of equal value',
    target8_6:'By 2020, substantially reduce the proportion of youth not in employment, education or training',
    target8_7:'Take immediate and effective measures to eradicate forced labour, end modern slavery and human trafficking and secure the prohibition and elimination of the worst forms of child labour, including recruitment and use of child soldiers, and by 2025 end child labour in all its forms',
    target8_8:'Protect labour rights and promote safe and secure working environments for all workers, including migrant workers, in particular women migrants, and those in precarious employment',
    target8_9:'By 2030, devise and implement policies to promote sustainable tourism that creates jobs and promotes local culture and products',
    target8_10:'Strengthen the capacity of domestic financial institutions to encourage and expand access to banking, insurance and financial services for all',
    target8_a:'Increase Aid for Trade support for developing countries, in particular least developed countries, including through the Enhanced Integrated Framework for Trade-Related Technical Assistance to Least Developed Countries',
    target8_b:'By 2020, develop and operationalize a global strategy for youth employment and implement the Global Jobs Pact of the International Labour Organization',
    desc9:'Inclusive and sustainable industrialization, together with innovation and infrastructure, can unleash dynamic and competitive economic forces that generate employment and income. They play a key role in introducing and promoting new technologies, facilitating international trade and enabling the efficient use of resources. However, the world still has a long way to go to fully tap this potential. Least developed countries, in particular, need to accelerate the development of their manufacturing sector if they are to meet the 2030 target, and scale up investment in scientific research and innovation.',
    9:'Industry, innovation and infrastructure',
    target9_1:'Develop quality, reliable, sustainable and resilient infrastructure, including regional and transborder infrastructure, to support economic development and human well-being, with a focus on affordable and equitable access for all',
    target9_2:'Promote inclusive and sustainable industrialization and, by 2030, significantly raise industry`s share of employment and gross domestic product, in line with national circumstances, and double its share in least developed countries',
    target9_3:'Increase the access of small-scale industrial and other enterprises, in particular in developing countries, to financial services, including affordable credit, and their integration into value chains and markets',
    target9_4:'By 2030, upgrade infrastructure and retrofit industries to make them sustainable, with increased resource-use efficiency and greater adoption of clean and environmentally sound technologies and industrial processes, with all countries taking action in accordance with their respective capabilities',
    target9_5:'Enhance scientific research, upgrade the technological capabilities of industrial sectors in all countries, in particular developing countries, including, by 2030, encouraging innovation and substantially increasing the number of research and development workers per 1 million people and public and private research and development spending',
    target9_a:'Facilitate sustainable and resilient infrastructure development in developing countries through enhanced financial, technological and technical support to African countries, least developed countries, landlocked developing countries and small island developing States 18',
    target9_b:'Support domestic technology development, research and innovation in developing countries, including by ensuring a conducive policy environment for, inter alia, industrial diversification and value addition to commodities',
    target9_c:'Significantly increase access to information and communications technology and strive to provide universal and affordable access to the Internet in least developed countries by 2020',
    desc10:'Reducing inequalities and ensuring no one is left behind are integral to achieving the Sustainable Development Goals. Inequality within and among countries is a persistent cause for concern. Despite some positive signs toward reducing inequality in some dimensions, such as reducing relative income inequality in some countries and preferential trade status benefiting lower-income countries, inequality still persists.',
    10:'Reduced inequalities',
    target10_1:'By 2030, progressively achieve and sustain income growth of the bottom 40 per cent of the population at a rate higher than the national average',
    target10_2:'By 2030, empower and promote the social, economic and political inclusion of all, irrespective of age, sex, disability, race, ethnicity, origin, religion or economic or other status',
    target10_3:'Ensure equal opportunity and reduce inequalities of outcome, including by eliminating discriminatory laws, policies and practices and promoting appropriate legislation, policies and action in this regard',
    target10_4:'Adopt policies, especially fiscal, wage and social protection policies, and progressively achieve greater equality',
    target10_5:'Improve the regulation and monitoring of global financial markets and institutions and strengthen the implementation of such regulations',
    target10_6:'Ensure enhanced representation and voice for developing countries in decision-making in global international economic and financial institutions in order to deliver more effective, credible, accountable and legitimate institutions',
    target10_7:'Facilitate orderly, safe, regular and responsible migration and mobility of people, including through the implementation of planned and well-managed migration policies',
    target10_a:'Implement the principle of special and differential treatment for developing countries, in particular least developed countries, in accordance with World Trade Organization agreements',
    target10_b:'Encourage official development assistance and financial flows, including foreign direct investment, to States where the need is greatest, in particular least developed countries, African countries, small island developing States and landlocked developing countries, in accordance with their national plans and programmes',
    target10_c:'By 2030, reduce to less than 3 per cent the transaction costs of migrant remittances and eliminate remittance corridors with costs higher than 5 per cent',
    desc11:'The world is becoming increasingly urbanized. Since 2007, more than half the world`s population has been living in cities, and that share is projected to rise to 60 per cent by 2030. Cities and metropolitan areas are powerhouses of economic growth—contributing about 60 per cent of global GDP. However, they also account for about 70 per cent of global carbon emissions and over 60 per cent of resource use. Rapid urbanization is resulting in a growing number of slum dwellers, inadequate and overburdened infrastructure and services (such as waste collection and water and sanitation systems, roads and transport), worsening air pollution and unplanned urban sprawl.',
    11:'Sustainable cities and communities',
    target11_1:'By 2030, ensure access for all to adequate, safe and affordable housing and basic services and upgrade slums',
    target11_2:'By 2030, provide access to safe, affordable, accessible and sustainable transport systems for all, improving road safety, notably by expanding public transport, with special attention to the needs of those in vulnerable situations, women, children, persons with disabilities and older persons',
    target11_3:'By 2030, enhance inclusive and sustainable urbanization and capacity for participatory, integrated and sustainable human settlement planning and management in all countries',
    target11_4:'Strengthen efforts to protect and safeguard the world`s cultural and natural heritage',
    target11_5:'By 2030, significantly reduce the number of deaths and the number of people affected and substantially decrease the direct economic losses relative to global gross domestic product caused by disasters, including water-related disasters, with a focus on protecting the poor and people in vulnerable situations',
    target11_6:'By 2030, reduce the adverse per capita environmental impact of cities, including by paying special attention to air quality and municipal and other waste management',
    target11_7:'By 2030, provide universal access to safe, inclusive and accessible, green and public spaces, in particular for women and children, older persons and persons with disabilities',
    target11_a:'Support positive economic, social and environmental links between urban, peri-urban and rural areas by strengthening national and regional development planning',
    target11_b:'By 2020, substantially increase the number of cities and human settlements adopting and implementing integrated policies and plans towards inclusion, resource efficiency, mitigation and adaptation to climate change, resilience to disasters, and develop and implement, in line with the Sendai Framework for Disaster Risk Reduction 2015-2030, holistic disaster risk management at all levels',
    target11_c:'Support least developed countries, including through financial and technical assistance, in building sustainable and resilient buildings utilizing local materials',
    desc12:'Worldwide consumption and production — a driving force of the global economy — rest on the use of the natural environment and resources in a way that continues to have destructive impacts on the planet. Economic and social progress over the last century has been accompanied by environmental degradation that is endangering the very systems on which our future development — indeed, our very survival — depends.',
    12:'Responsible consumption and production',
    target12_1:'Implement the 10-year framework of programmes on sustainable consumption and production, all countries taking action, with developed countries taking the lead, taking into account the development and capabilities of developing countries',
    target12_2:'By 2030, achieve the sustainable management and efficient use of natural resources',
    target12_3:'By 2030, halve per capita global food waste at the retail and consumer levels and reduce food losses along production and supply chains, including post-harvest losses',
    target12_4:'By 2020, achieve the environmentally sound management of chemicals and all wastes throughout their life cycle, in accordance with agreed international frameworks, and significantly reduce their release to air, water and soil in order to minimize their adverse impacts on human health and the environment',
    target12_5:'By 2030, substantially reduce waste generation through prevention, reduction, recycling and reuse',
    target12_6:'Encourage companies, especially large and transnational companies, to adopt sustainable practices and to integrate sustainability information into their reporting cycle',
    target12_7:'Promote public procurement practices that are sustainable, in accordance with national policies and priorities',
    target12_8:'By 2030, ensure that people everywhere have the relevant information and awareness for sustainable development and lifestyles in harmony with nature',
    target12_a:'Support developing countries to strengthen their scientific and technological capacity to move towards more sustainable patterns of consumption and production',
    target12_b:'Develop and implement tools to monitor sustainable development impacts for sustainable tourism that creates jobs and promotes local culture and products',
    target12_c:'Rationalize inefficient fossil-fuel subsidies that encourage wasteful consumption by removing market distortions, in accordance with national circumstances, including by restructuring taxation and phasing out those harmful subsidies, where they exist, to reflect their environmental impacts, taking fully into account the specific needs and conditions of developing countries and minimizing the possible adverse impacts on their development in a manner that protects the poor and the affected communities',
    desc13:'2019 was the second warmest year on record and the end of the warmest decade (2010- 2019) ever recorded. Carbon dioxide (CO2) levels and other greenhouse gases in the atmosphere rose to new records in 2019. Climate change is affecting every country on every continent. It is disrupting national economies and affecting lives. Weather patterns are changing, sea levels are rising, and weather events are becoming more extreme.',
    13:'Climate action',
    target13_1:'Strengthen resilience and adaptive capacity to climate-related hazards and natural disasters in all countries',
    target13_2:'Integrate climate change measures into national policies, strategies and planning',
    target13_3:'Improve education, awareness-raising and human and institutional capacity on climate change mitigation, adaptation, impact reduction and early warning',
    target13_a:'Implement the commitment undertaken by developed-country parties to the United Nations Framework Convention on Climate Change to a goal of mobilizing jointly $100 billion annually by 2020 from all sources to address the needs of developing countries in the context of meaningful mitigation actions and transparency on implementation and fully operationalize the Green Climate Fund through its capitalization as soon as possible',
    target13_b:'Promote mechanisms for raising capacity for effective climate change-related planning and management in least developed countries and small island developing States, including focusing on women, youth and local and marginalized communities',
    desc14:'The ocean drives global systems that make the Earth habitable for humankind. Our rainwater, drinking water, weather, climate, coastlines, much of our food, and even the oxygen in the air we breathe, are all ultimately provided and regulated by the sea. Careful management of this essential global resource is a key feature of a sustainable future. However, at the current time, there is a continuous deterioration of coastal waters owing to pollution, and ocean acidification is having an adversarial effect on the functioning of ecosystems and biodiversity. This is also negatively impacting small scale fisheries. Saving our ocean must remain a priority. Marine biodiversity is critical to the health of people and our planet. Marine protected areas need to be effectively managed and well-resourced and regulations need to be put in place to reduce overfishing, marine pollution and ocean acidification.',
    14:'Life below water',
    target14_1:'By 2025, prevent and significantly reduce marine pollution of all kinds, in particular from land-based activities, including marine debris and nutrient pollution',
    target14_2:'By 2020, sustainably manage and protect marine and coastal ecosystems to avoid significant adverse impacts, including by strengthening their resilience, and take action for their restoration in order to achieve healthy and productive oceans',
    target14_3:'Minimize and address the impacts of ocean acidification, including through enhanced scientific cooperation at all levels',
    target14_4:'By 2020, effectively regulate harvesting and end overfishing, illegal, unreported and unregulated fishing and destructive fishing practices and implement science-based management plans, in order to restore fish stocks in the shortest time feasible, at least to levels that can produce maximum sustainable yield as determined by their biological characteristics',
    target14_5:'By 2020, conserve at least 10 per cent of coastal and marine areas, consistent with national and international law and based on the best available scientific information',
    target14_6:'By 2020, prohibit certain forms of fisheries subsidies which contribute to overcapacity and overfishing, eliminate subsidies that contribute to illegal, unreported and unregulated fishing and refrain from introducing new such subsidies, recognizing that appropriate and effective special and differential treatment for developing and least developed countries should be an integral part of the World Trade Organization fisheries subsidies negotiation',
    target14_7:'By 2030, increase the economic benefits to Small Island developing States and least developed countries from the sustainable use of marine resources, including through sustainable management of fisheries, aquaculture and tourism',
    target14_a:'Increase scientific knowledge, develop research capacity and transfer marine technology, taking into account the Intergovernmental Oceanographic Commission Criteria and Guidelines on the Transfer of Marine Technology, in order to improve ocean health and to enhance the contribution of marine biodiversity to the development of developing countries, in particular small island developing States and least developed countries',
    target14_b:'Provide access for small-scale artisanal fishers to marine resources and markets',
    target14_c:'Enhance the conservation and sustainable use of oceans and their resources by implementing international law as reflected in UNCLOS, which provides the legal framework for the conservation and sustainable use of oceans and their resources, as recalled in paragraph 158 of The Future We Want',
    desc15:'Nature is critical to our survival: nature provides us with our oxygen, regulates our weather patterns, pollinates our crops, produces our food, feed and fibre. But it is under increasing stress. Human activity has altered almost 75 per cent of the earth`s surface, squeezing wildlife and nature into an ever-smaller corner of the planet. Around 1 million animal and plant species are threatened with extinction – many within decades – according to the 2019 Global Assessment Report on Biodiversity and Ecosystem Service. The report called for transformative changes to restore and protect nature. It found that the health of ecosystems on which we and all other species depend is deteriorating more rapidly than ever, affecting  the very foundations of our economies, livelihoods, food security, health and quality of life worldwide. Deforestation and desertification – caused by human activities and climate change – pose major challenges to sustainable development and have affected the lives and livelihoods of millions of people. Forests are vitally important for sustaining life on Earth, and play a major role in the fight against climate change. And investing in land restoration is critical for improving livelihoods, reducing vulnerabilities, and reducing risks for the economy. The health of our planet also plays an important role in the emergence of zoonotic diseases, i.e. diseases that are transmissible between animals and humans. As we continue to encroach on fragile ecosystems, we bring humans into ever-greater contact with wildlife, enabling pathogens in wildlife to spill over to livestock and humans, increasing the risk of disease emergence and amplification.',
    15:'Life on land',
    target15_1:'By 2020, ensure the conservation, restoration and sustainable use of terrestrial and inland freshwater ecosystems and their services, in particular forests, wetlands, mountains and drylands, in line with obligations under international agreements',
    target15_2:'By 2020, promote the implementation of sustainable management of all types of forests, halt deforestation, restore degraded forests and substantially increase afforestation and reforestation globally',
    target15_3:'By 2030, combat desertification, restore degraded land and soil, including land affected by desertification, drought and floods, and strive to achieve a land degradation-neutral world',
    target15_4:'By 2030, ensure the conservation of mountain ecosystems, including their biodiversity, in order to enhance their capacity to provide benefits that are essential for sustainable development',
    target15_5:'Take urgent and significant action to reduce the degradation of natural habitats, halt the loss of biodiversity and, by 2020, protect and prevent the extinction of threatened species',
    target15_6:'Promote fair and equitable sharing of the benefits arising from the utilization of genetic resources and promote appropriate access to such resources, as internationally agreed',
    target15_7:'Take urgent action to end poaching and trafficking of protected species of flora and fauna and address both demand and supply of illegal wildlife products',
    target15_8:'By 2020, introduce measures to prevent the introduction and significantly reduce the impact of invasive alien species on land and water ecosystems and control or eradicate the priority species',
    target15_9:'By 2020, integrate ecosystem and biodiversity values into national and local planning, development processes, poverty reduction strategies and accounts',
    target15_a:'Mobilize and significantly increase financial resources from all sources to conserve and sustainably use biodiversity and ecosystems',
    target15_b:'Mobilize significant resources from all sources and at all levels to finance sustainable forest management and provide adequate incentives to developing countries to advance such management, including for conservation and reforestation',
    target15_c:'Enhance global support for efforts to combat poaching and trafficking of protected species, including by increasing the capacity of local communities to pursue sustainable livelihood opportunities',
    desc16:'Conflict, insecurity, weak institutions and limited access to justice remain a great threat to sustainable development. The number of people fleeing war, persecution and conflict exceeded 70 million in 2018, the highest level recorded by the UN refugee agency (UNHCR) in almost 70 years. In 2019, the United Nations tracked 357 killings and 30 enforced disappearances of human rights defenders, journalists and trade unionists in 47 countries. And the births of around one in four children under age 5 worldwide are never officially recorded, depriving them of a proof of legal identity crucial for the protection of their rights and for access to justice and social services.',
    16:'Peace, justice and strong institutions',
    target16_1:'Significantly reduce all forms of violence and related death rates everywhere',
    target16_2:'End abuse, exploitation, trafficking and all forms of violence against and torture of children',
    target16_3:'Promote the rule of law at the national and international levels and ensure equal access to justice for all',
    target16_4:'By 2030, significantly reduce illicit financial and arms flows, strengthen the recovery and return of stolen assets and combat all forms of organized crime',
    target16_5:'Substantially reduce corruption and bribery in all their forms',
    target16_6:'Develop effective, accountable and transparent institutions at all levels',
    target16_7:'Ensure responsive, inclusive, participatory and representative decision-making at all levels',
    target16_8:'Broaden and strengthen the participation of developing countries in the institutions of global governance',
    target16_9:'By 2030, provide legal identity for all, including birth registration',
    target16_10:'Ensure public access to information and protect fundamental freedoms, in accordance with national legislation and international agreements',
    target16_a:'Strengthen relevant national institutions, including through international cooperation, for building capacity at all levels, in particular in developing countries, to prevent violence and combat terrorism and crime',
    target16_b:'Promote and enforce non-discriminatory laws and policies for sustainable development',
    desc17:'The SDGs can only be realized with strong global partnerships and cooperation. A successful development agenda requires inclusive partnerships — at the global, regional, national and local levels — built upon principles and values, and upon a shared vision and shared goals placing people and the planet at the centre. Many countries require Official Development Assistance to encourage growth and trade. Yet, aid levels are falling and donor countries have not lived up to their pledge to ramp up development finance.',
    17:'Partnerships for the goals',
    target17_1:'Strengthen domestic resource mobilization, including through international support to developing countries, to improve domestic capacity for tax and other revenue collection',
    target17_2:'Developed countries to implement fully their official development assistance commitments, including the commitment by many developed countries to achieve the target of 0.7 per cent of ODA/GNI to developing countries and 0.15 to 0.20 per cent of ODA/GNI to least developed countries ODA providers are encouraged to consider setting a target to provide at least 0.20 per cent of ODA/GNI to least developed countries',
    target17_3:'Mobilize additional financial resources for developing countries from multiple sources',
    target17_4:'Assist developing countries in attaining long-term debt sustainability through coordinated policies aimed at fostering debt financing, debt relief and debt restructuring, as appropriate, and address the external debt of highly indebted poor countries to reduce debt distress',
    target17_5:'Adopt and implement investment promotion regimes for least developed countries',
    target17_6:'Enhance North-South, South-South and triangular regional and international cooperation on and access to science, technology and innovation and enhance knowledge sharing on mutually agreed terms, including through improved coordination among existing mechanisms, in particular at the United Nations level, and through a global technology facilitation mechanism',
    target17_7:'Promote the development, transfer, dissemination and diffusion of environmentally sound technologies to developing countries on favourable terms, including on concessional and preferential terms, as mutually agreed',
    target17_8:'Fully operationalize the technology bank and science, technology and innovation capacity-building mechanism for least developed countries by 2017 and enhance the use of enabling technology, in particular information and communications technology',
    target17_9:'Enhance international support for implementing effective and targeted capacity-building in developing countries to support national plans to implement all the sustainable development goals, including through North-South, South-South and triangular cooperation',
    target17_10:'Promote a universal, rules-based, open, non-discriminatory and equitable multilateral trading system under the World Trade Organization, including through the conclusion of negotiations under its Doha Development Agenda',
    target17_11:'Significantly increase the exports of developing countries, in particular with a view to doubling the least developed countries` share of global exports by 2020',
    target17_12:'Realize timely implementation of duty-free and quota-free market access on a lasting basis for all least developed countries, consistent with World Trade Organization decisions, including by ensuring that preferential rules of origin applicable to imports from least developed countries are transparent and simple, and contribute to facilitating market access',
    target17_13:'Enhance global macroeconomic stability, including through policy coordination and policy coherence',
    target17_14:'Enhance policy coherence for sustainable development',
    target17_15:'Respect each country`s policy space and leadership to establish and implement policies for poverty eradication and sustainable development',
    target17_16:'Enhance the global partnership for sustainable development, complemented by multi-stakeholder partnerships that mobilize and share knowledge, expertise, technology and financial resources, to support the achievement of the sustainable development goals in all countries, in particular developing countries',
    target17_17:'Encourage and promote effective public, public-private and civil society partnerships, building on the experience and resourcing strategies of partnerships',
    target17_18:'By 2020, enhance capacity-building support to developing countries, including for least developed countries and small island developing States, to increase significantly the availability of high-quality, timely and reliable data disaggregated by income, gender, age, race, ethnicity, migratory status, disability, geographic location and other characteristics relevant in national contexts',
    target17_19:'By 2030, build on existing initiatives to develop measurements of progress on sustainable development that complement gross domestic product, and support statistical capacity-building in developing countries',
    // Temporary:
    // Development areas:
    Arbeid_sysselsettning:'Work and employment',
    Bebyggelse:'Buildings',
    Digitalisering1:'Digitalization',
    Energi:'Energy',
    Helse_sosial_og_velferd:'Health, social and welfare',
    Kultur:'Culture',
    Natur_og_miljø:'Nature and environment',
    Næring:'Industry',
    Oppvekst_og_utdanning:'Childhood and education',
    Styring_og_demokrati:'Governance and democracy',
    Transport:'Transport',
    Trygghet_og_beredskap:'Safety and preparedness',
    Vann_og_søppel:'Water and garbage',
    Økonomisk:'Economic',
    // TBL:
    Miljø:'Environment',
    Sosialt:'Social',
    Økonomi:'Economy',
    // Perspectives in Trdheim
    Arealer_og_ressursforvaltning:'Areas and resource management',
    Det_grønne_skiftet:'The green shift',
    Digitalisering2:'Digitalization',
    Forbruk:'Consumption',
    Grønn_mobilitet:'Green mobility',
    Indentitet_og_kultur:'Identity and culture',
    Inkluderende_samfunn:'Including society',
    Lokaldemokratiet:'Local democracy',
    Nærmiljø_og_stedsutvikling:'Local environment and development',
    Oppvekst_og_læring:'Childhood and learning',
    P1:'P1',
    Samarbeid_og_verdiskapning:'Co-operation and economic growth',
    Samskapt_velferd:'Co-created welfare',
    Økonomi1:'Economy',
    // Icons:
    icon_1: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf21440450108c3003abd2/previews/5daf21450450108c3003abec/download/E-WEB-Goal-01.png',
    icon_2: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf2145d48760808cf5818a/previews/5daf2146d48760808cf5819f/download/E-WEB-Goal-02.png',
    icon_3: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf2147c13e30877c4d3a44/previews/5daf2148c13e30877c4d3a61/download/E-WEB-Goal-03.png',
    icon_4: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf214808fe423a947dfa67/previews/5daf214908fe423a947dfa6e/download/E-WEB-Goal-04.png',
    icon_5: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf2149be96367d39c87966/previews/5daf214abe96367d39c87989/download/E-WEB-Goal-05.png',
    icon_6: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf214a4f65ab6e72d88bf3/previews/5daf214b4f65ab6e72d88d00/download/E-WEB-Goal-06.png',
    icon_7: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf214c7765bb3bec0c14ee/previews/5daf214c7765bb3bec0c14f6/download/E-WEB-Goal-07.png',
    icon_8: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf214d81db226fb7d58dd7/previews/5daf214e81db226fb7d58e35/download/E-WEB-Goal-08.png',
    icon_9: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf214ebd664d1c926d3f11/previews/5daf214fbd664d1c926d3f29/download/E-WEB-Goal-09.png',
    icon_10: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf214f45014b1f15b2eeff/previews/5daf215045014b1f15b2ef1a/download/E-WEB-Goal-10.png',
    icon_11: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf2150b7df28199b3fb08e/previews/5daf2151b7df28199b3fb09e/download/E-WEB-Goal-11.png',
    icon_12: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf2151269e9881834f9a3e/previews/5daf2152269e9881834f9a4b/download/E-WEB-Goal-12.png',
    icon_13: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf2152367f552ff02ababf/previews/5daf2153367f552ff02abad1/download/E-WEB-Goal-13.png',
    icon_14: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf2153647b8b0afacd7048/previews/5daf2154647b8b0afacd705f/download/E-WEB-Goal-14.png',
    icon_15: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf215416d44e4fa64dfe30/previews/5daf215516d44e4fa64dfe9d/download/E-WEB-Goal-15.png',
    icon_16: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf21440450108c3003abd2/previews/5daf21450450108c3003abec/download/E-WEB-Goal-16.png',
    icon_17: 'https://trello.com/1/cards/5aeb5fa28d9555986903a122/attachments/5daf21576cf20a5e74f12798/previews/5daf21586cf20a5e74f127b5/download/E-WEB-Goal-17.png',

};