export default {
    bulgarian: 'bulgarian',
    croatian: 'croatian',
    czech: 'czech', 
    danish: 'danish', 
    dutch: 'dutch',
    english: 'english',
    estonian: 'estonian',
    finnish: 'finnish',
    french: 'french',
    german: 'german', 
    greek: 'greek',
    hungarian: 'hungarian',
    irish: 'irish', 
    italian: 'italian',
    latvian: 'latvian',
    lithuanian: 'lithuanian',
    maltese: 'maltese',
    norwegian: 'norwegian',
    polish: 'polish',
    portuguese: 'portuguese',
    romanian:'romanian',
    slovak: 'slovak',
    slovenian: 'slovenian',
    spanish: 'spanish',
    swedish: 'swedish'
}