export default {
    bg: 'búlgaro',
    hr: 'croata',
    cs: 'checo', 
    da: 'danés', 
    nl: 'neerlandés',
    en: 'inglés',
    et: 'estonio',
    fi: 'finés',
    fr: 'francés',
    de: 'alemán', 
    el: 'griego',
    hu: 'húngaro',
    ga: 'irlandés',
    it: 'ito',
    lv: 'letón',
    lt: 'lituano',
    mt: 'maltés',
    no: 'noruego',
    pl: 'polaco',
    pt: 'portugués',
    ro:'rumano',
    sk: 'eslovaco',
    sl: 'esloveno',
    es: 'español',
    sv: 'sueco',
    LanguagePriorityInfo:'Aquí puede priorizar los idiomas según los resultados que desee. Lo que pone en la parte superior es el idioma en el que se muestra la página. Recibirá los documentos de la póliza en el idioma de mayor prioridad que tenga los documentos disponibles.',
    NoDocuments:'Lo sentimos, no hay documentos en ninguno de los idiomas seleccionados',
    AboutProject:'Sobre el proyecto',
    AboutText:'Este es un desarrollo posterior de un prototipo hecho para el municipio de Trondheim. El trabajo se realiza en relación con la asignatura Proyecto de Informática IT2901 trabajo II. El desarrollo posterior realiza una interfaz de usuario multilingüe, así como una página de documentos para ver documentos relacionados con los diversos metas. El desarrollo posterior ha tenido lugar sobre un prototipo existente desarrollado como parte de una tesis de maestría en informática.',
    About:'Sobre el proyecto',
    Home:'Inicio',
    Close:'Cerrar',
    GoTo:'Ve a',
    TheRelation:'La relación',
    hasDevelopmentArea:'tieneÁreaDeDesarrollo',
    hasTradeoffTo:'tieneCompensaciónA',
    hasContributionTo:'tieneContribuciónA',
    Correlation:'Correlación',
    Contribution:'Contribución',
    TradeOff: 'Compensación',
    To:'A',
    DevelopmentAreaCamel:'ÁreaDeDesarrollo',
    For:'Por',
    isA:'es una', // About relation
    binaryPositiveRelation:'relación binaria que describe que una clase/instancia tiene una influencia positiva en otra clase/instancia. La fuerza de esta relación no está definida, donde una relación entre dos clases/instancias donde solo se define "tieneContribuciónA", significa que la cantidad de contribuciones no está definida. Ver respectivamente "tiene (Alto/Moderado/Bajo) - CorrelaciónCon" - bajo las relaciones de tener Contribución a para influencias positivas más bien definidas.',
    ShowTargets:'Mostrar metas',
    developmentAreaRelation:'relación binaria para conceptos que tienen áreas de desarrollo. De acuerdo con la taxonomía de Statistics Norway, un área de desarrollo se define bajo perspectivas. Donde un área de desarrollo es un concepto que quiere ser mejorado. Por ejemplo, los conceptos: Economía y Naturaleza.',
    binaryNegativeRelation:'relación binaria que describe que una clase/instancia tiene un impacto negativo en otra clase/instancia. La fuerza de esta relación no está definida, donde una relación entre dos clases/instancias donde solo se define "tieneContribuciónA", significa que la cantidad de contribuciones no está definida. Ver respectivamente "tiene (Alto/Moderado/Bajo) - CorrelaciónCon" - bajo las relaciones de tener Contribución a para influencias positivas más bien definidas.',
    UknownMunicipality:'Municipio desconocido',
    Loading:'Cargando',
    BackToHomePage:'Inicio',
    Fullscreen:'Pantalla completa',
    StandardColor:'Color estándar',
    Targets:'Meta',
    Target:'Metas del objectivo',
    Tbl:'Triple resultado',
    DevelopmentArea:'Area de desarrollo',
    ShowEdgeLabels:'Mostrar etiquetas de borde',
    NameMissing:'Falta nombre',
    HasPositiveEffectOn: 'Tiene un efecto positivo en',
    HasNoEstablishedPositiveContributions: 'No tiene contribuciones positivas establecidas',
    HasNegativeEffectOn: 'Tiene un efecto negativo en',
    HasNoEstablishedNegativeContributions: 'No tiene contribuciones negativas establecidas',
    HasDevelopmentAreasFor: 'Tiene áreas de desarrollo para',
    HasNoDevelopmentAreas: 'No tiene áreas de desarrollo',
    has:'tiene',
    aHigh:'un alto',
    High:'Alto',
    Low:'Bajo',
    Moderate:'Moderado',
    aModerate:'Un moderado',
    aLow:'un bajo',
    to:'a',
    on:'sobre',
    UnlockNodes:'Desbloquear nodos',
    Sdg: 'Objetivo de Desarrollo Sostenible',
    positiveEffect:'efecto positivo',
    negativeEffect:'efecto negativo',
    ConceptUnderDevelopment:'Concepto en desarrollo',
    ChangeLanguage:'Cambiar idioma',
    effects:'efectos',
    PositivePlural:'Positivo',
    NegativePlural:'Negativo',
    DataUpload:'Subida de datos',
    ShowDocuments:'Mostrar documentos',
    Show:'Mostrar',
    GoalDistanceComputation:'Cómputo de distancia de goles',
    SearchDocuments:'Buscar documentos',
    Documents: 'Documentos',
    ToTop: 'Desplazarse hacia arriba',
    SeeMoreDocuments: 'Ver más documentos',
    YourSearchReturned: 'Tu búsqueda devolvió',
    results: 'resultados',
    LanguagePriority:'Prioridad de idioma',
    SearchLanguages:'Buscar idiomas',
    Multilingual:'Plurilingüe',
    MoreInfo:'Más información',
    OpenAs:'Abierto como',
    Active:'Activo',
    SeeRelatedGoals:'Ver objetivos relacionados',
    Sdgs:'Objetivos de Desarrollo Sostenible',
    SdgOntology:'ODS Ontología',
    Search:'Buscar',
    desc1:'Erradicar la pobreza en todas sus formas sigue siendo uno de los principales desafíos que enfrenta la humanidad. Si bien la cantidad de personas que viven en la extrema pobreza disminuyó en más de la mitad entre 1990 y 2015, aún demasiadas luchan por satisfacer las necesidades más básicas. Para el año 2015, a nivel mundial, alrededor de 736 millones de personas aún viven con menos de USD 1,90 al día y muchos carecen de acceso a alimentos, agua potable y saneamiento adecuados. El crecimiento económico acelerado de países como China y la India ha sacado a millones de personas de la pobreza, pero el progreso ha sido disparejo. La posibilidad de que las mujeres vivan en situación de pobreza es desproporcionadamente alta en relación con los hombres, debido al acceso desigual al trabajo remunerado, la educación y la propiedad.',
    1:'Fin de la pobreza',
    target1_1:'Para 2030, erradicar la pobreza extrema para todas las personas en el mundo, actualmente medida por un ingreso por persona inferior a 1,25 dólares al día.',
    target1_2:'Para 2030, reducir al menos a la mitad la proporción de hombres, mujeres y niños y niñas de todas las edades que viven en la pobreza en todas sus dimensiones con arreglo a las definiciones nacionales.',
    target1_3:' Poner en práctica a nivel nacional sistemas y medidas apropiadas de protección social para todos y, para 2030, lograr una amplia cobertura de los pobres y los más vulnerables.',
    target1_4:'Para 2030, garantizar que todos los hombres y mujeres, en particular los pobres y los más vulnerables, tengan los mismos derechos a los recursos económicos, así como acceso a los servicios básicos, la propiedad y el control de las tierras y otros bienes, la herencia, los recursos naturales, las nuevas tecnologías y los servicios económicos, incluida la microfinanciación.',
    target1_5:'Para 2030, fomentar la resiliencia de los pobres y las personas que se encuentran en situaciones vulnerables y reducir su exposición y vulnerabilidad a los fenómenos extremos relacionados con el clima y a otros desastres económicos, sociales y ambientales.',
    target1_a:'Garantizar una movilización importante de recursos procedentes de diversas fuentes, incluso mediante la mejora de la cooperación para el desarrollo, a fin de proporcionar medios suficientes y previsibles para los países en desarrollo, en particular los países menos adelantados, para poner en práctica programas y políticas encaminados a poner fin a la pobreza en todas sus dimensiones.',
    target1_b:'Crear marcos normativos sólidos en el ámbito nacional, regional e internacional, sobre la base de estrategias de desarrollo en favor de los pobres que tengan en cuenta las cuestiones de género, a fin de apoyar la inversión acelerada en medidas para erradicar la pobreza.',
    desc2:'Tras décadas de una disminución constante, el número de personas que padecen hambre (medido por la prevalencia de desnutrición) comenzó a aumentar lentamente de nuevo en 2015. Las estimaciones actuales indican que cerca de 690 millones de personas en el mundo padecen hambre, es decir, el 8,9 por ciento de la población mundial, lo que supone un aumento de unos 10 millones de personas en un año y de unos 60 millones en cinco años.El mundo no está bien encaminado para alcanzar el objetivo de hambre cero para 2030. Si continúan las tendencias recientes, el número de personas afectadas por el hambre superará los 840 millones de personas para 2030.',
    2:'Hambre cero',
    target2_1: 'Para 2030, poner fin al hambre y asegurar el acceso de todas las personas, en particular los pobres y las personas en situaciones vulnerables, incluidos los lactantes, a una alimentación sana, nutritiva y suficiente durante todo el año',
    target2_2:'Para 2030, poner fin a todas las formas de malnutrición, incluso logrando, a más tardar en 2025, las metas convenidas internacionalmente sobre el retraso del crecimiento y la emaciación de los niños menores de 5 años, y abordar las necesidades de nutrición de las adolescentes, las mujeres embarazadas y lactantes y las personas de edad',
    target2_3:'Para 2030, duplicar la productividad agrícola y los ingresos de los productores de alimentos en pequeña escala, en particular las mujeres, los pueblos indígenas, los agricultores familiares, los pastores y los pescadores, entre otras cosas mediante un acceso seguro y equitativo a las tierras, a otros recursos de producción e insumos, conocimientos, servicios financieros, mercados y oportunidades para la generación de valor añadido y empleos no agrícolas',
    target2_4:'Para 2030, asegurar la sostenibilidad de los sistemas de producción de alimentos y aplicar prácticas agrícolas resilientes que aumenten la productividad y la producción, contribuyan al mantenimiento de los ecosistemas, fortalezcan la capacidad de adaptación al cambio climático, los fenómenos meteorológicos extremos, las sequías, las inundaciones y otros desastres, y mejoren progresivamente la calidad del suelo y la tierra',
    target2_5:'Para 2020, mantener la diversidad genética de las semillas, las plantas cultivadas y los animales de granja y domesticados y sus especies silvestres conexas, entre otras cosas mediante una buena gestión y diversificación de los bancos de semillas y plantas a nivel nacional, regional e internacional, y promover el acceso a los beneficios que se deriven de la utilización de los recursos genéticos y los conocimientos tradicionales y su distribución justa y equitativa, como se ha convenido internacionalmente',
    target2_a:'Aumentar las inversiones, incluso mediante una mayor cooperación internacional, en la infraestructura rural, la investigación agrícola y los servicios de extensión, el desarrollo tecnológico y los bancos de genes de plantas y ganado a fin de mejorar la capacidad de producción agrícola en los países en desarrollo, en particular en los países menos adelantados',
    target2_b:'Corregir y prevenir las restricciones y distorsiones comerciales en los mercados agropecuarios mundiales, entre otras cosas mediante la eliminación paralela de todas las formas de subvenciones a las exportaciones agrícolas y todas las medidas de exportación con efectos equivalentes, de conformidad con el mandato de la Ronda de Doha para el Desarrollo',
    target2_c:'Adoptar medidas para asegurar el buen funcionamiento de los mercados de productos básicos alimentarios y sus derivados y facilitar el acceso oportuno a información sobre los mercados, en particular sobre las reservas de alimentos, a fin de ayudar a limitar la extrema volatilidad de los precios de los alimentos',
    desc3:'Garantizar una vida sana y promover el bienestar en todas las edades es esencial para el desarrollo sostenible. Actualmente, el mundo se enfrenta a una crisis sanitaria mundial sin precedentes; la COVID-19 está propagando el sufrimiento humano, desestabilizando la economía mundial y cambiando drásticamente las vidas de miles de millones de personas en todo el mundo. Antes de la pandemia, se consiguieron grandes avances en la mejora de la salud de millones de personas. En concreto, estos grandes avances se alcanzaron al aumentar la esperanza de vida y reducir algunas de las causas de muerte comunes asociadas con la mortalidad infantil y materna. Sin embargo, se necesitan más esfuerzos para erradicar por completo una gran variedad de enfermedades y abordar un gran número de problemas de salud, tanto constantes como emergentes. A través de una financiación más eficiente de los sistemas sanitarios, un mayor saneamiento e higiene, y un mayor acceso al personal médico, se podrán conseguir avances significativos a la hora de ayudar a salvar las vidas de millones de personas.',
    3:'Salud y bienestar',
    target3_1:'Para 2030, reducir la tasa mundial de mortalidad materna a menos de 70 por cada 100.000 nacidos vivos',
    target3_2:'Para 2030, poner fin a las muertes evitables de recién nacidos y de niños menores de 5 años, logrando que todos los países intenten reducir la mortalidad neonatal al menos hasta 12 por cada 1.000 nacidos vivos, y la mortalidad de niños menores de 5 años al menos hasta 25 por cada 1.000 nacidos vivos',
    target3_3:'Para 2030, poner fin a las epidemias del SIDA, la tuberculosis, la malaria y las enfermedades tropicales desatendidas y combatir la hepatitis, las enfermedades transmitidas por el agua y otras enfermedades transmisibles',
    target3_4:'Para 2030, reducir en un tercio la mortalidad prematura por enfermedades no transmisibles mediante la prevención y el tratamiento y promover la salud mental y el bienestar',
    target3_5:'Fortalecer la prevención y el tratamiento del abuso de sustancias adictivas, incluido el uso indebido de estupefacientes y el consumo nocivo de alcohol',
    target3_6:'Para 2020, reducir a la mitad el número de muertes y lesiones causadas por accidentes de tráfico en el mundo',
    target3_7:'Para 2030, garantizar el acceso universal a los servicios de salud sexual y reproductiva, incluidos los de planificación de la familia, información y educación, y la integración de la salud reproductiva en las estrategias y los programas nacionales',
    target3_8:'Lograr la cobertura sanitaria universal, en particular la protección contra los riesgos financieros, el acceso a servicios de salud esenciales de calidad y el acceso a medicamentos y vacunas seguros, eficaces, asequibles y de calidad para todos',
    target3_9:'Para 2030, reducir sustancialmente el número de muertes y enfermedades producidas por productos químicos peligrosos y la contaminación del aire, el agua y el suelo',
    target3_a:'Fortalecer la aplicación del Convenio Marco de la Organización Mundial de la Salud para el Control del Tabaco en todos los países, según proceda',
    target3_b:' Apoyar las actividades de investigación y desarrollo de vacunas y medicamentos para las enfermedades transmisibles y no transmisibles que afectan primordialmente a los países en desarrollo y facilitar el acceso a medicamentos y vacunas esenciales asequibles de conformidad con la Declaración de Doha relativa al Acuerdo sobre los ADPIC y la Salud Pública, en la que se afirma el derecho de los países en desarrollo a utilizar al máximo las disposiciones del Acuerdo sobre los Aspectos de los Derechos de Propiedad Intelectual Relacionados con el Comercio en lo relativo a la flexibilidad para proteger la salud pública y, en particular, proporcionar acceso a los medicamentos para todos',
    target3_c:'Aumentar sustancialmente la financiación de la salud y la contratación, el desarrollo, la capacitación y la retención del personal sanitario en los países en desarrollo, especialmente en los países menos adelantados y los pequeños Estados insulares en desarrollo',
    target3_d:'Reforzar la capacidad de todos los países, en particular los países en desarrollo, en materia de alerta temprana, reducción de riesgos y gestión de los riesgos para la salud nacional y mundial',
    desc4:'La educación permite la movilidad socioeconómica ascendente y es clave para salir de la pobreza. Durante la última década, se consiguieron grandes avances a la hora de ampliar el acceso a la educación y las tasas de matriculación en las escuelas en todos los niveles, especialmente para las niñas. No obstante, alrededor de 260 millones de niños aún estaban fuera de la escuela en 2018; cerca de una quinta parte de la población mundial de ese grupo de edad. Además, más de la mitad de todos los niños y adolescentes de todo el mundo no están alcanzando los estándares mínimos de competencia en lectura y matemáticas.',
    4:'Educación de calidad',
    target4_1:'De aquí a 2030, asegurar que todas las niñas y todos los niños terminen la enseñanza primaria y secundaria, que ha de ser gratuita, equitativa y de calidad y producir resultados de aprendizaje pertinentes y efectivos',
    target4_2:'De aquí a 2030, asegurar que todas las niñas y todos los niños tengan acceso a servicios de atención y desarrollo en la primera infancia y educación preescolar de calidad, a fin de que estén preparados para la enseñanza primaria',
    target4_3:'De aquí a 2030, asegurar el acceso igualitario de todos los hombres y las mujeres a una formación técnica, profesional y superior de calidad, incluida la enseñanza universitaria',
    target4_4:'De aquí a 2030, aumentar considerablemente el número de jóvenes y adultos que tienen las competencias necesarias, en particular técnicas y profesionales, para acceder al empleo, el trabajo decente y el emprendimiento',
    target4_5:'De aquí a 2030, eliminar las disparidades de género en la educación y asegurar el acceso igualitario a todos los niveles de la enseñanza y la formación profesional para las personas vulnerables, incluidas las personas con discapacidad, los pueblos indígenas y los niños en situaciones de vulnerabilidad',
    target4_6:'De aquí a 2030, asegurar que todos los jóvenes y una proporción considerable de los adultos, tanto hombres como mujeres, estén alfabetizados y tengan nociones elementales de aritmética',
    target4_7:'De aquí a 2030, asegurar que todos los alumnos adquieran los conocimientos teóricos y prácticos necesarios para promover el desarrollo sostenible, entre otras cosas mediante la educación para el desarrollo sostenible y los estilos de vida sostenibles, los derechos humanos, la igualdad de género, la promoción de una cultura de paz y no violencia, la ciudadanía mundial y la valoración de la diversidad cultural y la contribución de la cultura al desarrollo sostenible',
    target4_a:'Construir y adecuar instalaciones educativas que tengan en cuenta las necesidades de los niños y las personas con discapacidad y las diferencias de género, y que ofrezcan entornos de aprendizaje seguros, no violentos, inclusivos y eficaces para todos',
    target4_b:'De aquí a 2020, aumentar considerablemente a nivel mundial el número de becas disponibles para los países en desarrollo, en particular los países menos adelantados, los pequeños Estados insulares en desarrollo y los países africanos, a fin de que sus estudiantes puedan matricularse en programas de enseñanza superior, incluidos programas de formación profesional y programas técnicos, científicos, de ingeniería y de tecnología de la información y las comunicaciones, de países desarrollados y otros países en desarrollo',
    target4_c:'De aquí a 2030, aumentar considerablemente la oferta de docentes calificados, incluso mediante la cooperación internacional para la formación de docentes en los países en desarrollo, especialmente los países menos adelantados y los pequeños Estados insulares en desarrollo',
    desc5:'La igualdad de género no solo es un derecho humano fundamental, sino que es uno de los fundamentos esenciales para construir un mundo pacífico, próspero y sostenible. Se han conseguido algunos avances durante las últimas décadas: más niñas están escolarizadas, y se obliga a menos niñas al matrimonio precoz; hay más mujeres con cargos en parlamentos y en posiciones de liderazgo, y las leyes se están reformando para fomentar la igualdad de género. A pesar de estos logros, todavía existen muchas dificultades: las leyes y las normas sociales discriminatorias continúan siendo generalizadas, las mujeres siguen estando infrarrepresentadas a todos los niveles de liderazgo político, y 1 de cada 5 mujeres y niñas de entre 15 y 49 años afirma haber sufrido violencia sexual o física a manos de una pareja íntima en un período de 12 meses.',
    5:'Igualdad de género',
    target5_1:'Poner fin a todas las formas de discriminación contra todas las mujeres y las niñas en todo el mundo',
    target5_2:'Eliminar todas las formas de violencia contra todas las mujeres y las niñas en los ámbitos público y privado, incluidas la trata y la explotación sexual y otros tipos de explotación',
    target5_3:'Eliminar todas las prácticas nocivas, como el matrimonio infantil, precoz y forzado y la mutilación genital femenina',
    target5_4:'Reconocer y valorar los cuidados y el trabajo doméstico no remunerados mediante servicios públicos, infraestructuras y políticas de protección social, y promoviendo la responsabilidad compartida en el hogar y la familia, según proceda en cada país',
    target5_5:'Asegurar la participación plena y efectiva de las mujeres y la igualdad de oportunidades de liderazgo a todos los niveles decisorios en la vida política, económica y pública',
    target5_6:'Asegurar el acceso universal a la salud sexual y reproductiva y los derechos reproductivos según lo acordado de conformidad con el Programa de Acción de la Conferencia Internacional sobre la Población y el Desarrollo, la Plataforma de Acción de Beijing y los documentos finales de sus conferencias de examen',
    target5_a:'Emprender reformas que otorguen a las mujeres igualdad de derechos a los recursos económicos, así como acceso a la propiedad y al control de la tierra y otros tipos de bienes, los servicios financieros, la herencia y los recursos naturales, de conformidad con las leyes nacionales',
    target5_b:'Mejorar el uso de la tecnología instrumental, en particular la tecnología de la información y las comunicaciones, para promover el empoderamiento de las mujeres',
    target5_c:'Aprobar y fortalecer políticas acertadas y leyes aplicables para promover la igualdad de género y el empoderamiento de todas las mujeres y las niñas a todos los niveles',
    desc6:'Si bien se ha conseguido progresar de manera sustancial a la hora de ampliar el acceso a agua potable y saneamiento, existen miles de millones de personas (principalmente en áreas rurales) que aún carecen de estos servicios básicos. En todo el mundo, una de cada tres personas no tiene acceso a agua potable salubre, dos de cada cinco personas no disponen de una instalación básica destinada a lavarse las manos con agua y jabón, y más de 673 millones de personas aún defecan al aire libre.',
    6:'Agua limpia y saneamiento',
    target6_1:'De aquí a 2030, lograr el acceso universal y equitativo al agua potable a un precio asequible para todos',
    target6_2:'De aquí a 2030, lograr el acceso a servicios de saneamiento e higiene adecuados y equitativos para todos y poner fin a la defecación al aire libre, prestando especial atención a las necesidades de las mujeres y las niñas y las personas en situaciones de vulnerabilidad',
    target6_3:'De aquí a 2030, mejorar la calidad del agua reduciendo la contaminación, eliminando el vertimiento y minimizando la emisión de productos químicos y materiales peligrosos, reduciendo a la mitad el porcentaje de aguas residuales sin tratar y aumentando considerablemente el reciclado y la reutilización sin riesgos a nivel mundial',
    target6_4:'De aquí a 2030, aumentar considerablemente el uso eficiente de los recursos hídricos en todos los sectores y asegurar la sostenibilidad de la extracción y el abastecimiento de agua dulce para hacer frente a la escasez de agua y reducir considerablemente el número de personas que sufren falta de agua',
    target6_5:'De aquí a 2030, implementar la gestión integrada de los recursos hídricos a todos los niveles, incluso mediante la cooperación transfronteriza, según proceda',
    target6_6:'De aquí a 2020, proteger y restablecer los ecosistemas relacionados con el agua, incluidos los bosques, las montañas, los humedales, los ríos, los acuíferos y los lagos',
    target6_a:'De aquí a 2030, ampliar la cooperación internacional y el apoyo prestado a los países en desarrollo para la creación de capacidad en actividades y programas relativos al agua y el saneamiento, como los de captación de agua, desalinización, uso eficiente de los recursos hídricos, tratamiento de aguas residuales, reciclado y tecnologías de reutilización',
    target6_b:'Apoyar y fortalecer la participación de las comunidades locales en la mejora de la gestión del agua y el saneamiento',
    desc7:'El mundo está avanzando hacia la consecución del Objetivo 7 con indicios alentadores de que la energía se está volviendo más sostenible y ampliamente disponible. El acceso a la electricidad en los países más pobres ha comenzado a acelerarse, la eficiencia energética continúa mejorando y la energía renovable está logrando resultados excelentes en el sector eléctrico. A pesar de ello, es necesario prestar una mayor atención a las mejoras para el acceso a combustibles de cocina limpios y seguros, y a tecnologías para 3000 millones de personas, para expandir el uso de la energía renovable más allá del sector eléctrico e incrementar la electrificación en el África subsahariana',
    7:'Energía asequible y no contaminante',
    target7_1:'De aquí a 2030, garantizar el acceso universal a servicios energéticos asequibles, fiables y modernos',
    target7_2:'De aquí a 2030, aumentar considerablemente la proporción de energía renovable en el conjunto de fuentes energéticas',
    target7_3:'De aquí a 2030, duplicar la tasa mundial de mejora de la eficiencia energética',
    target7_a:'De aquí a 2030, aumentar la cooperación internacional para facilitar el acceso a la investigación y la tecnología relativas a la energía limpia, incluidas las fuentes renovables, la eficiencia energética y las tecnologías avanzadas y menos contaminantes de combustibles fósiles, y promover la inversión en infraestructura energética y tecnologías limpias',
    target7_b:'De aquí a 2030, ampliar la infraestructura y mejorar la tecnología para prestar servicios energéticos modernos y sostenibles para todos en los países en desarrollo, en particular los países menos adelantados, los pequeños Estados insulares en desarrollo y los países en desarrollo sin litoral, en consonancia con sus respectivos programas de apoyo',
    desc8:'Un crecimiento económico inclusivo y sostenido puede impulsar el progreso, crear empleos decentes para todos y mejorar los estándares de vida.',
    8:'Trabajo decente y crecimiento económico',
    target8_1:'Mantener el crecimiento económico per capita de conformidad con las circunstancias nacionales y, en particular, un crecimiento del producto interno bruto de al menos el 7% anual en los países menos adelantados',
    target8_2:'Lograr niveles más elevados de productividad económica mediante la diversificación, la modernización tecnológica y la innovación, entre otras cosas centrándose en los sectores con gran valor añadido y un uso intensivo de la mano de obra',
    target8_3:'Promover políticas orientadas al desarrollo que apoyen las actividades productivas, la creación de puestos de trabajo decentes, el emprendimiento, la creatividad y la innovación, y fomentar la formalización y el crecimiento de las microempresas y las pequeñas y medianas empresas, incluso mediante el acceso a servicios financieros',
    target8_4:'Mejorar progresivamente, de aquí a 2030, la producción y el consumo eficientes de los recursos mundiales y procurar desvincular el crecimiento económico de la degradación del medio ambiente, conforme al Marco Decenal de Programas sobre modalidades de Consumo y Producción Sostenibles, empezando por los países desarrollados',
    target8_5:'De aquí a 2030, lograr el empleo pleno y productivo y el trabajo decente para todas las mujeres y los hombres, incluidos los jóvenes y las personas con discapacidad, así como la igualdad de remuneración por trabajo de igual valor',
    target8_6:'De aquí a 2020, reducir considerablemente la proporción de jóvenes que no están empleados y no cursan estudios ni reciben capacitación',
    target8_7:'Adoptar medidas inmediatas y eficaces para erradicar el trabajo forzoso, poner fin a las formas contemporáneas de esclavitud y la trata de personas y asegurar la prohibición y eliminación de las peores formas de trabajo infantil, incluidos el reclutamiento y la utilización de niños soldados, y, de aquí a 2025, poner fin al trabajo infantil en todas sus formas',
    target8_8:'Proteger los derechos laborales y promover un entorno de trabajo seguro y sin riesgos para todos los trabajadores, incluidos los trabajadores migrantes, en particular las mujeres migrantes y las personas con empleos precarios',
    target8_9:'De aquí a 2030, elaborar y poner en práctica políticas encaminadas a promover un turismo sostenible que cree puestos de trabajo y promueva la cultura y los productos locales',
    target8_10:'Fortalecer la capacidad de las instituciones financieras nacionales para fomentar y ampliar el acceso a los servicios bancarios, financieros y de seguros para todos',
    target8_a:'Aumentar el apoyo a la iniciativa de ayuda para el comercio en los países en desarrollo, en particular los países menos adelantados, incluso mediante el Marco Integrado Mejorado para la Asistencia Técnica a los Países Menos Adelantados en Materia de Comercio',
    target8_b:'De aquí a 2020, desarrollar y poner en marcha una estrategia mundial para el empleo de los jóvenes y aplicar el Pacto Mundial para el Empleo de la Organización Internacional del Trabajo',
    desc9:'La industrialización inclusiva y sostenible, junto con la innovación y la infraestructura, pueden dar rienda suelta a las fuerzas económicas dinámicas y competitivas que generan el empleo y los ingresos. Estas desempeñan un papel clave a la hora de introducir y promover nuevas tecnologías, facilitar el comercio internacional y permitir el uso eficiente de los recursos. Sin embargo, todavía queda un largo camino que recorrer para que el mundo pueda aprovechar al máximo este potencial. En especial, los países menos desarrollados necesitan acelerar el desarrollo de sus sectores manufactureros si desean conseguir la meta de 2030 y aumentar la inversión en investigación e innovación científicas.',
    9:'Industria, innovación e infraestructuras',
    target9_1:'Desarrollar infraestructuras fiables, sostenibles, resilientes y de calidad, incluidas infraestructuras regionales y transfronterizas, para apoyar el desarrollo económico y el bienestar humano, haciendo especial hincapié en el acceso asequible y equitativo para todos',
    target9_2:'Promover una industrialización inclusiva y sostenible y, de aquí a 2030, aumentar significativamente la contribución de la industria al empleo y al producto interno bruto, de acuerdo con las circunstancias nacionales, y duplicar esa contribución en los países menos adelantados',
    target9_3:'Aumentar el acceso de las pequeñas industrias y otras empresas, particularmente en los países en desarrollo, a los servicios financieros, incluidos créditos asequibles, y su integración en las cadenas de valor y los mercados',
    target9_4:'De aquí a 2030, modernizar la infraestructura y reconvertir las industrias para que sean sostenibles, utilizando los recursos con mayor eficacia y promoviendo la adopción de tecnologías y procesos industriales limpios y ambientalmente racionales, y logrando que todos los países tomen medidas de acuerdo con sus capacidades respectivas',
    target9_5:'Aumentar la investigación científica y mejorar la capacidad tecnológica de los sectores industriales de todos los países, en particular los países en desarrollo, entre otras cosas fomentando la innovación y aumentando considerablemente, de aquí a 2030, el número de personas que trabajan en investigación y desarrollo por millón de habitantes y los gastos de los sectores público y privado en investigación y desarrollo',
    target9_a:'Facilitar el desarrollo de infraestructuras sostenibles y resilientes en los países en desarrollo mediante un mayor apoyo financiero, tecnológico y técnico a los países africanos, los países menos adelantados, los países en desarrollo sin litoral y los pequeños Estados insulares en desarrollo',
    target9_b:'Apoyar el desarrollo de tecnologías, la investigación y la innovación nacionales en los países en desarrollo, incluso garantizando un entorno normativo propicio a la diversificación industrial y la adición de valor a los productos básicos, entre otras cosas',
    target9_c:'Aumentar significativamente el acceso a la tecnología de la información y las comunicaciones y esforzarse por proporcionar acceso universal y asequible a Internet en los países menos adelantados de aquí a 2020',
    desc10:'Reducir las desigualdades y garantizar que nadie se queda atrás forma parte integral de la consecución de los Objetivos de Desarrollo Sostenible. La desigualdad dentro de los países y entre estos es un continuo motivo de preocupación. A pesar de la existencia de algunos indicios positivos hacia la reducción de la desigualdad en algunas dimensiones, como la reducción de la desigualdad de ingresos en algunos países y el estatus comercial preferente que beneficia a los países de bajos ingresos, la desigualdad aún continúa.',
    10:'Reducción de las desigualdades',
    target10_1:'De aquí a 2030, lograr progresivamente y mantener el crecimiento de los ingresos del 40% más pobre de la población a una tasa superior a la media nacional',
    target10_2:'De aquí a 2030, potenciar y promover la inclusión social, económica y política de todas las personas, independientemente de su edad, sexo, discapacidad, raza, etnia, origen, religión o situación económica u otra condición',
    target10_3:'Garantizar la igualdad de oportunidades y reducir la desigualdad de resultados, incluso eliminando las leyes, políticas y prácticas discriminatorias y promoviendo legislaciones, políticas y medidas adecuadas a ese respecto',
    target10_4:'Adoptar políticas, especialmente fiscales, salariales y de protección social, y lograr progresivamente una mayor igualdad',
    target10_5:'Mejorar la reglamentación y vigilancia de las instituciones y los mercados financieros mundiales y fortalecer la aplicación de esos reglamentos',
    target10_6:'Asegurar una mayor representación e intervención de los países en desarrollo en las decisiones adoptadas por las instituciones económicas y financieras internacionales para aumentar la eficacia, fiabilidad, rendición de cuentas y legitimidad de esas instituciones',
    target10_7:'Facilitar la migración y la movilidad ordenadas, seguras, regulares y responsables de las personas, incluso mediante la aplicación de políticas migratorias planificadas y bien gestionadas',
    target10_a:'Aplicar el principio del trato especial y diferenciado para los países en desarrollo, en particular los países menos adelantados, de conformidad con los acuerdos de la Organización Mundial del Comercio',
    target10_b:'Fomentar la asistencia oficial para el desarrollo y las corrientes financieras, incluida la inversión extranjera directa, para los Estados con mayores necesidades, en particular los países menos adelantados, los países africanos, los pequeños Estados insulares en desarrollo y los países en desarrollo sin litoral, en consonancia con sus planes y programas nacionales',
    target10_c:'De aquí a 2030, reducir a menos del 3% los costos de transacción de las remesas de los migrantes y eliminar los corredores de remesas con un costo superior al 5%',
    desc11:'El mundo cada vez está más urbanizado. Desde 2007, más de la mitad de la población mundial ha estado viviendo en ciudades, y se espera que dicha cantidad aumente hasta el 60 % para 2030. Las ciudades y las áreas metropolitanas son centros neurálgicos del crecimiento económico, ya que contribuyen al 60 % aproximadamente del PIB mundial. Sin embargo, también representan alrededor del 70 % de las emisiones de carbono mundiales y más del 60 % del uso de recursos. La rápida urbanización está dando como resultado un número creciente de habitantes en barrios pobres, infraestructuras y servicios inadecuados y sobrecargados (como la recogida de residuos y los sistemas de agua y saneamiento, carreteras y transporte), lo cual está empeorando la contaminación del aire y el crecimiento urbano incontrolado.',
    11:'Ciudades y comunidades sostenibles',
    target11_1:'De aquí a 2030, asegurar el acceso de todas las personas a viviendas y servicios básicos adecuados, seguros y asequibles y mejorar los barrios marginales',
    target11_2:'De aquí a 2030, proporcionar acceso a sistemas de transporte seguros, asequibles, accesibles y sostenibles para todos y mejorar la seguridad vial, en particular mediante la ampliación del transporte público, prestando especial atención a las necesidades de las personas en situación de vulnerabilidad, las mujeres, los niños, las personas con discapacidad y las personas de edad',
    target11_3:'De aquí a 2030, aumentar la urbanización inclusiva y sostenible y la capacidad para la planificación y la gestión participativas, integradas y sostenibles de los asentamientos humanos en todos los países',
    target11_4:'Redoblar los esfuerzos para proteger y salvaguardar el patrimonio cultural y natural del mundo',
    target11_5:'De aquí a 2030, reducir significativamente el número de muertes causadas por los desastres, incluidos los relacionados con el agua, y de personas afectadas por ellos, y reducir considerablemente las pérdidas económicas directas provocadas por los desastres en comparación con el producto interno bruto mundial, haciendo especial hincapié en la protección de los pobres y las personas en situaciones de vulnerabilidad',
    target11_6:'De aquí a 2030, reducir el impacto ambiental negativo per capita de las ciudades, incluso prestando especial atención a la calidad del aire y la gestión de los desechos municipales y de otro tipo',
    target11_7:'De aquí a 2030, proporcionar acceso universal a zonas verdes y espacios públicos seguros, inclusivos y accesibles, en particular para las mujeres y los niños, las personas de edad y las personas con discapacidad',
    target11_a:'Apoyar los vínculos económicos, sociales y ambientales positivos entre las zonas urbanas, periurbanas y rurales fortaleciendo la planificación del desarrollo nacional y regional',
    target11_b:'De aquí a 2020, aumentar considerablemente el número de ciudades y asentamientos humanos que adoptan e implementan políticas y planes integrados para promover la inclusión, el uso eficiente de los recursos, la mitigación del cambio climático y la adaptación a él y la resiliencia ante los desastres, y desarrollar y poner en práctica, en consonancia con el Marco de Sendai para la Reducción del Riesgo de Desastres 2015-2030, la gestión integral de los riesgos de desastre a todos los niveles',
    target11_c:'Proporcionar apoyo a los países menos adelantados, incluso mediante asistencia financiera y técnica, para que puedan construir edificios sostenibles y resilientes utilizando materiales locales',
    desc12:'El consumo y la producción mundiales (fuerzas impulsoras de la economía mundial) dependen del uso del medio ambiente natural y de los recursos de una manera que continúa teniendo efectos destructivos sobre el planeta. El progreso económico y social conseguido durante el último siglo ha estado acompañado de una degradación medioambiental que está poniendo en peligro los mismos sistemas de los que depende nuestro desarrollo futuro (y ciertamente, nuestra supervivencia).',
    12:'Producción y consumo responsables',
    target12_1:'Aplicar el Marco Decenal de Programas sobre Modalidades de Consumo y Producción Sostenibles, con la participación de todos los países y bajo el liderazgo de los países desarrollados, teniendo en cuenta el grado de desarrollo y las capacidades de los países en desarrollo',
    target12_2:'De aquí a 2030, lograr la gestión sostenible y el uso eficiente de los recursos naturales',
    target12_3:'De aquí a 2030, reducir a la mitad el desperdicio de alimentos per capita mundial en la venta al por menor y a nivel de los consumidores y reducir las pérdidas de alimentos en las cadenas de producción y suministro, incluidas las pérdidas posteriores a la cosecha',
    target12_4:'De aquí a 2020, lograr la gestión ecológicamente racional de los productos químicos y de todos los desechos a lo largo de su ciclo de vida, de conformidad con los marcos internacionales convenidos, y reducir significativamente su liberación a la atmósfera, el agua y el suelo a fin de minimizar sus efectos adversos en la salud humana y el medio ambiente',
    target12_5:'De aquí a 2030, reducir considerablemente la generación de desechos mediante actividades de prevención, reducción, reciclado y reutilización',
    target12_6:'Alentar a las empresas, en especial las grandes empresas y las empresas transnacionales, a que adopten prácticas sostenibles e incorporen información sobre la sostenibilidad en su ciclo de presentación de informes',
    target12_7:'Promover prácticas de adquisición pública que sean sostenibles, de conformidad con las políticas y prioridades nacionales',
    target12_8:'De aquí a 2030, asegurar que las personas de todo el mundo tengan la información y los conocimientos pertinentes para el desarrollo sostenible y los estilos de vida en armonía con la naturaleza',
    target12_a:'Ayudar a los países en desarrollo a fortalecer su capacidad científica y tecnológica para avanzar hacia modalidades de consumo y producción más sostenibles',
    target12_b:'Elaborar y aplicar instrumentos para vigilar los efectos en el desarrollo sostenible, a fin de lograr un turismo sostenible que cree puestos de trabajo y promueva la cultura y los productos locales',
    target12_c:'Racionalizar los subsidios ineficientes a los combustibles fósiles que fomentan el consumo antieconómico eliminando las distorsiones del mercado, de acuerdo con las circunstancias nacionales, incluso mediante la reestructuración de los sistemas tributarios y la eliminación gradual de los subsidios perjudiciales, cuando existan, para reflejar su impacto ambiental, teniendo plenamente en cuenta las necesidades y condiciones específicas de los países en desarrollo y minimizando los posibles efectos adversos en su desarrollo, de manera que se proteja a los pobres y a las comunidades afectadas',
    desc13:'El 2019 fue el segundo año más caluroso de todos los tiempos y marcó el final de la década más calurosa (2010-2019) que se haya registrado jamás. Los niveles de dióxido de carbono (CO2) y de otros gases de efecto invernadero en la atmósfera aumentaron hasta niveles récord en 2019. El cambio climático está afectando a todos los países de todos los continentes. Está alterando las economías nacionales y afectando a distintas vidas. Los sistemas meteorológicos están cambiando, los niveles del mar están subiendo y los fenómenos meteorológicos son cada vez más extremos.',
    13:'Acción por el clima',
    target13_1:'Fortalecer la resiliencia y la capacidad de adaptación a los riesgos relacionados con el clima y los desastres naturales en todos los países',
    target13_2:'Incorporar medidas relativas al cambio climático en las políticas, estrategias y planes nacionales',
    target13_3:'Mejorar la educación, la sensibilización y la capacidad humana e institucional respecto de la mitigación del cambio climático, la adaptación a él, la reducción de sus efectos y la alerta temprana',
    target13_a:'Cumplir el compromiso de los países desarrollados que son partes en la Convención Marco de las Naciones Unidas sobre el Cambio Climático de lograr para el año 2020 el objetivo de movilizar conjuntamente 100.000 millones de dólares anuales procedentes de todas las fuentes a fin de atender las necesidades de los países en desarrollo respecto de la adopción de medidas concretas de mitigación y la transparencia de su aplicación, y poner en pleno funcionamiento el Fondo Verde para el Clima capitalizándolo lo antes posible',
    target13_b:'Promover mecanismos para aumentar la capacidad para la planificación y gestión eficaces en relación con el cambio climático en los países menos adelantados y los pequeños Estados insulares en desarrollo, haciendo particular hincapié en las mujeres, los jóvenes y las comunidades locales y marginadas',
    desc14:'El océano impulsa los sistemas mundiales que hacen de la Tierra un lugar habitable para el ser humano. Nuestra lluvia, el agua potable, el tiempo, el clima, los litorales, gran parte de nuestra comida e incluso el oxígeno del aire que respiramos los proporciona y regula el mar. Una gestión cuidadosa de este recurso mundial esencial es una característica clave de un futuro sostenible. No obstante, en la actualidad, existe un deterioro continuo de las aguas costeras debido a la contaminación y a la acidificación de los océanos que está teniendo un efecto adverso sobre el funcionamiento de los ecosistemas y la biodiversidad. Asimismo, también está teniendo un impacto perjudicial sobre las pesquerías de pequeña escala. Proteger nuestros océanos debe seguir siendo una prioridad. La biodiversidad marina es vital para la salud de las personas y de nuestro planeta. Las áreas marinas protegidas se deben gestionar de manera efectiva, al igual que sus recursos, y se deben poner en marcha reglamentos que reduzcan la sobrepesca, la contaminación marina y la acidificación de los océanos',
    14:'Vida submarina',
    target14_1:'De aquí a 2025, prevenir y reducir significativamente la contaminación marina de todo tipo, en particular la producida por actividades realizadas en tierra, incluidos los detritos marinos y la polución por nutrientes',
    target14_2:'De aquí a 2020, gestionar y proteger sosteniblemente los ecosistemas marinos y costeros para evitar efectos adversos importantes, incluso fortaleciendo su resiliencia, y adoptar medidas para restaurarlos a fin de restablecer la salud y la productividad de los océanos',
    target14_3:'Minimizar y abordar los efectos de la acidificación de los océanos, incluso mediante una mayor cooperación científica a todos los niveles',
    target14_4:'De aquí a 2020, reglamentar eficazmente la explotación pesquera y poner fin a la pesca excesiva, la pesca ilegal, no declarada y no reglamentada y las prácticas pesqueras destructivas, y aplicar planes de gestión con fundamento científico a fin de restablecer las poblaciones de peces en el plazo más breve posible, al menos alcanzando niveles que puedan producir el máximo rendimiento sostenible de acuerdo con sus características biológicas',
    target14_5:'De aquí a 2020, conservar al menos el 10% de las zonas costeras y marinas, de conformidad con las leyes nacionales y el derecho internacional y sobre la base de la mejor información científica disponible',
    target14_6:'De aquí a 2020, prohibir ciertas formas de subvenciones a la pesca que contribuyen a la sobrecapacidad y la pesca excesiva, eliminar las subvenciones que contribuyen a la pesca ilegal, no declarada y no reglamentada y abstenerse de introducir nuevas subvenciones de esa índole, reconociendo que la negociación sobre las subvenciones a la pesca en el marco de la Organización Mundial del Comercio debe incluir un trato especial y diferenciado, apropiado y efectivo para los países en desarrollo y los países menos adelantados',
    target14_7:'De aquí a 2030, aumentar los beneficios económicos que los pequeños Estados insulares en desarrollo y los países menos adelantados obtienen del uso sostenible de los recursos marinos, en particular mediante la gestión sostenible de la pesca, la acuicultura y el turismo',
    target14_a:'Aumentar los conocimientos científicos, desarrollar la capacidad de investigación y transferir tecnología marina, teniendo en cuenta los Criterios y Directrices para la Transferencia de Tecnología Marina de la Comisión Oceanográfica Intergubernamental, a fin de mejorar la salud de los océanos y potenciar la contribución de la biodiversidad marina al desarrollo de los países en desarrollo, en particular los pequeños EstFacilitar el acceso de los pescadores artesanales a los recursos marinos y los mercados',
    target14_c:'Mejorar la conservación y el uso sostenible de los océanos y sus recursos aplicando el derecho internacional reflejado en la Convención de las Naciones Unidas sobre el Derecho del Mar, que constituye el marco jurídico para la conservación y la utilización sostenible de los océanos y sus recursos, como se recuerda en el párrafo 158 del documento “El futuro que queremos”',
    desc15:'En 2016, el Programa de las Naciones Unidas para el Medio Ambiente (PNUMA) alertó de que un aumento mundial de las epidemias zoonóticas era motivo de preocupación. En concreto, señaló que el 75 % de todas las enfermedades infecciosas nuevas en humanos son zoonóticas y que dichas enfermedades están estrechamente relacionadas con la salud de los ecosistemas. En Trabajar con el medio ambiente para proteger a las personas, el PNUMA detalla cómo «reconstruir mejor», mediante una base científica más sólida, políticas que contribuyan a un planeta más sano y más inversiones verdes.',
    15:'Vida de ecosistemas terrestres',
    target15_1:'Para 2020, velar por la conservación, el restablecimiento y el uso sostenible de los ecosistemas terrestres y los ecosistemas interiores de agua dulce y los servicios que proporcionan, en particular los bosques, los humedales, las montañas y las zonas áridas, en consonancia con las obligaciones contraídas en virtud de acuerdos internacionales',
    target15_2:'Para 2020, promover la gestión sostenible de todos los tipos de bosques, poner fin a la deforestación, recuperar los bosques degradados e incrementar la forestación y la reforestación a nivel mundial',
    target15_3:'Para 2030, luchar contra la desertificación, rehabilitar las tierras y los suelos degradados, incluidas las tierras afectadas por la desertificación, la sequía y las inundaciones, y procurar lograr un mundo con una degradación neutra del suelo',
    target15_4:'Para 2030, velar por la conservación de los ecosistemas montañosos, incluida su diversidad biológica, a fin de mejorar su capacidad de proporcionar beneficios esenciales para el desarrollo sostenible',
    target15_5:'Adoptar medidas urgentes y significativas para reducir la degradación de los hábitats naturales, detener la pérdida de la diversidad biológica y, para 2020, proteger las especies amenazadas y evitar su extinción',
    target15_6:'Promover la participación justa y equitativa en los beneficios que se deriven de la utilización de los recursos genéticos y promover el acceso adecuado a esos recursos, como se ha convenido internacionalmente',
    target15_7:'Adoptar medidas urgentes para poner fin a la caza furtiva y el tráfico de especies protegidas de flora y fauna y abordar la demanda y la oferta ilegales de productos silvestres',
    target15_8:'Para 2020, adoptar medidas para prevenir la introducción de especies exóticas invasoras y reducir de forma significativa sus efectos en los ecosistemas terrestres y acuáticos y controlar o erradicar las especies prioritarias',
    target15_9:'Para 2020, integrar los valores de los ecosistemas y la diversidad biológica en la planificación nacional y local, los procesos de desarrollo, las estrategias de reducción de la pobreza y la contabilidad',
    target15_a:'Movilizar y aumentar de manera significativa los recursos financieros procedentes de todas las fuentes para conservar y utilizar de forma sostenible la diversidad biológica y los ecosistemas',
    target15_b:'Movilizar un volumen apreciable de recursos procedentes de todas las fuentes y a todos los niveles para financiar la gestión forestal sostenible y proporcionar incentivos adecuados a los países en desarrollo para que promuevan dicha gestión, en particular con miras a la conservación y la reforestación',
    target15_c:'Aumentar el apoyo mundial a la lucha contra la caza furtiva y el tráfico de especies protegidas, en particular aumentando la capacidad de las comunidades locales para promover oportunidades de subsistencia sostenibles',
    desc16:'Los conflictos, la inseguridad, las instituciones débiles y el acceso limitado a la justicia continúan suponiendo una grave amenaza para el desarrollo sostenible. El número de personas que huyen de las guerras, las persecuciones y los conflictos superó los 70 millones en 2018, la cifra más alta registrada por la Oficina del Alto Comisionado de las Naciones Unidas para los Refugiados (ACNUR) en casi 70 años. En 2019, las Naciones Unidas registraron 357 asesinatos y 30 desapariciones forzadas de defensores de los derechos humanos, periodistas y sindicalistas en 47 países. Por otro lado, los nacimientos de alrededor de uno de cada cuatro niños en todo el mundo con menos de 5 años nunca se registran de manera oficial, lo que les priva de una prueba de identidad legal, que es crucial para la protección de sus derechos y para el acceso a la justicia y a los servicios sociales.',
    16:'Paz, justicia e instituciones sólidas',
    target16_1:'Reducir significativamente todas las formas de violencia y las correspondientes tasas de mortalidad en todo el mundo',
    target16_2:'Poner fin al maltrato, la explotación, la trata y todas las formas de violencia y tortura contra los niños',
    target16_3:'Promover el estado de derecho en los planos nacional e internacional y garantizar la igualdad de acceso a la justicia para todos',
    target16_4:'De aquí a 2030, reducir significativamente las corrientes financieras y de armas ilícitas, fortalecer la recuperación y devolución de los activos robados y luchar contra todas las formas de delincuencia organizada',
    target16_5:'Reducir considerablemente la corrupción y el soborno en todas sus formas',
    target16_6:'Crear a todos los niveles instituciones eficaces y transparentes que rindan cuentas',
    target16_7:'Garantizar la adopción en todos los niveles de decisiones inclusivas, participativas y representativas que respondan a las necesidades',
    target16_8:'Ampliar y fortalecer la participación de los países en desarrollo en las instituciones de gobernanza mundial',
    target16_9:'De aquí a 2030, proporcionar acceso a una identidad jurídica para todos, en particular mediante el registro de nacimientos',
    target16_10:'Garantizar el acceso público a la información y proteger las libertades fundamentales, de conformidad con las leyes nacionales y los acuerdos internacionales',
    target16_a:'Fortalecer las instituciones nacionales pertinentes, incluso mediante la cooperación internacional, para crear a todos los niveles, particularmente en los países en desarrollo, la capacidad de prevenir la violencia y combatir el terrorismo y la delincuencia',
    target16_b:'Promover y aplicar leyes y políticas no discriminatorias en favor del desarrollo sostenible',
    desc17:'Los ODS solo se pueden conseguir con asociaciones mundiales sólidas y cooperación. Para que un programa de desarrollo se cumpla satisfactoriamente, es necesario establecer asociaciones inclusivas (a nivel mundial, regional, nacional y local) sobre principios y valores, así como sobre una visión y unos objetivos compartidos que se centren primero en las personas y el planeta. Muchos países requieren asistencia oficial para el desarrollo con el fin de fomentar el crecimiento y el comercio. Aun así, los niveles de ayuda están disminuyendo y los países donantes no han respetado su compromiso de aumentar la financiación para el desarrollo.',
    17:'Alianzas para lograr los objectivos',
    target17_1:'Fortalecer la movilización de recursos internos, incluso mediante la prestación de apoyo internacional a los países en desarrollo, con el fin de mejorar la capacidad nacional para recaudar ingresos fiscales y de otra índole',
    target17_2:'Velar por que los países desarrollados cumplan plenamente sus compromisos en relación con la asistencia oficial para el desarrollo, incluido el compromiso de numerosos países desarrollados de alcanzar el objetivo de destinar el 0,7% del ingreso nacional bruto a la asistencia oficial para el desarrollo de los países en desarrollo y entre el 0,15% y el 0,20% del ingreso nacional bruto a la asistencia oficial para el desarrollo de los países menos adelantados; se alienta a los proveedores de asistencia oficial para el desarrollo a que consideren la posibilidad de fijar una meta para destinar al menos el 0,20% del ingreso nacional bruto a la asistencia oficial para el desarrollo de los países menos adelantados',
    target17_3:'Movilizar recursos financieros adicionales de múltiples fuentes para los países en desarrollo',
    target17_4:'Ayudar a los países en desarrollo a lograr la sostenibilidad de la deuda a largo plazo con políticas coordinadas orientadas a fomentar la financiación, el alivio y la reestructuración de la deuda, según proceda, y hacer frente a la deuda externa de los países pobres muy endeudados a fin de reducir el endeudamiento excesivo',
    target17_5:'Adoptar y aplicar sistemas de promoción de las inversiones en favor de los países menos adelantados',
    target17_6:'Mejorar la cooperación regional e internacional Norte-Sur, Sur-Sur y triangular en materia de ciencia, tecnología e innovación y el acceso a estas, y aumentar el intercambio de conocimientos en condiciones mutuamente convenidas, incluso mejorando la coordinación entre los mecanismos existentes, en particular a nivel de las Naciones Unidas, y mediante un mecanismo mundial de facilitación de la tecnología',
    target17_7:'Promover el desarrollo de tecnologías ecológicamente racionales y su transferencia, divulgación y difusión a los países en desarrollo en condiciones favorables, incluso en condiciones concesionarias y preferenciales, según lo convenido de mutuo acuerdo',
    target17_8:'Poner en pleno funcionamiento, a más tardar en 2017, el banco de tecnología y el mecanismo de apoyo a la creación de capacidad en materia de ciencia, tecnología e innovación para los países menos adelantados y aumentar la utilización de tecnologías instrumentales, en particular la tecnología de la información y las comunicaciones',
    target17_9:'Aumentar el apoyo internacional para realizar actividades de creación de capacidad eficaces y específicas en los países en desarrollo a fin de respaldar los planes nacionales de implementación de todos los Objetivos de Desarrollo Sostenible, incluso mediante la cooperación Norte-Sur, Sur-Sur y triangular',
    target17_10:'Promover un sistema de comercio multilateral universal, basado en normas, abierto, no discriminatorio y equitativo en el marco de la Organización Mundial del Comercio, incluso mediante la conclusión de las negociaciones en el marco del Programa de Doha para el Desarrollo',
    target17_11:'Aumentar significativamente las exportaciones de los países en desarrollo, en particular con miras a duplicar la participación de los países menos adelantados en las exportaciones mundiales de aquí a 2020',
    target17_12:'Lograr la consecución oportuna del acceso a los mercados libre de derechos y contingentes de manera duradera para todos los países menos adelantados, conforme a las decisiones de la Organización Mundial del Comercio, incluso velando por que las normas de origen preferenciales aplicables a las importaciones de los países menos adelantados sean transparentes y sencillas y contribuyan a facilitar el acceso a los mercados',
    target17_13:'Aumentar la estabilidad macroeconómica mundial, incluso mediante la coordinación y coherencia de las políticas',
    target17_14:'Mejorar la coherencia de las políticas para el desarrollo sostenible',
    target17_15:'Respetar el margen normativo y el liderazgo de cada país para establecer y aplicar políticas de erradicación de la pobreza y desarrollo sostenible',
    target17_16:'Mejorar la Alianza Mundial para el Desarrollo Sostenible, complementada por alianzas entre múltiples interesados que movilicen e intercambien conocimientos, especialización, tecnología y recursos financieros, a fin de apoyar el logro de los Objetivos de Desarrollo Sostenible en todos los países, particularmente los países en desarrollo',
    target17_17:'Fomentar y promover la constitución de alianzas eficaces en las esferas pública, público-privada y de la sociedad civil, aprovechando la experiencia y las estrategias de obtención de recursos de las alianzas',
    target17_18:'De aquí a 2020, mejorar el apoyo a la creación de capacidad prestado a los países en desarrollo, incluidos los países menos adelantados y los pequeños Estados insulares en desarrollo, para aumentar significativamente la disponibilidad de datos oportunos, fiables y de gran calidad desglosados por ingresos, sexo, edad, raza, origen étnico, estatus migratorio, discapacidad, ubicación geográfica y otras características pertinentes en los contextos nacionales',
    target17_19:'De aquí a 2030, aprovechar las iniciativas existentes para elaborar indicadores que permitan medir los progresos en materia de desarrollo sostenible y complementen el producto interno bruto, y apoyar la creación de capacidad estadística en los países en desarrollo',
    // Temporary:
    // Development areas
    Arbeid_sysselsettning:'Trabajo y empleo',
    Bebyggelse:'Edificios',
    Digitalisering1:'Digitalización',
    Energi:'Energía',
    Helse_sosial_og_velferd:'Salud, social y bienestar',
    Kultur:'Cultura',
    Natur_og_miljø:'Naturaleza y entorno',
    Næring:'Industria',
    Oppvekst_og_utdanning:'Crianza y educación',
    Styring_og_demokrati:'Gobernanza y democracia',
    Transport:'Transporte',
    Trygghet_og_beredskap:'Seguridad y preparación',
    Vann_og_søppel:'Agua y basura',
    Økonomisk:'Económico',
    // TBL:
    Miljø:'Entorno',
    Sosialt:'Socialmente',
    Økonomi:'Economía',
    // Perspectives in Trdheim
    Arealer_og_ressursforvaltning:'Gestión de áreas y recursos',
    Det_grønne_skiftet:'El cambio verde',
    Digitalisering2:'Digitalización',
    Forbruk:'Consumo',
    Grønn_mobilitet:'Movilidad verde',
    Indentitet_og_kultur:'Identidad y cultura',
    Inkluderende_samfunn:'Sociedad inclusiva',
    Lokaldemokratiet:'Democracia local',
    Nærmiljø_og_stedsutvikling:'Entorno local y desarrollo del lugar',
    Oppvekst_og_læring:'Creciendo y aprendiendo',
    P1:'P1',
    Samarbeid_og_verdiskapning:'Cooperación y crecimiento económico',
    Samskapt_velferd:'Bienestar co-creado',
    Økonomi1:'Economía',
    // Icons:
    icon_1:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d0aebb20784479c2060/previews/5daf4d0aebb20784479c2089/download/S-WEB-Goal-01.png',
    icon_2:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d0bb628453d5f2623f2/previews/5daf4d0bb628453d5f2623fd/download/S-WEB-Goal-02.png',
    icon_3:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d0b66b56d5f0dd682c8/previews/5daf4d0c66b56d5f0dd682d1/download/S-WEB-Goal-03.png',
    icon_4:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d090e2ac45477f05f72/previews/5daf4d090e2ac45477f05f7f/download/S-WEB-Goal-04.png',
    icon_5:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d1bc093347b40d318dd/previews/5daf4d1cc093347b40d318e0/download/S-WEB-Goal-05.png',
    icon_6:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d1cc0b2c01307937f60/previews/5daf4d1dc0b2c01307937f6c/download/S-WEB-Goal-06.png',
    icon_7:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d1d4ab6728834ae7184/previews/5daf4d1e4ab6728834ae7199/download/S-WEB-Goal-07.png',
    icon_8:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d1e84c47f76b46abf11/previews/5daf4d1f84c47f76b46abf29/download/S-WEB-Goal-08.png',
    icon_9:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d1ad838108446432881/previews/5daf4d1bd8381084464328f5/download/S-WEB-Goal-09.png',
    icon_10:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d437106e3732a33da4e/previews/5daf4d447106e3732a33da60/download/S-WEB-Goal-10.png',
    icon_11:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d4443cbd84e907595c0/previews/5daf4d4543cbd84e9075964d/download/S-WEB-Goal-11.png',
    icon_12:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d450e2ac45477f06ba8/previews/5daf4d460e2ac45477f06bb7/download/S-WEB-Goal-12.png',
    icon_13:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d46bfcae772ec9b6adc/previews/5daf4d47bfcae772ec9b6b01/download/S-WEB-Goal-13.png',
    icon_14:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d3fe16cf93bb2fc4dfc/previews/5daf4d3fe16cf93bb2fc4dfd/download/S-WEB-Goal-14.png',
    icon_15:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d40d82f1a4c70d727a1/previews/5daf4d40d82f1a4c70d727ac/download/S-WEB-Goal-15.png',
    icon_16:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d41f8a4142e671de07c/previews/5daf4d41f8a4142e671de08f/download/S-WEB-Goal-16.png',
    icon_17:'https://trello.com/1/cards/5aeba536a9cefbbaf4bffd8c/attachments/5daf4d4263526566e4de9772/previews/5daf4d4363526566e4de9779/download/S-WEB-Goal-17.png',

};