export default {
    bulgarian: 'búlgaro',
    croatian: 'croata',
    czech: 'checo', 
    danish: 'danés', 
    dutch: 'neerlandés',
    english: 'inglés',
    estonian: 'estonio',
    finnish: 'finés',
    french: 'francés',
    german: 'alemán', 
    greek: 'griego',
    hungarian: 'húngaro',
    irish: 'irlandés',
    italian: 'italiano',
    latvian: 'letón',
    lithuanian: 'lituano',
    maltese: 'maltés',
    norwegian: 'noruego',
    polish: 'polaco',
    portuguese: 'portugués',
    romanian:'rumano',
    slovak: 'eslovaco',
    slovenian: 'esloveno',
    spanish: 'español',
    swedish: 'sueco'
}