export default {
    bg: 'búlgaro',
    hr: 'croata',
    cs: 'checo', 
    da: 'danés', 
    nl: 'neerlandés',
    en: 'inglés',
    et: 'estonio',
    fi: 'finés',
    fr: 'francés',
    de: 'alemán', 
    el: 'griego',
    hu: 'húngaro',
    ga: 'irlandés',
    it: 'ito',
    lv: 'letón',
    lt: 'lituano',
    mt: 'maltés',
    no: 'noruego',
    pl: 'polaco',
    pt: 'portugués',
    ro:'rumano',
    sk: 'eslovaco',
    sl: 'esloveno',
    es: 'español',
    sv: 'sueco'
}