export default {
    bulgarian: 'bulgaaria keel',
    croatian: 'horvaadi keel',
    czech: 'tšehhi keel', 
    danish: 'taani keel', 
    dutch: 'hollandi keel',
    english: 'inglise keel',
    estonian: 'eesti keel',
    finnish: 'soome keel',
    french: 'prantsuse keel',
    german: 'saksa keel', 
    greek: 'kreeka keel',
    hungarian: 'ungari keel',
    irish: 'iiri keel',
    italian: 'itaalia keel',
    latvian: 'läti keel',
    lithuanian: 'leedu keel',
    maltese: 'malta keel',
    norwegian: 'noruego',
    polish: 'poola keel',
    portuguese: 'portugali keel',
    romanian:'rumeenia keel',
    slovak: 'slovaki keel',
    slovenian: 'sloveenia keel',
    spanish: 'hispaania keel',
    swedish: 'rootsi keel'
}