export default {
    bg: 'bulgaaria keel',
    hr: 'horvaadi keel',
    cs: 'tšehhi keel', 
    da: 'taani keel', 
    nl: 'hollandi keel',
    en: 'inglise keel',
    et: 'eesti keel',
    fi: 'soome keel',
    fr: 'prantsuse keel',
    de: 'saksa keel', 
    el: 'kreeka keel',
    hu: 'ungari keel',
    ga: 'iiri keel',
    it: 'itaalia keel',
    lv: 'läti keel',
    lt: 'leedu keel',
    mt: 'malta keel',
    no: 'noruego',
    pl: 'poola keel',
    pt: 'portugali keel',
    ro:'rumeenia keel',
    sk: 'ski keel',
    sl: 'sloveenia keel',
    es: 'hispaania keel',
    sv: 'rootsi keel',
};