export default {
    bulgarian: 'bulgaria',
    croatian: 'kroatia',
    czech: 'tšekki', 
    danish: 'tanska', 
    dutch: 'saksa',
    english: 'englanti',
    estonian: 'viro',
    finnish: 'suomi',
    french: 'ranska',
    german: 'german', 
    greek: 'kreikka',
    hungarian: 'unkari',
    irish: 'iiri', 
    italian: 'italia',
    latvian: 'latvia',
    lithuanian: 'liettua',
    maltese: 'malta',
    norwegian: 'norjan kieli',
    polish: 'puola',
    portuguese: 'portugali',
    romanian:'romania',
    slovak: 'slovakki',
    slovenian: 'sloveeni',
    spanish: 'espanja',
    swedish: 'ruotsi'
}