export default {
    bg: 'bulgaria',
    hr: 'kroatia',
    cs: 'tšekki', 
    da: 'tanska', 
    nl: 'saksa',
    en: 'englanti',
    et: 'viro',
    fi: 'suomi',
    fr: 'ranska',
    de: 'de', 
    el: 'kreikka',
    hu: 'unkari',
    ga: 'iiri', 
    it: 'italia',
    lv: 'latvia',
    lt: 'liettua',
    mt: 'malta',
    no: 'norjan kieli',
    pl: 'puola',
    pt: 'portugali',
    ro:'romania',
    sk: 'skki',
    sl: 'sloveeni',
    es: 'espanja',
    sv: 'ruotsi',
};