export default {
    bg: 'bulgare',
    hr: 'croate',
    cs: 'tchèque', 
    da: 'danois', 
    nl: 'néerlandais',
    en: 'anglais',
    et: 'estonien',
    fi: 'finnois',
    fr: 'français',
    de: 'allemand', 
    el: 'grec',
    hu: 'hongrois',
    ga: 'irlandais', 
    it: 'italien',
    lv: 'letton',
    lt: 'lituanien',
    mt: 'maltais',
    no: 'norvégien',
    pl: 'polonais',
    pt: 'portugais',
    ro:'roumain',
    sk: 'slovaque',
    sl: 'slovène',
    es: 'espagnol',
    sv: 'suédois'
}