export default {
    bg: 'bulgare',
    hr: 'croate',
    cs: 'tchèque', 
    da: 'danois', 
    nl: 'néerlandais',
    en: 'anglais',
    et: 'estonien',
    fi: 'finnois',
    fr: 'français',
    de: 'allemand', 
    el: 'grec',
    hu: 'hongrois',
    ga: 'irlandais', 
    it: 'italien',
    lv: 'letton',
    lt: 'lituanien',
    mt: 'maltais',
    no: 'norvégien',
    pl: 'polonais',
    pt: 'portugais',
    ro:'roumain',
    sk: 'slovaque',
    sl: 'slovène',
    es: 'espagnol',
    sv: 'suédois',
    NoDocuments:'Désolé, il n`y a aucun document dans aucune des langues sélectionnées',
    About:'Pas de pauvreté',
    Home:'Page d`accueil',
    Close:'Proche',
    GoTo:'Va à',
    TheRelation:'La relation',
    hasDevelopmentArea:'aZoneDeDéveloppement',
    hasTradeoffTo:'aCompromisÀ',
    hasContributionTo:'aContribuéÀ',
    Correlation:'CorrélationÀ',
    Contribution:'Contribué',
    TradeOff: 'Compromis',
    DevelopmentAreaCamel:'ZoneDeDéveloppement',
    For:'Pour',
    To:'À',
    isA:'est un',
    binaryPositiveRelation:'relation binaire qui décrit qu`une classe/instance a une influence positive sur une autre classe/instance. La force de cette relation n`est pas définie, là où une relation entre deux classes/instances où seul "aContribuéÀ" est défini, signifie que le montant des contributions est indéfini. Voir respectivement "a (Élevé / Modéré / Faible) - CorrélationÀ" - sous les relations d`avoir Contribution à pour des influences positives plus bien définies.',
    ShowTargets:'Afficher les cibles',
    developmentAreaRelation:'relation binaire pour les concepts qui ont des domaines de développement. Selon la taxonomie de Statistics Norway, une zone de développement est définie par des perspectives. Où une zone de développement est un concept qui veut être amélioré. Par exemple, les concepts : Economie et Nature.',
    binaryNegativeRelation:'relation binaire qui décrit qu`une classe/instance a une influence negative sur une autre classe/instance. La force de cette relation n`est pas définie, là où une relation entre deux classes/instances où seul "aContribuéÀ" est défini, signifie que le montant des contributions est indéfini. Voir respectivement "a (Élevé / Modéré / Faible) - CorrélationÀ" - sous les relations d`avoir Contribution à pour des influences positives plus bien définies.',
    UknownMunicipality:'Commune inconnue',
    Loading:'Chargement',
    BackToHomePage:'Retour à l`accueil',
    Fullscreen:'Plein écran',
    StandardColor:'Couleur standard',
    Targets:'Objectifs et cibles',
    Target:'Cible',
    Tbl:'Triple bottom line',
    DevelopmentArea:'Zone de développement',
    ShowEdgeLabels:'Afficher les étiquettes d`arête',
    NameMissing:'Nom manquant',
    HasPositiveEffectOn: 'A un effet positif sur',
    HasNoEstablishedPositiveContributions: 'N`a pas de contributions positives établies',
    HasNegativeEffectOn: 'A un effet négatif sur',
    HasNoEstablishedNegativeContributions: 'N`a pas de contributions négatives établies',
    HasDevelopmentAreasFor: 'A des zones de développement pour',
    HasNoDevelopmentAreas: 'N`a pas de zones de développement',
    has:'a',
    aHigh:'un haut',
    High:'Haut',
    Low:'Bas',
    Moderate:'Modéré',
    aModerate:'un modéré',
    aLow:'un bas',
    to:'à',
    on:'sur',
    UnlockNodes:'Déverrouiller les nœuds',
    Sdg: 'Objectif de développement durable',
    positiveEffect:'effet positif',
    negativeEffect:'effet negatif',
    ConceptUnderDevelopment:'Concept en cours de développement',
    ChangeLanguage:'Changer de langue',
    effects:'effets',
    PositivePlural:'Positif',
    NegativePlural:'Négatif',
    DataUpload:'Téléchargement de données',
    ShowDocuments:'Afficher les documents',
    Show:'Montrer',
    GoalDistanceComputation:'Calcul de la distance de but',
    SearchDocuments:'Chercher des documents',
    Documents: 'Documents',
    ToTop: 'Défiler vers le haut',
    SeeMoreDocuments: 'Voir plus de documents',
    YourSearchReturned: 'Votre recherche a renvoyé',
    results: 'résultats',
    LanguagePriority:'Priorité linguistique',
    SearchLanguages:'Chercher des langues',
    Multilingual:'Multilingue',
    MoreInfo:'Plus d`informations',
    OpenAs:'Ouvrir en tant que',
    Active:'Actif',
    SeeRelatedGoals:'Voir les objectifs associés',
    Sdgs:'Objectifs de développement durable',
    SdgOntology:'ODD ontologie',
    Search:'Chercher',
    desc1:'Entre 1990 et 2015, le taux d`extrême pauvreté dans le monde a reculé, passant de 36 % à 10 %. Toutefois, le rythme du changement s`est ralenti et la crise liée à la COVID-19 risque hélas d`anéantir des décennies de progrès dans la lutte contre la pauvreté. Une nouvelle étude publiée par l`Institut mondial de recherche sur les aspects économiques du développement de l`Université des Nations Unies indique qu`un demi-milliard de personnes, soit 8 % de la population mondiale, risquent de tomber dans la pauvreté en raison des retombées économiques de la pandémie. Pour la première fois depuis 1990, la pauvreté pourrait donc augmenter au niveau mondial — un retour 30 ans en arrière.',
    1:'Pas de pauvreté',
    target1_1:'D`ici à 2030, éliminer complètement l`extrême pauvreté dans le monde entier (s`entend actuellement du fait de vivre avec moins de 1,90 dollar américain par jour)',
    target1_2:'D`ici à 2030, réduire de moitié au moins la proportion d`hommes, de femmes et d`enfants de tous âges souffrant d`une forme ou l`autre de pauvreté, telle que définie par chaque pays',
    target1_3:'Mettre en place des systèmes et mesures de protection sociale pour tous, adaptés au contexte national, y compris des socles de protection sociale, et faire en sorte que, d`ici à 2030, une part importante des pauvres et des personnes vulnérables en bénéficient',
    target1_4:'D`ici à 2030, faire en sorte que tous les hommes et les femmes, en particulier les pauvres et les personnes vulnérables, aient les mêmes droits aux ressources économiques et qu`ils aient accès aux services de base, à la propriété foncière, au contrôle des terres et à d`autres formes de propriété, à l`héritage, aux ressources naturelles et à des nouvelles technologies et des services financiers adaptés à leurs besoins, y compris la microfinance',
    target1_5:'D`ici à 2030, renforcer la résilience des pauvres et des personnes en situation vulnérable et réduire leur exposition aux phénomènes climatiques extrêmes et à d`autres chocs et catastrophes d`ordre économique, social ou environnemental et leur vulnérabilité',
    target1_a:'Garantir une mobilisation importante de ressources provenant de sources multiples, y compris par le renforcement de la coopération pour le développement, afin de doter les pays en développement, en particulier les pays les moins avancés, de moyens adéquats et prévisibles de mettre en œuvre des programmes et politiques visant à mettre fin à la pauvreté sous toutes ses formes',
    target1_b:'Mettre en place aux niveaux national, régional et international des cadres d`action viables, fondés sur des stratégies de développement favorables aux pauvres et soucieuses de la problématique hommes-femmes, afin d`accélérer l`investissement dans des mesures d`élimination de la pauvreté',
    desc2:'Après plusieurs décennies de baisse continue, le nombre de personnes qui souffrent de la faim – mesuré par la prévalence de la sous-alimentation – a recommencé à augmenter lentement en 2015. Les estimations actuelles montrent que près de 690 millions de personnes souffrent de la faim, soit 8,9% de la population mondiale – en hausse de 10 millions de personnes en un an et de près de 60 millions en cinq ans. Le monde n`est pas sur la bonne voie pour atteindre la Faim Zéro d`ici à 2030. Si les tendances récentes se poursuivent, le nombre de personnes touchées par la faim dépasserait 840 millions d`ici à 2030.',
    2:'Faim "zéro"',
    target2_1: 'D`ici à 2030, éliminer la faim et faire en sorte que chacun, en particulier les pauvres et les personnes en situation vulnérable, y compris les nourrissons, ait accès tout au long de l`année à une alimentation saine, nutritive et suffisante',
    target2_2:'D`ici à 2030, mettre fin à toutes les formes de malnutrition, y compris en réalisant d`ici à 2025 les objectifs arrêtés à l`échelle internationale relatifs aux retards de croissance et à l`émaciation parmi les enfants de moins de 5 ans, et répondre aux besoins nutritionnels des adolescentes, des femmes enceintes ou allaitantes et des personnes âgées',
    target2_3:'D`ici à 2030, doubler la productivité agricole et les revenus des petits producteurs alimentaires, en particulier les femmes, les autochtones, les exploitants familiaux, les éleveurs et les pêcheurs, y compris en assurant l`égalité d`accès aux terres, aux autres ressources productives et intrants, au savoir, aux services financiers, aux marchés et aux possibilités d`ajout de valeur et d`emploi autres qu`agricoles',
    target2_4:'D`ici à 2030, assurer la viabilité des systèmes de production alimentaire et mettre en œuvre des pratiques agricoles résilientes qui permettent d`accroître la productivité et la production, contribuent à la préservation des écosystèmes, renforcent les capacités d`adaptation aux changements climatiques, aux phénomènes météorologiques extrêmes, à la sécheresse, aux inondations et à d`autres catastrophes et améliorent progressivement la qualité des terres et des sols',
    target2_5:'D`ici à 2020, préserver la diversité génétique des semences, des cultures et des animaux d`élevage ou domestiqués et des espèces sauvages apparentées, y compris au moyen de banques de semences et de plantes bien gérées et diversifiées aux niveaux national, régional et international, et favoriser l`accès aux avantages que présentent l`utilisation des ressources génétiques et du savoir traditionnel associé et le partage juste et équitable de ces avantages, ainsi que cela a été décidé à l`échelle internationale',
    target2_a:'Accroître, notamment dans le cadre du renforcement de la coopération internationale, l`investissement en faveur de l`infrastructure rurale, des services de recherche et de vulgarisation agricoles et de la mise au point de technologies et de banques de gènes de plantes et d`animaux d`élevage, afin de renforcer les capacités productives agricoles des pays en développement, en particulier des pays les moins avancés',
    target2_b:'Corriger et prévenir les restrictions et distorsions commerciales sur les marchés agricoles mondiaux, y compris par l`élimination parallèle de toutes les formes de subventions aux exportations agricoles et de toutes les mesures relatives aux exportations aux effets similaires, conformément au mandat du Cycle de développement de Doha',
    target2_c:'Adopter des mesures visant à assurer le bon fonctionnement des marchés de denrées alimentaires et des produits dérivés et faciliter l`accès rapide aux informations relatives aux marchés, y compris les réserves alimentaires, afin de contribuer à limiter l`extrême volatilité du prix des denrées alimentaires',
    desc3:'Permettre à tous de vivre en bonne santé et promouvoir le bien-être de tous à tout âge sont des conditions essentielles au développement durable. Avant la pandémie, des progrès majeurs ont été accomplis pour améliorer la santé de millions de personnes. Des avancées significatives ont permis d`augmenter l`espérance de vie et de réduire certaines causes majeures de la mortalité infantile et maternelle. Davantage d`efforts sont requis pour éradiquer un large éventail de maladies et pour résoudre de nombreux enjeux sanitaires, qu`ils soient anciens ou nouveaux. En mettant l`accent sur un financement plus efficace des systèmes de santé, l`amélioration de l`assainissement et de l`hygiène et un meilleur accès aux professionnels de santé, des progrès significatifs peuvent être réalisés pour sauver des millions de vies.',
    3:'Bonne santé et bien-être',
    target3_1:'D`ici à 2030, faire passer le taux mondial de mortalité maternelle au-dessous de 70 pour 100 000 naissances vivantes',
    target3_2:'D`ici à 2030, éliminer les décès évitables de nouveau-nés et d`enfants de moins de 5 ans, tous les pays devant chercher à ramener la mortalité néonatale à 12 pour 1 000 naissances vivantes au plus et la mortalité des enfants de moins de 5 ans à 25 pour 1 000 naissances vivantes au plus',
    target3_3:'D`ici à 2030, mettre fin à l`épidémie de sida, à la tuberculose, au paludisme et aux maladies tropicales négligées et combattre l`hépatite, les maladies transmises par l`eau et autres maladies transmissibles',
    target3_4:'D`ici à 2030, réduire d`un tiers, par la prévention et le traitement, le taux de mortalité prématurée due à des maladies non transmissibles et promouvoir la santé mentale et le bien-être',
    target3_5:'Renforcer la prévention et le traitement de l`abus de substances psychoactives, notamment de stupéfiants et d`alcool',
    target3_6:'D`ici à 2020, diminuer de moitié à l`échelle mondiale le nombre de décès et de blessures dus à des accidents de la route',
    target3_7:'D`ici à 2030, assurer l`accès de tous à des services de soins de santé sexuelle et procréative, y compris à des fins de planification familiale, d`information et d`éducation, et la prise en compte de la santé procréative dans les stratégies et programmes nationaux',
    target3_8:'Faire en sorte que chacun bénéficie d`une couverture sanitaire universelle, comprenant une protection contre les risques financiers et donnant accès à des services de santé essentiels de qualité et à des médicaments et vaccins essentiels sûrs, efficaces, de qualité et d`un coût abordable',
    target3_9:'D`ici à 2030, réduire nettement le nombre de décès et de maladies dus à des substances chimiques dangereuses, à la pollution et à la contamination de l`air, de l`eau et du sol',
    target3_a:'Renforcer dans tous les pays l`application de la Convention-cadre de l`Organisation mondiale de la Santé pour la lutte antitabac',
    target3_b:'Appuyer la recherche et la mise au point de vaccins et de médicaments contre les maladies, transmissibles ou non, qui touchent principalement les habitants des pays en développement, donner accès, à un coût abordable, à des médicaments et vaccins essentiels, conformément à la Déclaration de Doha sur l`Accord sur les ADPIC et la santé publique.  Cette déclaration réaffirme le droit qu`ont les pays en développement de tirer pleinement parti des dispositions de l`Accord sur les aspects des droits de propriété intellectuelle qui touchent au commerce et à la marge de manœuvre nécessaire pour protéger la santé publique et, en particulier, assurer l`accès universel aux médicaments',
    target3_c:'Accroître considérablement le budget de la santé, le recrutement, le perfectionnement, la formation et le maintien en poste du personnel de santé dans les pays en développement, notamment dans les pays les moins avancés et les petits États insulaires en développement',
    target3_d:'Renforcer les moyens dont disposent tous les pays, en particulier les pays en développement en matière d`alerte rapide, de réduction des risques et de gestion des risques sanitaires nationaux et mondiaux',
    desc4:'',
    4:'Éducation de qualité',
    target4_1:'D`ici à 2030, faire en sorte que toutes les filles et tous les garçons suivent, sur un pied d`égalité, un cycle complet d`enseignement primaire et secondaire gratuit et de qualité, qui débouche sur un apprentissage véritablement utile',
    target4_2:'D`ici à 2030, faire en sorte que toutes les filles et tous les garçons aient accès à des activités de développement et de soins de la petite enfance et à une éducation préscolaire de qualité qui les préparent à suivre un enseignement primaire',
    target4_3:'D`ici à 2030, faire en sorte que les femmes et les hommes aient tous accès dans des conditions d`égalité à un enseignement technique, professionnel ou tertiaire, y compris universitaire, de qualité et d`un coût abordable',
    target4_4:'D`ici à 2030, augmenter considérablement le nombre de jeunes et d`adultes disposant des compétences, notamment techniques et professionnelles, nécessaires à l`emploi, à l`obtention d`un travail décent et à l`entrepreneuriat',
    target4_5:'D`ici à 2030, éliminer les inégalités entre les sexes dans le domaine de l`éducation et assurer l`égalité d`accès des personnes vulnérables, y compris les personnes handicapées, les autochtones et les enfants en situation vulnérable, à tous les niveaux d`enseignement et de formation professionnelle',
    target4_6:'D`ici à 2030, veiller à ce que tous les jeunes et une proportion considérable d`adultes, hommes et femmes, sachent lire, écrire et compter',
    target4_7:'D`ici à 2030, faire en sorte que tous les élèves acquièrent les connaissances et compétences nécessaires pour promouvoir le développement durable, notamment par l`éducation en faveur du développement et de modes de vie durables, des droits de l`homme, de l`égalité des sexes, de la promotion d`une culture de paix et de non-violence, de la citoyenneté mondiale et de l`appréciation de la diversité culturelle et de la contribution de la culture au développement durable',
    target4_a:'Faire construire des établissements scolaires qui soient adaptés aux enfants, aux personnes handicapées et aux deux sexes ou adapter les établissements existants à cette fin et fournir un cadre d`apprentissage effectif qui soit sûr, exempt de violence et accessible à tous',
    target4_b:'D`ici à 2020, augmenter considérablement à l`échelle mondiale le nombre de bourses d`études offertes aux pays en développement, en particulier aux pays les moins avancés, aux petits États insulaires en développement et aux pays d`Afrique, pour financer le suivi d`études supérieures, y compris la formation professionnelle, les cursus informatiques, techniques et scientifiques et les études d`ingénieur, dans des pays développés et d`autres pays en développement',
    target4_c:'D`ici à 2030, accroître considérablement le nombre d`enseignants qualifiés, notamment au moyen de la coopération internationale pour la formation d`enseignants dans les pays en développement, surtout dans les pays les moins avancés et les petits États insulaires en développement',
    desc5:'L`égalité des sexes n`est pas seulement un droit fondamental à la personne, elle est aussi un fondement nécessaire pour l`instauration d`un monde pacifique, prospère et durable. Des progrès ont été réalisés au cours des dernières décennies. Davantage de filles sont scolarisées, moins de filles sont contraintes de se marier précocement, davantage de femmes siègent dans les parlements et occupent des postes de direction, et les lois sont réformées afin de faire progresser l`égalité des sexes. En dépit de ces avancées, de nombreux défis subsistent : les lois et les normes sociales discriminatoires restent omniprésentes ; les femmes restent sous-représentées à tous les niveaux du pouvoir politique ; et, 20 % des femmes et des filles âgées de 15 à 49 ans ont subi des violences physiques ou sexuelles de la part d`un partenaire intime sur une période de 12 mois.',
    5:'Égalité entre les sexes',
    target5_1:'Mettre fin, dans le monde entier, à toutes les formes de discrimination à l`égard des femmes et des filles',
    target5_2:'Éliminer de la vie publique et de la vie privée toutes les formes de violence faite aux femmes et aux filles, y compris la traite et l`exploitation sexuelle et d`autres types d`exploitation',
    target5_3:'Éliminer toutes les pratiques préjudiciables, telles que le mariage des enfants, le mariage précoce ou forcé et la mutilation génitale féminine',
    target5_4:'Faire une place aux soins et travaux domestiques non rémunérés et les valoriser, par l`apport de services publics, d`infrastructures et de politiques de protection sociale et la promotion du partage des responsabilités dans le ménage et la famille, en fonction du contexte national',
    target5_5:'Garantir la participation entière et effective des femmes et leur accès en toute égalité aux fonctions de direction à tous les niveaux de décision, dans la vie politique, économique et publique',
    target5_6:'Assurer l`accès de tous aux soins de santé sexuelle et procréative et faire en sorte que chacun puisse exercer ses droits en matière de procréation, ainsi qu`il a été décidé dans le Programme d`action de la Conférence internationale sur la population et le développement et le Programme d`action de Beijing et les documents finaux des conférences d`examen qui ont suivi',
    target5_a:'Entreprendre des réformes visant à donner aux femmes les mêmes droits aux ressources économiques, ainsi qu`à l`accès à la propriété et au contrôle des terres et d`autres formes de propriété, aux services financiers, à l`héritage et aux ressources naturelles, dans le respect du droit interne',
    target5_b:'Renforcer l`utilisation des technologies clefs, en particulier l`informatique et les communications, pour promouvoir l`autonomisation des femmes',
    target5_c:'Adopter des politiques bien conçues et des dispositions législatives applicables en faveur de la promotion de l`égalité des sexes et de l`autonomisation de toutes les femmes et de toutes les filles à tous les niveaux et renforcer celles qui existent',
    desc6:'Alors que des progrès substantiels ont été accomplis pour augmenter les services d`approvisionnement en eau potable et d`assainissement, des milliards de personnes, principalement dans les zones rurales, n`ont toujours pas accès à ces services de base. Dans le monde, une personne sur trois ne bénéficie pas d`une eau potable gérée en toute sécurité, deux personnes sur cinq ne disposent pas d`une installation de base pour se laver les mains avec de l`eau et du savon, et plus de 673 millions de personnes pratiquent encore la défécation à l`air libre.',
    6:'Eau propre et assainissement',
    target6_1:'D`ici à 2030, assurer l`accès universel et équitable à l`eau potable, à un coût abordable',
    target6_2:'D`ici à 2030, assurer l`accès de tous, dans des conditions équitables, à des services d`assainissement et d`hygiène adéquats et mettre fin à la défécation en plein air, en accordant une attention particulière aux besoins des femmes et des filles et des personnes en situation vulnérable',
    target6_3:'D`ici à 2030, améliorer la qualité de l`eau en réduisant la pollution, en éliminant l`immersion de déchets et en réduisant au minimum les émissions de produits chimiques et de matières dangereuses, en diminuant de moitié la proportion d`eaux usées non traitées et en augmentant considérablement à l`échelle mondiale le recyclage et la réutilisation sans danger de l`eau',
    target6_4:'D`ici à 2030, augmenter considérablement l`utilisation rationnelle des ressources en eau dans tous les secteurs et garantir la viabilité des retraits et de l`approvisionnement en eau douce afin de tenir compte de la pénurie d`eau et de réduire nettement le nombre de personnes qui souffrent du manque d`eau',
    target6_5:'D`ici à 2030, mettre en œuvre une gestion intégrée des ressources en eau à tous les niveaux, y compris au moyen de la coopération transfrontière',
    target6_6:'D`ici à 2020, protéger et restaurer les écosystèmes liés à l`eau, notamment les montagnes, les forêts, les zones humides, les rivières, les aquifères et les lacs',
    target6_a:'D`ici à 2030, développer la coopération internationale et l`appui au renforcement des capacités des pays en développement en ce qui concerne les activités et programmes relatifs à l`eau et à l`assainissement, y compris la collecte de l`eau, la désalinisation, l`utilisation rationnelle de l`eau, le traitement des eaux usées, le recyclage et les techniques de réutilisation',
    target6_b:'Appuyer et renforcer la participation de la population locale à l`amélioration de la gestion de l`eau et de l`assainissement',
    desc7:'',
    7:'Énergie propre et d`un coût abordable',
    target7_1:'Dans le monde, des progrès ont été accomplis dans la réalisation de l`objectif 7, et des signes encourageants suggèrent que l`énergie est plus largement accessible et durable. L`accès à l`électricité dans les pays les plus pauvres est en augmentation, l`efficacité énergétique continue de s`améliorer, et l`énergie renouvelable réalise des progrès impressionnants dans le secteur de l`électricité. Cependant, des progrès soutenus sont nécessaires afin d`améliorer l`accès, pour 3 milliards de personnes, à des technologies et à des combustibles non polluants et sûrs pour cuisiner ; d`accroître l`utilisation des énergies renouvelables au-delà du secteur de l`électricité et ; de développer l`électrification en Afrique subsaharienne.',
    target7_2:'D`ici à 2030, garantir l`accès de tous à des services énergétiques fiables et modernes, à un coût abordable',
    target7_3:'D`ici à 2030, accroître nettement la part de l`énergie renouvelable dans le bouquet énergétique mondial',
    target7_a:'D`ici à 2030, renforcer la coopération internationale en vue de faciliter l`accès à la recherche et aux technologies relatives à l`énergie propre, notamment l`énergie renouvelable, l`efficacité énergétique et les nouvelles technologies relatives aux combustibles fossiles propres, et promouvoir l`investissement dans l`infrastructure énergétique et les technologies relatives à l`énergie propre',
    target7_b:'D`ici à 2030, développer les infrastructure et améliorer les technologies afin d`approvisionner en services énergétiques modernes et durables tous les habitants des pays en développement, en particulier des pays les moins avancés, des petits États insulaires en développement et des pays en développement sans littoral, dans le respect des programmes d`aide qui les concernent',
    desc8:'Une croissance économique soutenue et partagée peut entraîner des progrès, créer des emplois décents pour tous et améliorer le niveau de vie. La COVID-19 a bouleversé des milliards de vies et mis l`économie mondiale en péril. En effet, le Fonds monétaire international (FMI) prévoit une récession aussi grave ou pire encore que celle de 2009. Alors que les pertes d`emploi s`intensifient, l`Organisation internationale du Travail estime que près de la moitié de la main-d`œuvre mondiale risque de perdre ses moyens de subsistances.',
    8:'Travail dècent et croissance èconomique',
    target8_1:'Maintenir un taux de croissance économique par habitant adapté au contexte national et, en particulier, un taux de croissance annuelle du produit intérieur brut d`au moins 7 % dans les pays les moins avancés.',
    target8_2:'Parvenir à un niveau élevé de productivité économique par la diversification, la modernisation technologique et l`innovation, notamment en mettant l`accent sur les secteurs à forte valeur ajoutée et à forte intensité de main-d`œuvre.',
    target8_3:'Promouvoir des politiques axées sur le développement qui favorisent des activités productives, la création d`emplois décents, l`entrepreneuriat, la créativité et l`innovation et stimulent la croissance des microentreprises et des petites et moyennes entreprises et facilitent leur intégration dans le secteur formel, y compris par l`accès aux services financiers.',
    target8_4:'Améliorer progressivement, jusqu`en 2030, l`efficience de l`utilisation des ressources mondiales du point de vue de la consommation comme de la production et s`attacher à ce que la croissance économique n`entraîne plus la dégradation de l`environnement, comme prévu dans le cadre décennal de programmation relatif à la consommation et à la production durables, les pays développés montrant l`exemple en la matière.',
    target8_5:'D`ici à 2030, parvenir au plein emploi productif et garantir à toutes les femmes et à tous les hommes, y compris les jeunes et les personnes handicapées, un travail décent et un salaire égal pour un travail de valeur égale.',
    target8_6:'D`ici à 2020, réduire considérablement la proportion de jeunes non scolarisés et sans emploi ni formation.',
    target8_7:'Prendre des mesures immédiates et efficaces pour supprimer le travail forcé, mettre fin à l`esclavage moderne et à la traite d`êtres humains, interdire et éliminer les pires formes de travail des enfants, y compris le recrutement et l`utilisation d`enfants soldats et, d`ici à 2025, mettre fin au travail des enfants sous toutes ses formes.',
    target8_8:'Défendre les droits des travailleurs, promouvoir la sécurité sur le lieu de travail et assurer la protection de tous les travailleurs, y compris les migrants, en particulier les femmes, et ceux qui ont un emploi précaire.',
    target8_9:'D`ici à 2030, élaborer et mettre en œuvre des politiques visant à développer un tourisme durable qui crée des emplois et mette en valeur la culture et les produits locaux.',
    target8_10:'Renforcer la capacité des institutions financières nationales de favoriser et généraliser l`accès de tous aux services bancaires et financiers et aux services d`assurance',
    target8_a:'Accroître l`appui apporté dans le cadre de l`initiative Aide pour le commerce aux pays en développement, en particulier aux pays les moins avancés, y compris par l`intermédiaire du cadre intégré renforcé pour l`assistance technique liée au commerce en faveur des pays les moins avancés.',
    target8_b:'D`ici à 2020, élaborer et mettre en œuvre une stratégie mondiale en faveur de l`emploi des jeunes et appliquer le Pacte mondial pour l`emploi de l`Organisation internationale du Travail.',
    desc9:'Une industrialisation durable qui profite à tous, allant de pair avec des innovations et des infrastructures, peut libérer des forces économiques dynamiques et compétitives qui génèrent des emplois et des revenus. Ces facteurs ont un rôle crucial dans l`introduction et la promotion de nouvelles technologies, le développement du commerce international et l`utilisation efficace des matières premières. Cependant, il reste encore beaucoup à faire au niveau mondial pour exploiter pleinement ce potentiel. Les pays les moins avancés, en particulier, doivent intensifier le développement de leur secteur manufacturier s`ils veulent atteindre cet objectif d`ici à 2030, et doivent augmenter leurs investissements dans la recherche scientifique et l`innovation.',
    9:'Industrie, innovation et infrastructures',
    target9_1:'Mettre en place une infrastructure de qualité, fiable, durable et résiliente, y compris une infrastructure régionale et transfrontière, pour favoriser le développement économique et le bien-être de l`être humain, en mettant l`accent sur un accès universel, à un coût abordable et dans des conditions d`équité.',
    target9_2:'Promouvoir une industrialisation durable qui profite à tous et, d`ici à 2030, augmenter nettement la contribution de l`industrie à l`emploi et au produit intérieur brut, en fonction du contexte national, et la multiplier par deux dans les pays les moins avancés.',
    target9_3:'Accroître, en particulier dans les pays en développement, l`accès des entreprises, notamment des petites entreprises industrielles, aux services financiers, y compris aux prêts consentis à des conditions abordables, et leur intégration dans les chaînes de valeur et sur les marchés.',
    target9_4:'D`ici à 2030, moderniser l`infrastructure et adapter les industries afin de les rendre durables, par une utilisation plus rationnelle des ressources et un recours accru aux technologies et procédés industriels propres et respectueux de l`environnement, chaque pays agissant dans la mesure de ses moyens.',
    target9_5:'Renforcer la recherche scientifique, perfectionner les capacités technologiques des secteurs industriels de tous les pays, en particulier des pays en développement, notamment en encourageant l`innovation et en augmentant considérablement le nombre de personnes travaillant dans le secteur de la recherche et du développement pour 1 million d`habitants et en accroissant les dépenses publiques et privées consacrées à la recherche et au développement d`ici à 2030.',
    target9_a:'Faciliter la mise en place d`une infrastructure durable et résiliente dans les pays en développement en renforçant l`appui financier, technologique et technique apporté aux pays d`Afrique, aux pays les moins avancés, aux pays en développement sans littoral et aux petits États insulaires en développement.',
    target9_b:'Soutenir la recherche, le développement et l`innovation technologique au niveau national dans les pays en développement, notamment en instaurant des conditions propices telles que la diversification industrielle et l`ajout de valeur aux marchandises.',
    target9_c:'Accroître nettement l`accès aux technologies de l`information et de la communication et faire en sorte que tous les habitants des pays les moins avancés aient accès à Internet à un coût abordable d`ici à 2020.',
    desc10:'Réduire les inégalités et ne pas faire de laissés-pour-compte font partie intégrante des efforts visant à atteindre les objectifs de développement durable. Or, les inégalités dans les pays et d`un pays à l`autre restent préoccupantes. Malgré quelques signes positifs en faveur de la réduction des inégalités dans certains domaines, tels que la réduction des inégalités de revenus dans certains pays et l`octroi d`un statut commercial préférentiel dont bénéficient les pays à faible revenu, les inégalités persistent.',
    10:'Inégalités réduites',
    target10_1:'D`ici à 2030, faire en sorte, au moyen d`améliorations progressives, que les revenus des 40 pour cent les plus pauvres de la population augmentent plus rapidement que le revenu moyen national, et ce de manière durable',
    target10_2:'D`ici à 2030, autonomiser toutes les personnes et favoriser leur intégration sociale, économique et politique, indépendamment de leur âge, de leur sexe, de leur handicap, de leur race, de leur appartenance ethnique, de leurs origines, de leur religion ou de leur statut économique ou autre',
    target10_3:'Assurer l`égalité des chances et réduire l`inégalité des résultats, notamment en éliminant les lois, politiques et pratiques discriminatoires et en promouvant l`adoption de lois, politiques et mesures adéquates en la matière',
    target10_4:'Adopter des politiques, notamment sur les plans budgétaire, salarial et dans le domaine de la protection sociale, et parvenir progressivement à une plus grande égalité',
    target10_5:'Améliorer la réglementation et la surveillance des institutions et marchés financiers mondiaux et renforcer l`application des règles',
    target10_6:'Faire en sorte que les pays en développement soient davantage représentés et entendus lors de la prise de décisions dans les institutions économiques et financières internationales, afin que celles-ci soient plus efficaces, crédibles, transparentes et légitimes',
    target10_7:'Faciliter la migration et la mobilité de façon ordonnée, sans danger, régulière et responsable, notamment par la mise en œuvre de politiques de migration planifiées et bien gérées',
    target10_a:'Mettre en œuvre le principe d`un traitement spécial et différencié pour les pays en développement, en particulier les pays les moins avancés, conformément aux accords de l`Organisation mondiale du commerce',
    target10_b:'Stimuler l`aide publique au développement et les flux financiers, y compris les investissements étrangers directs, pour les États qui en ont le plus besoin, en particulier les pays les moins avancés, les pays d`Afrique, les petits États insulaires en développement et les pays en développement sans littoral, conformément à leurs plans et programmes nationaux',
    target10_c:'D`ici à 2030, faire baisser au-dessous de 3 pour cent les coûts de transaction des envois de fonds effectués par les migrants et éliminer les couloirs de transfert de fonds dont les coûts sont supérieurs à 5 pour cent',
    desc11:'Le monde est de plus en plus urbanisé. Depuis 2007, plus de la moitié de la population mondiale vit dans des villes, et cette proportion devrait augmenter à 60 % d`ici à 2030. Les villes et les zones métropolitaines sont des pôles de la croissance économique, contribuant à près de 60 % du produit intérieur brut mondial. Cependant, elles représentent aussi près de 70 % des émissions de carbone dans le monde et plus de 60 % des ressources utilisées. L`urbanisation rapide se traduit par un nombre croissant de personnes vivant dans des taudis, ainsi que par des infrastructures et des services inadéquats et surchargés (tels que la collecte des déchets et les systèmes d`approvisionnement en eau et d`assainissement, les routes et le transport), aggravant la pollution atmosphérique et l`expansion urbaine non planifiée.',
    11:'Villes et communautés durables',
    target11_1:'D`ici à 2030, assurer l`accès de tous à un logement et des services de base adéquats et sûrs, à un coût abordable, et assainir les quartiers de taudis.',
    target11_2:'D`ici à 2030, assurer l`accès de tous à des systèmes de transport sûrs, accessibles et viables, à un coût abordable, en améliorant la sécurité routière, notamment en développant les transports publics, une attention particulière devant être accordée aux besoins des personnes en situation vulnérable, des femmes, des enfants, des personnes handicapées et des personnes âgées.',
    target11_3:'D`ici à 2030, renforcer l`urbanisation inclusive et durable pour tous et les capacités de planification et de gestion participatives, intégrées et durables des établissements humains dans tous les pays.',
    target11_4:'Renforcer les efforts de protection et de préservation du patrimoine culturel et naturel mondial.',
    target11_5:'D`ici à 2030, réduire considérablement le nombre de personnes tuées et le nombre de personnes touchées par les catastrophes, y compris celles d`origine hydrique, et réduire considérablement le montant des pertes économiques qui sont dues directement à ces catastrophes exprimé en proportion du produit intérieur brut mondial, l`accent étant mis sur la protection des pauvres et des personnes en situation vulnérable.',
    target11_6:'D`ici à 2030, réduire l`impact environnemental négatif des villes par habitant, en accordant une attention particulière à la qualité de l`air et à la gestion, notamment municipale, des déchets.',
    target11_7:'D`ici à 2030, assurer l`accès de tous, en particulier des femmes et des enfants, des personnes âgées et des personnes handicapées, à des espaces verts et des espaces publics sûrs.',
    target11_a:'Favoriser l`établissement de liens économiques, sociaux et environnementaux positifs entre zones urbaines, périurbaines et rurales en renforçant la planification du développement à l`échelle nationale et régionale.',
    target11_b:'D`ici 2020, accroître considérablement le nombre de villes et d`établissements humains qui adoptent et mettent en œuvre des politiques et plans d`action intégrés en faveur de l`insertion de tous, de l`utilisation rationnelle des ressources, de l`adaptation aux effets des changements climatiques et de leur atténuation et de la résilience face aux catastrophes, et élaborer et mettre en œuvre, conformément au Cadre de Sendai pour la réduction des risques de catastrophe (2015-2030), une gestion globale des risques de catastrophe à tous les niveaux.',
    target11_c:'Aider les pays les moins avancés, y compris par une assistance financière et technique, à construire des bâtiments durables et résilients en utilisant des matériaux locaux.',
    desc12:'La consommation et la production mondiales — véritables moteurs de l`économie mondiale — reposent sur une utilisation de l`environnement et des ressources naturelles d`une manière qui continue à avoir des effets destructeurs sur la planète. Les progrès économiques et sociaux accomplis au siècle précédent ont provoqué une dégradation de l`environnement qui menace les systèmes dont nous dépendons pour notre futur développement, notre propre survie.',
    12:'Consommation et production durables',
    target12_1:'Mettre en œuvre le Cadre décennal de programmation concernant les modes de consommation et de production durables avec la participation de tous les pays, les pays développés montrant l`exemple en la matière, compte tenu du degré de développement et des capacités des pays en développement',
    target12_2:'D`ici à 2030, parvenir à une gestion durable et à une utilisation rationnelle des ressources naturelles',
    target12_3:'D`ici à 2030, réduire de moitié à l`échelle mondiale le volume de déchets alimentaires par habitant au niveau de la distribution comme de la consommation et réduire les pertes de produits alimentaires tout au long des chaînes de production et d`approvisionnement, y compris les pertes après récolte',
    target12_4:'D`ici à 2020, instaurer une gestion écologiquement rationnelle des produits chimiques et de tous les déchets tout au long de leur cycle de vie, conformément aux principes directeurs arrêtés à l`échelle internationale, et réduire considérablement leur déversement dans l`air, l`eau et le sol, afin de minimiser leurs effets négatifs sur la santé et l`environnement',
    target12_5:'D`ici à 2030, réduire considérablement la production de déchets par la prévention, la réduction, le recyclage et la réutilisation',
    target12_6:'Encourager les entreprises, en particulier les grandes et les transnationales, à adopter des pratiques viables et à intégrer dans les rapports qu`elles établissent des informations sur la viabilité',
    target12_7:'Promouvoir des pratiques durables dans le cadre de la passation des marchés publics, conformément aux politiques et priorités nationales',
    target12_8:'D`ici à 2030, faire en sorte que toutes les personnes, partout dans le monde, aient les informations et connaissances nécessaires au développement durable et à un style de vie en harmonie avec la nature',
    target12_a:'Aider les pays en développement à se doter des moyens scientifiques et technologiques qui leur permettent de s`orienter vers des modes de consommation et de production plus durables',
    target12_b:'Mettre au point et utiliser des outils de contrôle des impacts sur le développement durable, pour un tourisme durable qui crée des emplois et met en valeur la culture et les produits locaux',
    target12_c:'Rationaliser les subventions aux combustibles fossiles qui sont source de gaspillage, en éliminant les distorsions du marché, selon le contexte national, y compris par la restructuration de la fiscalité et l`élimination progressive des subventions nuisibles, afin de mettre en évidence leur impact sur l`environnement, en tenant pleinement compte des besoins et de la situation propres aux pays en développement et en réduisant au minimum les éventuels effets pernicieux sur le développement de ces pays tout en protégeant les pauvres et les collectivités concernées',
    desc13:'L`année 2019 a été la deuxième année la plus chaude de l`histoire et marque la fin d`une décennie (2010- 2019) de chaleur exceptionnelle. Les niveaux de dioxyde de carbone (CO2) et d`autres gaz à effet de serre enregistrés dans l`atmosphère ont atteint de nouveaux records en 2019. Les changements climatiques affectent désormais tous les pays sur tous les continents. Ils perturbent les économies nationales et affectent des vies, tandis que les conditions météorologiques changent, le niveau de la mer monte et que les phénomènes météorologiques deviennent plus extrêmes. Bien que les émissions de gaz à effet de serre devraient diminuer d`environ 6 % en 2020 en raison des restrictions de déplacement et du ralentissement des activités économiques liés à la pandémie de COVID-19, cette amélioration n`est que temporaire. Les changements climatiques ne connaissent aucun répit. Une fois que l`économie mondiale commencera à se remettre de la pandémie, les émissions devraient revenir à des niveaux plus élevés.',
    13:'Lutte contre les changements climatiques',
    target13_1:'Renforcer, dans tous les pays, la résilience et les capacités d`adaptation face aux aléas climatiques et aux catastrophes naturelles liées au climat',
    target13_2:'Incorporer des mesures relatives aux changements climatiques dans les politiques, les stratégies et la planification nationales',
    target13_3:'Améliorer l`éducation, la sensibilisation et les capacités individuelles et institutionnelles en ce qui concerne l`adaptation aux changements climatiques, l`atténuation de leurs effets et la réduction de leur impact et les systèmes d`alerte rapide',
    target13_a:'Mettre en œuvre l`engagement que les pays développés parties à la Convention-cadre des Nations Unies sur les changements climatiques ont pris de mobiliser ensemble auprès de multiples sources 100 milliards de dollars des États-Unis par an d`ici à 2020 pour répondre aux besoins des pays en développement en ce qui concerne les mesures concrètes d`atténuation et la transparence de leur mise en œuvre et rendre le Fonds vert pour le climat pleinement opérationnel en le dotant dans les plus brefs délais des moyens financiers nécessaires',
    target13_b:'Promouvoir des mécanismes de renforcement des capacités afin que les pays les moins avancés et les petits États insulaires en développement se dotent de moyens efficaces de planification et de gestion pour faire face aux changements climatiques, l`accent étant mis notamment sur les femmes, les jeunes, la population locale et les groupes marginalisés',
    desc14:'L`océan est à la base des phénomènes mondiaux qui rendent notre planète habitable pour l`humanité. L`eau de pluie, l`eau potable, les conditions météorologiques, le climat, les côtes, une grande partie de nos aliments et même l`oxygène de l`air que nous respirons, tous sont fournis et régulés par les océans. La gestion prudente de cette ressource vitale mondiale est un élément clé pour un avenir durable. Cependant, à l`heure actuelle, les eaux côtières se détériorent continuellement à cause de la pollution, et l`acidification des océans a un effet de confrontation sur le fonctionnement des écosystèmes et de la biodiversité. Cela a également un impact négatif sur la pêche artisanale.',
    14:'Vie aquatique',
    target14_1:'D`ici à 2025, prévenir et réduire nettement la pollution marine de tous types, en particulier celle résultant des activités terrestres, y compris les déchets en mer et la pollution par les nutriments',
    target14_2:'D`ici à 2020, gérer et protéger durablement les écosystèmes marins et côtiers, notamment en renforçant leur résilience, afin d`éviter les graves conséquences de leur dégradation et prendre des mesures en faveur de leur restauration pour rétablir la santé et la productivité des océans',
    target14_3:'Réduire au maximum l`acidification des océans et lutter contre ses effets, notamment en renforçant la coopération scientifique à tous les niveaux',
    target14_4:'D`ici à 2020, réglementer efficacement la pêche, mettre un terme à la surpêche, à la pêche illicite, non déclarée et non réglementée et aux pratiques de pêche destructrices et exécuter des plans de gestion fondés sur des données scientifiques, l`objectif étant de rétablir les stocks de poissons le plus rapidement possible, au moins à des niveaux permettant d`obtenir un rendement constant maximal compte tenu des caractéristiques biologiques',
    target14_5:'D`ici à 2020, préserver au moins 10 % des zones marines et côtières, conformément au droit national et international et compte tenu des meilleures informations scientifiques disponibles',
    target14_6:'D`ici à 2020, interdire les subventions à la pêche qui contribuent à la surcapacité et à la surpêche, supprimer celles qui favorisent la pêche illicite, non déclarée et non réglementée et s`abstenir d`en accorder de nouvelles, sachant que l`octroi d`un traitement spécial et différencié efficace et approprié aux pays en développement et aux pays les moins avancés doit faire partie intégrante des négociations sur les subventions à la pêche menées dans le cadre de l`Organisation mondiale du commerce',
    target14_7:'D`ici à 2030, faire mieux bénéficier les petits États insulaires en développement et les pays les moins avancés des retombées économiques de l`exploitation durable des ressources marines, notamment grâce à une gestion durable des pêches, de l`aquaculture et du tourisme',
    target14_a:'Approfondir les connaissances scientifiques, renforcer les capacités de recherche et transférer les techniques marines, conformément aux Critères et principes directeurs de la Commission océanographique intergouvernementale concernant le transfert de techniques marines, l`objectif étant d`améliorer la santé des océans et de renforcer la contribution de la biodiversité marine au développement des pays en développement, en particulier des petits États insulaires en développement et des pays les moins avancés',
    target14_b:'Garantir aux petits pêcheurs l`accès aux ressources marines et aux marchés',
    target14_c:'Améliorer la conservation des océans et de leurs ressources et les exploiter de manière plus durable en application des dispositions du droit international, énoncées dans la Convention des Nations Unies sur le droit de la mer, qui fournit le cadre juridique requis pour la conservation et l`exploitation durable des océans et de leurs ressources, comme il est rappelé au paragraphe 158 de « L`avenir que nous voulons »',
    desc15:'La nature est indispensable à notre survie : elle nous fournit de l`oxygène, régule nos conditions météorologiques, pollinise nos cultures, produit de quoi nous nourrir et nous vêtir. Pourtant, la nature est soumise à une pression croissante. Au total, 75 % de la surface terrestre a été altérée par l`activité humaine, obligeant la faune et la flore à se replier dans des espaces de plus en plus restreints. Environ 1 million d`espèces animales et végétales sont déjà menacées d`extinction, beaucoup dans les décennies à venir, indique le Rapport 2019 de l`évaluation mondiale de la biodiversité et des services écosystémiques. Le rapport appelle à des changements transformateurs afin de restaurer et de protéger la nature. Il constate que la santé des écosystèmes, dont l`humanité tout entière ainsi que toutes les autres espèces dépendent, se détériore plus rapidement que jamais, affectant les fondements mêmes de nos économies, nos moyens de subsistance, notre sécurité alimentaire, notre santé et notre qualité de vie dans le monde entier.',
    15:'Vie terrestre',
    target15_1:'D`ici à 2020, garantir la préservation, la restauration et l`exploitation durable des écosystèmes terrestres et des écosystèmes d`eau douce et des services connexes, en particulier les forêts, les zones humides, les montagnes et les zones arides, conformément aux obligations découlant des accords internationaux',
    target15_2:'D`ici à 2020, promouvoir la gestion durable de tous les types de forêt, mettre un terme à la déforestation, restaurer les forêts dégradées et accroître considérablement le boisement et le reboisement au niveau mondial',
    target15_3:'D`ici à 2030, lutter contre la désertification, restaurer les terres et sols dégradés, notamment les terres touchées par la désertification, la sécheresse et les inondations, et s`efforcer de parvenir à un monde neutre en matière de dégradation des terres.',
    target15_4:'D`ici à 2030, assurer la préservation des écosystèmes montagneux, notamment de leur biodiversité, afin de mieux tirer parti de leurs bienfaits essentiels pour le développement durable',
    target15_5:'Prendre d`urgence des mesures énergiques pour réduire la dégradation du milieu naturel, mettre un terme à l`appauvrissement de la biodiversité et, d`ici à 2020, protéger les espèces menacées et prévenir leur extinction',
    target15_6:'Favoriser le partage juste et équitable des bénéfices découlant de l`utilisation des ressources génétiques et promouvoir un accès approprié à celles-ci, ainsi que cela a été décidé à l`échelle internationale',
    target15_7:'Prendre d`urgence des mesures pour mettre un terme au braconnage et au trafic d`espèces végétales et animales protégées et s`attaquer au problème sous l`angle de l`offre et de la demande',
    target15_8:'D`ici à 2020, prendre des mesures pour empêcher l`introduction d`espèces exotiques envahissantes, atténuer sensiblement les effets que ces espèces ont sur les écosystèmes terrestres et aquatiques et contrôler ou éradiquer les espèces prioritaires',
    target15_9:'D`ici à 2020, intégrer la protection des écosystèmes et de la biodiversité dans la planification nationale, dans les mécanismes de développement, dans les stratégies de réduction de la pauvreté et dans la comptabilité',
    target15_a:'Mobiliser des ressources financières de toutes provenances et les augmenter nettement pour préserver la biodiversité et les écosystèmes et les exploiter durablement',
    target15_b:'Mobiliser d`importantes ressources de toutes provenances et à tous les niveaux pour financer la gestion durable des forêts et inciter les pays en développement à privilégier ce type de gestion, notamment aux fins de la préservation des forêts et du reboisement',
    target15_c:'Apporter, à l`échelon mondial, un soutien accru à l`action menée pour lutter contre le braconnage et le trafic d`espèces protégées, notamment en donnant aux populations locales d`autres moyens d`assurer durablement leur subsistance',
    desc16:'Les conflits, l`insécurité, les institutions faibles et l`accès limité à la justice portent atteinte au développement durable. En 2018, plus de 70 millions de personnes ont fui la guerre, les persécutions et les conflits ; ce nombre de réfugiés est le plus élevé depuis la création, il y a 70 ans, du Haut-Commissariat des Nations Unies pour les réfugiés. En 2019, l`ONU a enregistré 357 assassinats et 30 disparitions forcées concernant des défenseurs des droits de l`homme, des journalistes et des syndicalistes dans 47 pays. Par ailleurs, à l`échelle mondiale, un quart des enfants de moins de cinq ans n`ont jamais été enregistrés à la naissance ; ils ne disposent d`aucune preuve d`identité juridique leur permettant de protéger leurs droits et de garantir l`accès universel aux services sociaux.',
    16:'Paix, justice et institutions efficaces',
    target16_1:'Réduire nettement, partout dans le monde, toutes les formes de violence et les taux de mortalité qui y sont associés',
    target16_2:'Mettre un terme à la maltraitance, à l`exploitation et à la traite, et à toutes les formes de violence et de torture dont sont victimes les enfants',
    target16_3:'Promouvoir l`état de droit aux niveaux national et international et donner à tous accès à la justice dans des conditions d`égalité',
    target16_4:'D`ici à 2030, réduire nettement les flux financiers illicites et le trafic d`armes, renforcer les activités de récupération et de restitution des biens volés et lutter contre toutes les formes de criminalité organisée',
    target16_5:'Réduire nettement la corruption et la pratique des pots-de-vin sous toutes leurs formes',
    target16_6:'Mettre en place des institutions efficaces, responsables et transparentes à tous les niveaux',
    target16_7:'Faire en sorte que le dynamisme, l`ouverture, la participation et la représentation à tous les niveaux caractérisent la prise de décisions',
    target16_8:'Élargir et renforcer la participation des pays en développement aux institutions chargées de la gouvernance au niveau mondial',
    target16_9:'D`ici à 2030, garantir à tous une identité juridique, notamment grâce à l`enregistrement des naissances',
    target16_10:'Garantir l`accès public à l`information et protéger les libertés fondamentales, conformément à la législation nationale et aux accords internationaux',
    target16_a:'Appuyer, notamment dans le cadre de la coopération internationale, les institutions nationales chargées de renforcer, à tous les niveaux, les moyens de prévenir la violence et de lutter contre le terrorisme et la criminalité, en particulier dans les pays en développement',
    target16_b:'Promouvoir et appliquer des lois et politiques non discriminatoires pour le développement durable',
    desc17:'La grande ambition des ODD s`articule autour d`une coopération et de partenariats mondiaux solides. Des partenariats inclusifs sont nécessaires pour un programme de développement durable réussi. Ces partenariats construits sur des principes et des valeurs, une vision commune et des objectifs communs qui placent les peuples et la planète au centre, sont nécessaires au niveau mondial, régional, national et local. De nombreux pays ont besoin de l`aide publique au développement pour soutenir leur croissance et leur commerce. Pourtant, les flux d`aide sont en baisse et de nombreux pays donateurs ne respectent pas leurs engagements en matière de financement du développement.',
    17:'Partenariats pour la réalisation des objectifs',
    target17_1:'Améliorer, notamment grâce à l`aide internationale aux pays en développement, la mobilisation de ressources nationales en vue de renforcer les capacités nationales de collecte de l`impôt et d`autres recettes',
    target17_2:' Faire en sorte que les pays développés honorent tous leurs engagements en matière d`aide publique au développement, notamment celui pris par nombre d`entre eux de consacrer 0,7% de leur revenu national brut à l`aide aux pays en développement et entre 0,15% et 0,20% à l`aide aux pays les moins avancés, les bailleurs de fonds étant encouragés à envisager de se fixer pour objectif de consacrer au moins 0,20% de leur revenu national brut à l`aide aux pays les moins avancés',
    target17_3:'Mobiliser des ressources financières supplémentaires de diverses provenances en faveur des pays en développement',
    target17_4:'Aider les pays en développement à assurer la viabilité à long terme de leur dette au moyen de politiques concertées visant à favoriser le financement de la dette, son allègement ou sa restructuration, selon le cas, et réduire le surendettement en réglant le problème de la dette extérieure des pays pauvres très endettés',
    target17_5:'Adopter et mettre en œuvre des dispositifs visant à encourager l`investissement en faveur des pays les moins avancés',
    target17_6:'Renforcer l`accès à la science, à la technologie et à l`innovation et la coopération Nord-Sud et Sud-Sud et la coopération triangulaire régionale et internationale dans ces domaines et améliorer le partage des savoirs selon des modalités arrêtées d`un commun accord, notamment en coordonnant mieux les mécanismes existants, en particulier au niveau des organismes des Nations unies, et dans le cadre d`un mécanisme mondial de facilitation des technologies',
    target17_7:'Promouvoir la mise au point, le transfert et la diffusion de technologies respectueuses de l`environnement en faveur des pays en développement, à des conditions favorables, y compris privilégiées et préférentielles, arrêtées d`un commun accord',
    target17_8:'Faire en sorte que la banque de technologies et le mécanisme de renforcement des capacités scientifiques et technologiques et des capacités d`innovation des pays les moins avancés soient pleinement opérationnels d`ici à 2017 et renforcer l`utilisation des technologies clefs, en particulier de l`informatique et des communications',
    target17_9:'Apporter, à l`échelon international, un soutien accru pour assurer le renforcement efficace et ciblé des capacités des pays en développement et appuyer ainsi les plans nationaux visant à atteindre tous les objectifs de développement durable, notamment dans le cadre de la coopération Nord-Sud et Sud-Sud et de la coopération triangulaire',
    target17_10:'Promouvoir un système commercial multilatéral universel, réglementé, ouvert, non discriminatoire et équitable sous l`égide de l`Organisation mondiale du commerce, notamment grâce à la tenue de négociations dans le cadre du Programme de Doha pour le développement',
    target17_11:'Accroître nettement les exportations des pays en développement, en particulier en vue de doubler la part des pays les moins avancés dans les exportations mondiales d`ici à 2020',
    target17_12:'Permettre l`accès rapide de tous les pays les moins avancés aux marchés en franchise de droits et sans contingent, conformément aux décisions de l`Organisation mondiale du commerce, notamment en veillant à ce que les règles préférentielles applicables aux importations provenant des pays les moins avancés soient transparentes et simples et facilitent l`accès aux marchés',
    target17_13:'Renforcer la stabilité macroéconomique mondiale, notamment en favorisant la coordination et la cohérence des politiques',
    target17_14:'Renforcer la cohérence des politiques de développement durable',
    target17_15:'Respecter la marge de manœuvre et l`autorité de chaque pays en ce qui concerne l`élaboration et l`application des politiques d`élimination de la pauvreté et de développement durable',
    target17_16:'Renforcer le Partenariat mondial pour le développement durable, associé à des partenariats multipartites permettant de mobiliser et de partager des savoirs, des connaissances spécialisées, des technologies et des ressources financières, afin d`aider tous les pays, en particulier les pays en développement, à atteindre les objectifs de développement durable',
    target17_17:'Encourager et promouvoir les partenariats publics, les partenariats public-privé et les partenariats avec la société civile, en faisant fond sur l`expérience acquise et les stratégies de financement appliquées en la matière',
    target17_18:'D`ici à 2020, apporter un soutien accru au renforcement des capacités des pays en développement, notamment des pays les moins avancés et des petits États insulaires en développement, l`objectif étant de disposer d`un beaucoup plus grand nombre de données de qualité, actualisées et exactes, ventilées par niveau de revenu, sexe, âge, race, appartenance ethnique, statut migratoire, handicap et emplacement géographique, et selon d`autres caractéristiques propres à chaque pays',
    target17_19:'D`ici à 2030, tirer parti des initiatives existantes pour établir des indicateurs de progrès en matière de développement durable qui viendraient compléter le produit intérieur brut, et appuyer le renforcement des capacités statistiques des pays en développement',
    // Temporary:
    // Development areas
    Arbeid_sysselsettning:'Travail et emploi',
    Bebyggelse:'Immeubles',
    Digitalisering1:'Digitalisation',
    Energi:'Énergie',
    Helse_sosial_og_velferd:'Santé, social et bien-être',
    Kultur:'Culture',
    Natur_og_miljø:'Nature et environnement',
    Næring:'Industrie',
    Oppvekst_og_utdanning:'Enfance et éducation',
    Styring_og_demokrati:'Gouvernance et démocratie',
    Transport:'Le transport',
    Trygghet_og_beredskap:'Sécurité et préparation',
    Vann_og_søppel:'Eau et déchets',
    Økonomisk:'Économique',
    // TBL:
    Miljø:'Environnement',
    Sosialt:'Socialement',
    Økonomi:'Économie',
    // Perspectives in Trdheim
    Arealer_og_ressursforvaltning:'Zones et gestion des ressources',
    Det_grønne_skiftet:'Le virage vert',
    Digitalisering2:'Digitalisation',
    Forbruk:'Consommation',
    Grønn_mobilitet:'Mobilité verte',
    Indentitet_og_kultur:'Identité et culture',
    Inkluderende_samfunn:'Société inclusive',
    Lokaldemokratiet: 'Démocratie locale',
    Nærmiljø_og_stedsutvikling:'Environnement local et développement',
    Oppvekst_og_læring:'Enfance et apprentissage',
    P1:'P1',
    Samarbeid_og_verdiskapning:'Coopération et création de valeur',
    Samskapt_velferd:'Bien-être co-créé',
    Økonomi1:'Économie',
    // Icons:
    icon_1:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf4484c1418719ce8ca501/previews/5daf4485c1418719ce8ca513/download/F-WEB-Goal-01.png',
    icon_2:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448569d4507a4f8c947e/previews/5daf448669d4507a4f8c94bc/download/F-WEB-Goal-02.png',
    icon_3:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448696863841204c86c4/previews/5daf448796863841204c86cd/download/F-WEB-Goal-03.png',
    icon_4:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf44879b9be84afe422575/previews/5daf44889b9be84afe422599/download/F-WEB-Goal-04.png',
    icon_5:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf4488dc980764789b36f4/previews/5daf448adc980764789b37b9/download/F-WEB-Goal-05.png',
    icon_6:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448a8673f480d02f8d28/previews/5daf448b8673f480d02f8d38/download/F-WEB-Goal-06.png',
    icon_7:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448bf9cdde61808bcbd8/previews/5daf448cf9cdde61808bcc74/download/F-WEB-Goal-07.png',
    icon_8:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448c911d4f71428469f6/previews/5daf448d911d4f7142846a06/download/F-WEB-Goal-08.png',
    icon_9:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448d3c139b7aa9f119d6/previews/5daf448e3c139b7aa9f119f2/download/F-WEB-Goal-09.png',
    icon_10:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448e902ed347e0d2e6a6/previews/5daf448f902ed347e0d2e6cc/download/F-WEB-Goal-10.png',
    icon_11:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf448f28433142428842e6/previews/5daf449028433142428842f0/download/F-WEB-Goal-11.png',
    icon_12:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf44904f2ec66be05ccb6c/previews/5daf44914f2ec66be05ccb82/download/F-WEB-Goal-12.png',
    icon_13:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf4491402d576bfe28d69f/previews/5daf4492402d576bfe28d6bd/download/F-WEB-Goal-13.png',
    icon_14:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf44923e66370c28bbf0e2/previews/5daf44933e66370c28bbf182/download/F-WEB-Goal-14.png',
    icon_15:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf44949a687624543b64a1/previews/5daf44959a687624543b64b3/download/F-WEB-Goal-15.png',
    icon_16:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf4495344d4052e88a7e1d/previews/5daf4496344d4052e88a7ef4/download/F-WEB-Goal-16.png',
    icon_17:'https://trello.com/1/cards/5aeb6826e93e1ec7d0a5d92f/attachments/5daf4496f579d97e65f7ed86/previews/5daf4497f579d97e65f7edb0/download/F-WEB-Goal-17.png',
};