export default {
    bulgarian: 'bulgare',
    croatian: 'croate',
    czech: 'tchèque', 
    danish: 'danois', 
    dutch: 'néerlandais',
    english: 'anglais',
    estonian: 'estonien',
    finnish: 'finnois',
    french: 'français',
    german: 'allemand', 
    greek: 'grec',
    hungarian: 'hongrois',
    irish: 'irlandais', 
    italian: 'italien',
    latvian: 'letton',
    lithuanian: 'lituanien',
    maltese: 'maltais',
    norwegian: 'norvégien',
    polish: 'polonais',
    portuguese: 'portugais',
    romanian:'roumain',
    slovak: 'slovaque',
    slovenian: 'slovène',
    spanish: 'espagnol',
    swedish: 'suédois'
}