export default {
    bg: 'bulgáiris',
    hr: 'cróitis',
    cs: 'tchèque', 
    da: 'danmhairgis', 
    nl: 'ollainnis',
    en: 'béarla',
    et: 'eastóinis',
    fi: 'fionlainnis',
    fr: 'fraincis',
    de: 'gearmáinis', 
    el: 'gréigis',
    hu: 'ungáiris',
    ga: 'gaeilge', 
    it: 'iodáilis',
    lv: 'laitvis',
    lt: 'liotuáinis',
    mt: 'máltais',
    no: 'ioruais',
    pl: 'polainnis',
    pt: 'portaingéilis',
    ro:'rómáinis',
    sk: 'slóvaicis',
    sl: 'slóivéinis',
    es: 'spáinnis',
    sv: 'sualainnis'
}