export default {
    bg: 'bugarski',
    hr: 'hrvatski',
    cs: 'češki', 
    da: 'danski', 
    nl: 'nizozemski',
    en: 'engleski',
    et: 'estonski',
    fi: 'finski',
    fr: 'francuski',
    de: 'njemački', 
    el: 'grčki',
    hu: 'mađarski',
    ga: 'irski', 
    it: 'talijanski',
    lv: 'latvijski',
    lt: 'litavski',
    mt: 'malteški',
    no: 'norveški',
    pl: 'poljski',
    pt: 'portugalski',
    ro:'rumunjski',
    sk: 'slovački',
    sl: 'slovenski',
    es: 'španjolski',
    sv: 'švedski'
}