export default {
    bg: 'bolgár',
    hr: 'horvát',
    cs: 'cseh', 
    da: 'dán', 
    nl: 'holland',
    en: 'angol',
    et: 'észt',
    fi: 'finn',
    fr: 'francia',
    de: 'német', 
    el: 'görög',
    hu: 'magyar',
    ga: 'ír', 
    it: 'olasz',
    lv: 'lett',
    lt: 'litván',
    mt: 'máltai',
    no: 'norvég',
    pl: 'lengyel',
    pt: 'portugál',
    ro:'román',
    sk: 'szlovák',
    sl: 'szlovén',
    es: 'spanyol',
    sv: 'svéd'
}