export default {
    bg: 'bulgaro',
    hr: 'croato',
    cs: 'ceco', 
    da: 'danese', 
    nl: 'neerlandese',
    en: 'inglese',
    et: 'estone',
    fi: 'finlandese',
    fr: 'francese',
    de: 'tedesco', 
    el: 'greco',
    hu: 'ungherese',
    ga: 'irlandese', 
    it: 'italiano',
    lv: 'lettone',
    lt: 'lituano',
    mt: 'maltese',
    no: 'norvegese',
    pl: 'polacco',
    pt: 'portoghese',
    ro:'rumeno',
    sk: 'slovacco',
    sl: 'sloveno',
    es: 'spagnolo',
    sv: 'svedese',
};