export default {
    bg: 'bulgarų kalba',
    hr: 'kroatų kalba',
    cs: 'čekų kalba', 
    da: 'danų kalba', 
    nl: 'nyderlandų kalba',
    en: 'anglų kalba',
    et: 'estų kalba"',
    fi: 'suomių kalba',
    fr: 'prancūzų kalba',
    de: 'vokiečių kalba', 
    el: 'graikų kalba',
    hu: 'vengrų kalba',
    ga: 'airių kalba', 
    it: 'italų kalba',
    lv: 'latvių kalba',
    lt: 'lietuvių kalba',
    mt: 'maltiečių kalba',
    no: 'norvegų kalba',
    pl: 'lenkų kalba',
    pt: 'portugalų kalba',
    ro:'rumunų kalba',
    sk: 'slovakų kalba',
    sl: 'slovėnų kalba',
    es: 'ispanų kalba',
    sv: 'švedų kalba',
};