export default {
    bg: 'bulgāru valoda',
    hr: 'horvātu valoda',
    cs: 'čehu valoda', 
    da: 'dāņu valoda', 
    nl: 'holandiešu valoda',
    en: 'angļu valoda"',
    et: 'igauņu valoda',
    fi: 'somu valoda',
    fr: 'franču valoda',
    de: 'vācu valoda', 
    el: 'grieķu valoda',
    hu: 'ungāru valoda',
    ga: 'īru valoda', 
    it: 'itāļu valoda',
    lv: 'latviešu valoda',
    lt: 'lietuviešu valoda',
    mt: 'maltiešu valoda',
    no: 'norvēģu valoda',
    pl: 'poļu valoda',
    pt: 'portugāļu valoda',
    ro:'rumāņu valoda',
    sk: 'slovāku valoda',
    sl: 'slovēņu valoda',
    es: 'spāņu valoda',
    sv: 'zviedru valoda',
};