export default {
    bg: 'bulgaru',
    hr: 'kroat',
    cs: 'ċek', 
    da: 'daniż', 
    nl: 'olandiż',
    en: 'ingliż',
    et: 'eston',
    fi: 'finlandiż',
    fr: 'franċiż',
    de: 'ġermaniż', 
    el: 'grieg',
    hu: 'ungeriż',
    ga: 'irlandiż', 
    it: 'taljan',
    lv: 'latvjan',
    lt: 'litwan',
    mt: 'malti',
    no: 'norveġiż',
    pl: 'pollakk',
    pt: 'portugiż',
    ro:'rumen',
    sk: 'slovakk',
    sl: 'sloven',
    es: 'spanjol',
    sv: 'svediż',
};