export default {
    bg: 'bulgaars',
    hr: 'kroatisch',
    cs: 'tsjechisch', 
    da: 'deens', 
    nl: 'nederlands',
    en: 'engels',
    et: 'estisch',
    fi: 'fins',
    fr: 'frans',
    de: 'duits', 
    el: 'grieks',
    hu: 'hongaars',
    ga: 'iers', 
    it: 'italiaans',
    lv: 'lets',
    lt: 'litouws',
    mt: 'maltees',
    no: 'noors',
    pl: 'pools',
    pt: 'portugees',
    ro:'roemeens',
    sk: 'slowaaks',
    sl: 'sloveens',
    es: 'spaans',
    sv: 'zweeds',
};