// https://unric.org/nl/duurzame-ontwikkelingsdoelstellingen/
export default {
    bg: 'bulgaars',
    hr: 'kroatisch',
    cs: 'tsjechisch', 
    da: 'deens', 
    nl: 'nederlands',
    en: 'engels',
    et: 'estisch',
    fi: 'fins',
    fr: 'frans',
    de: 'duits', 
    el: 'grieks',
    hu: 'hongaars',
    ga: 'iers', 
    it: 'italiaans',
    lv: 'lets',
    lt: 'litouws',
    mt: 'maltees',
    no: 'noors',
    pl: 'pools',
    pt: 'portugees',
    ro:'roemeens',
    sk: 'slowaaks',
    sl: 'sloveens',
    es: 'spaans',
    sv: 'zweeds',
    LanguagePriorityInfo:'Hier kunt u de talen prioriteren op basis waarvan u resultaten wilt. Wat u bovenaan plaatst, is de taal waarin de pagina wordt weergegeven. U krijgt beleidsdocumenten in de taal met de hoogste prioriteit die de documenten beschikbaar hebben.',
    NoDocuments:'Sorry, er zijn geen documenten in een van de door u geselecteerde talen',
    AboutProject:'Over het project',
    AboutText:'Dit is een doorontwikkeling van een prototype gemaakt voor de gemeente Trondheim. Het werk wordt gedaan in het kader van het vak IT2901 Informatica Projectwerk II. De verdere ontwikkeling realiseert een meertalige gebruikersinterface, evenals een documentpagina om documenten te zien die verband houden met de verschillende doelen. De doorontwikkeling heeft plaatsgevonden bovenop een bestaand prototype dat is ontwikkeld als onderdeel van een masterscriptie in de informatica.',
    About:'Over deze site',
    Home:'Home',
    Close:'Dicht',
    GoTo:'Ga naar',
    TheRelation:'De relatie',
    hasDevelopmentArea:'heeftOntwikkelingsgebied',
    hasTradeoffTo:'heeftCompromisMet',
    hasContributionTo:'heeftBijdrageAan',
    Correlation:'Correlatie',
    Contribution:'Bijdrage',
    TradeOff: 'Compromis',
    To:'Aan',
    DevelopmentAreaCamel:'Ontwikkelingsgebied',
    For:'Voor',
    isA:'is een',
    binaryPositiveRelation:'binaire relatie die beschrijft dat de ene klasse / instantie een positieve invloed heeft op een andere klasse / instantie. De sterkte van deze relatie is niet gedefinieerd, waar een relatie tussen twee klassen / instanties waar alleen "heeftBijdrageAan" is gedefinieerd, betekent dat het bedrag van de bijdragen ongedefinieerd is. Zie respectievelijk "heeft (Hoog / Matig / Laag) - CorrelatieMet" - onder de relaties van heeftBijdrageAan voor meer goed gedefinieerde positieve invloeden.',
    ShowTargets:'Doelen tonen',
    developmentAreaRelation:'binaire relatie voor concepten met ontwikkelingsgebieden. Volgens de taxonomie van Statistics Norway wordt een ontwikkelingsgebied gedefinieerd onder perspectieven. Waar een ontwikkelgebied een concept is dat verbeterd wil worden. Bijvoorbeeld de begrippen: Economie en Natuur.',
    binaryNegativeRelation:'binaire relatie die beschrijft dat de ene klasse / instantie een negatieve invloed heeft op een andere klasse / instantie. De sterkte van deze relatie is niet gedefinieerd, waar een relatie tussen twee klassen / instanties waar alleen "heeftBijdrageAan" is gedefinieerd, betekent dat het bedrag van de bijdragen ongedefinieerd is. Zie respectievelijk "heeft (Hoog / Matig / Laag) - CorrelatieMet" - onder de relaties van heeftBijdrageAan voor meer goed gedefinieerde positieve invloeden.',
    UknownMunicipality:'Onbekende gemeente',
    Loading:'Laden',
    BackToHomePage:'Terug naar homepage',
    Fullscreen:'Schermvullend',
    StandardColor:'Standaard kleur',
    Targets:'Doel',
    Target:'Doelen',
    Tbl:'People Planet Profit',
    DevelopmentArea:'Ontwikkelingsgebied',
    ShowEdgeLabels:'Randlabels weergeven',
    NameMissing:'Naam ontbreekt',
    HasPositiveEffectOn: 'Heeft een positief effect op',
    HasNoEstablishedPositiveContributions: 'Heeft geen vastgestelde positieve bijdragen',
    HasNegativeEffectOn: 'Heeft een negatief effect op',
    HasNoEstablishedNegativeContributions: 'Heeft geen vastgestelde negatieve bijdragen',
    HasDevelopmentAreasFor: 'Heeft ontwikkelingsgebieden voor',
    HasNoDevelopmentAreas: 'Heeft geen ontwikkelingsgebieden',
    has:'heeft',
    aHigh:'een hoog',
    High:'Hoog',
    Low:'Laag',
    Moderate:'Matig',
    aModerate:'een gematigde',
    aLow:'een laag',
    to:'aan',
    on:'op',
    UnlockNodes:'Ontgrendel knooppunten',
    Sdg: 'Duurzame Ontwikkelingsdoelstelling',
    positiveEffect:'positief effect',
    negativeEffect:'negatief effect',
    ConceptUnderDevelopment:'Concept in ontwikkeling',
    ChangeLanguage:'Taal wijzigen',
    effects:'effecten',
    PositivePlural:'Positieve',
    NegativePlural:'Negatieve',
    DataUpload:'Data uploaden',
    ShowDocuments:'Documenten tonen',
    Show:'Toon',
    GoalDistanceComputation:'Berekening van doelafstand',
    SearchDocuments:'Documenten zoeken',
    Documents: 'Documenten',
    ToTop: 'Scroll naar boven',
    SeeMoreDocuments: 'Meer documenten bekijken',
    YourSearchReturned: 'Uw zoekopdracht heeft',
    results: 'resultaten opgeleverd',
    LanguagePriority:'Taalprioriteit',
    SearchLanguages:'Zoek talen',
    Multilingual:'Meertalig',
    MoreInfo:'Meer informatie',
    OpenAs:'Openen als',
    Active:'Actief',
    SeeRelatedGoals:'Zie gerelateerde doelen',
    Sdgs:'Duurzame Ontwikkelingsdoelstellingen',
    SdgOntology:'SDG Ontologie',
    Search:'Zoek',
    desc1:'Van 25 tot 27 september 2015 vond er in het hoofdkwartier van de Verenigde Naties in New York de Duurzame Ontwikkelingstop plaats waar alle staatshoofden, overheids- en topvertegenwoordigers samenkwamen. Ze bespraken de nieuwe Duurzame Ontwikkelingsdoelstellingen (SDG`s) die tegen 2030 bereikt moeten worden. De SDG`s werden voorafgegaan door de Millenniumdoelstellingen (MDG`s). Een terugkerend onderwerp in beide ontwikkelingsdoelstellingen is armoede. Het doel van de MDG`s was om het aantal personen wiens inkomen lager is dan $1,25 per dag te halveren tussen 1990 en 2015.',
    1:'Geen armoede',
    target1_1:'Tegen 2030 extreme armoede uitroeien voor alle mensen wereldwijd, die met minder dan $ 1,25 per dag moeten rondkomen',
    target1_2:'Tegen 2030 het aandeel mannen, vrouwen en kinderen van alle leeftijden die volgens de nationale definities in armoede leven in al haar dimensies, minstens tot de helft terugbrengen',
    target1_3:'Nationaal toepasbare sociale beschermingssystemen en maatregelen implementeren voor iedereen, met inbegrip van sociale beschermingsvloeren, en tegen 2030 een aanzienlijke dekkingsgraad realiseren van de armen en de kwetsbaren',
    target1_4:'Er tegen 2030 voor zorgen dat alle mannen en vrouwen, in het bijzonder de armen en de kwetsbaren, gelijke rechten hebben op economische middelen, alsook toegang tot basisdiensten, eigenaarschap en controle over land en andere vormen van eigendom, nalatenschap, natuurlijke hulpbronnen, gepaste nieuwe technologie en financiële diensten, met inbegrip van microfinanciering',
    target1_5:'Tegen 2030 de weerbaarheid opbouwen van de armen en van zij die zich in kwetsbare situaties bevinden en hun blootstelling aan en kwetsbaarheid voor met klimaatgerelateerde extreme gebeurtenissen en andere economische, sociale en ecologische schokken en rampen beperken',
    target1_a:'Zorgen voor een aanzienlijke mobilisatie van middelen afkomstig uit verschillende bronnen, ook via versterkte ontwikkelingssamenwerking, om adequate en voorspelbare middelen te voorzien voor ontwikkelingslanden, in het bijzonder de minst ontwikkelde landen, om programma`s en beleidslijnen te implementeren die een einde moeten maken aan armoede in al haar vormen',
    target1_b:' Solide beleidskaders creëren op nationaal, regionaal en internationaal niveau, die zijn gebaseerd op ontwikkelingsstrategieën ten gunste van de armen en het genderbeleid, om de versnelde investering te ondersteunen in acties die gericht zijn op het uitroeien van de armoede',
    desc2:'Sinds 1990 is het aantal ondervoede mensen in ontwikkelingslanden met bijna 50% verminderd. Die daling kunnen we ondermeer toeschrijven aan de succesvolle implementatie van de eerste Millenniumdoelstelling. Die was erop gericht om het aantal mensen dat honger lijdt te halveren tussen 1990 en 2015. Vandaag worden 805 miljoen mensen nog steeds bedreigd door honger en malnutritie, dat is één persoon op negen. Malnutritie is de oorzaak van bijna de helft van alle sterfgevallen bij kinderen onder de vijf jaar, dat zijn 3,1 miljoen kinderen per jaar. Wereldwijd lijdt één op vier kinderen aan een groeistoornis. In ontwikkelingslanden kan dat aantal oplopen tot één op drie.',
    2:'Geen honger',
    target2_1: 'Tegen 2030 een einde maken aan honger en voor iedereen, in het bijzonder de armen en de mensen die leven in kwetsbare situaties, met inbegrip van kinderen, toegang garanderen tot veilig, voedzaam en voldoende voedsel en dit het hele jaar lang',
    target2_2:'Tegen 2030 een einde maken aan alle vormen van malnutritie, waarbij ook tegen 2025 voldaan moet kunnen worden aan de internationaal overeengekomen doelstellingen met betrekking tot groeiachterstand en ondergewicht bij kinderen onder de 5 jaar; en eveneens tegemoetkomen aan de voedingsbehoeften van adolescente meisjes, zwangere vrouwen, vrouwen die borstvoeding geven en oudere personen',
    target2_3:'Tegen 2030 de landbouwproductiviteit en de inkomens verdubbelen voor kleinschalige voedselproducenten, in het bijzonder vrouwen, inheemse bevolkingen, familieboeren, veefokkers en vissers, onder meer door een veilige en gelijke toegang tot land, andere productieve hulpbronnen en inputs, kennis, financiële diensten, markten en opportuniteiten die toegevoegde waarde bieden en ook buiten de landbouw tewerkstelling genereren',
    target2_4:'Tegen 2030 duurzame voedselproductiesystemen garanderen en veerkrachtige landbouwpraktijken implementeren die de productiviteit en de productie kunnen verhogen, die helpen bij het in stand houden van ecosystemen, die de aanpassingscapaciteit verhogen in de strijd tegen klimaatverandering, extreme weersomstandigheden, droogte, overstromingen en andere rampen en die op een progressieve manier de kwaliteit van het land en de bodem verbeteren',
    target2_5:'Tegen 2020 de genetische diversiteit in stand houden van zaden, cultuurgewassen en gefokte en gedomesticeerde dieren en hun in het wild levende verwanten, ook aan de hand van zaad- en plantenbanken die op een degelijke manier beheerd en gediversifieerd worden op nationaal, regionaal en internationaal niveau; en de toegang bevorderen tot het eerlijk en billijk delen van voordelen afkomstig van het gebruik van genetische hulpbronnen en daaraan gekoppelde traditionele kennis, zoals internationaal overeengekomen',
    target2_a:'Verhogen van de investeringen, door versterkte internationale samenwerking, in landelijke infrastructuur, landbouwkundig onderzoek en uitgebreide diensten, technologische ontwikkeling en genetische databanken voor planten en vee om de landbouwkundige productiecapaciteit in ontwikkelingslanden, in het bijzonder in de minst ontwikkelde landen, te versterken',
    target2_b:'Corrigeren en voorkomen van handelsbeperkingen en scheefgegroeide situaties op de wereldlandbouwmarkten, door onder andere tegelijk alle vormen van landbouwexportsubsidies en alle exportmaatregelen met een gelijkaardig effect af te schaffen, in overeenstemming met het mandaat van de Ontwikkelingsronde in Doha',
    target2_c:'Maatregelen aannemen die de correcte werking moeten garanderen van de voedselgrondstoffenmarkten en hun afgeleiden en een snelle toegang tot marktinformatie bevorderen, met inbegrip van informatie over voedselreserves, om de extreme volatiliteit van de voedselprijzen te helpen beperken',
    desc3:'De derde Duurzame Ontwikkelingsdoelstelling (SDG3) is goede gezondheid en welzijn. Deze doelstelling is opgedeeld in vier grote pijlers die aandacht besteden aan moeder en kind, epidemieën, verkeersveiligheid en gezondheidszorg. Maar wat houden deze pijlers juist in? Het eerste target ijvert voor een duurzame ontwikkeling van moeder en kind door het aantal moedersterftes te verminderen tot 70 op 100.000. Volgens de Wereldgezondheidsorganisatie (WHO) sterven dagelijks 800 moeders door complicaties tijdens de zwangerschap die vermeden konden worden en maar liefst 99% van de moedersterftes vindt plaats in ontwikkelingslanden. Daarnaast moet men het overlijden van pas geboren baby`s vermijden en neonatale sterfte een halt toeroepen, aangezien twee op vijf kinderen jonger dan vijf jaar die overlijden pasgeborenen zijn.',
    3:'Goede gezondheid en welzijn',
    target3_1:'Tegen 2030 de globale moedersterfte terugdringen tot minder dan 70 per 100.000 levendgeborenen',
    target3_2:'Tegen 2030 een einde maken aan vermijdbare overlijdens van pasgeborenen en kinderen onder de 5 jaar, waarbij alle landen er moeten naar streven om het sterftecijfer van baby`s minstens tot 12 per 1000 levendgeborenen te beperken alsook het sterftecijfer van kinderen jonger dan 5 jaar eveneens in te perken tot maximum 25 per 1000 levendgeborenen',
    target3_3:'Tegen 2030 een einde maken aan epidemieën zoals aids, tuberculose, malaria en verwaarloosde tropische ziekten, alsook hepatitis, door water overgebrachte ziekten en andere overdraagbare ziekten bestrijden',
    target3_4:'Tegen 2030 de vroegtijdige sterfte gelinkt aan niet-overdraagbare ziekten met een derde inperken via preventie en behandeling, en mentale gezondheid en welzijn bevorderen',
    target3_5:'De preventie en behandeling versterken van misbruik van verslavende middelen, met inbegrip van drugsgebruik en het schadelijk gebruik van alcohol',
    target3_6:'Tegen 2020 het aantal doden en gewonden in het verkeer wereldwijd halveren',
    target3_7:'Tegen 2030 universele toegang tot seksuele en reproductieve gezondheidszorgdiensten garanderen, met inbegrip van diensten voor gezinsplanning, informatie en opvoeding, en voor de integratie van reproductieve gezondheid in nationale strategieën en programma`s',
    target3_8:'Zorgen voor een universele gezondheidsdekking, met inbegrip van de bescherming tegen financiële risico`s, toegang tot kwaliteitsvolle essentiële gezondheidszorgdiensten en toegang tot de veilige, doeltreffende, kwaliteitsvolle en betaalbare essentiële geneesmiddelen en vaccins voor iedereen',
    target3_9:'Tegen 2030 in aanzienlijke mate het aantal sterfgevallen en ziekten verminderen als gevolg van gevaarlijke chemicaliën en de vervuiling en besmetting van lucht, water en bodem',
    target3_a:'Waar nodig de implementatie van de kaderovereenkomst van de Wereldgezondheidsorganisatie over tabakscontrole versterken.',
    target3_b:'Het onderzoek en de ontwikkeling ondersteunen van vaccins en geneesmiddelen voor overdraagbare en niet-overdraagbare ziekten die in hoofdzaak ontwikkelingslanden treffen, toegang verschaffen tot betaalbare essentiële geneesmiddelen en vaccins, volgens de richtlijnen van de Verklaring van Doha aangaande het TRIPS-akkoord en Volksgezondheid. De Verklaring bevestigt het recht van ontwikkelingslanden om ten volle gebruik te maken van de bepalingen van de Overeenkomst aangaande de Handelsaspecten van de Intellectuele Eigendom (TRAIPR) die afwijkingen toelaat voor de bescherming van de volksgezondheid; en, in het bijzonder, het verschaffen van toegang tot geneesmiddelen voor iedereen.',
    target3_c:'De financiering van de gezondheidszorg aanzienlijk opvoeren, net als de aanwerving, de ontwikkeling, de opleiding en het lange tijd in dienst houden van gezondheidswerkers in ontwikkelingslanden, in het bijzonder in de minst ontwikkelde landen en de kleine eilandstaten in ontwikkeling.',
    target3_d:'De capaciteit van alle landen versterken, in het bijzonder die van de ontwikkelingslanden, met betrekking tot systemen voor vroegtijdige waarschuwing, risicovermindering en het beheer van nationale en globale gezondheidsrisico`s.',
    desc4:'Het recht op onderwijs ligt aan de basis van alle andere mensenrechten. Toch zijn 121 miljoen kinderen nog nooit naar school geweest of ze hebben de schoolbanken vroegtijdig verlaten. Dit staat in schril contrast met de belofte van de internationale gemeenschap om tegen 2015 ‘onderwijs voor iedereen` te creëren. De voorbije 15 jaar werd er zeker vooruitgang geboekt. Zo steeg het percentage van inschrijvingen voor de basisschool in ontwikkelingslanden van 83% in 2000 naar 91% in 2015. Toch zijn er vandaag nog steeds 57 miljoen kinderen van basisschooleeftijd die niet naar school gaan. Dat betekent dat één kind op zes in ontwikkelingslanden geen toegang heeft tot basisonderwijs.',
    4:'Kwaliteitsonderwijs',
    target4_1:'Er tegen 2030 voor zorgen dat alle meisjes en jongens op een vrije, billijke en kwalitatief hoogstaande manier lager en middelbaar onderwijs kunnen afwerken, wat moet kunnen leiden tot relevante en doeltreffende leerresultaten',
    target4_2:'Er tegen 2030 voor zorgen dat alle meisjes en jongens in hun vroege kindertijd toegang hebben tot een kwalitatieve ontwikkeling, zorg en opvoeding voorafgaand aan de lagere school zodat ze klaar zijn voor het basisonderwijs',
    target4_3:'Tegen 2030 gelijke toegang garanderen voor alle vrouwen en mannen tot betaalbaar en kwaliteitsvol technisch, beroeps- en hoger onderwijs, met inbegrip van de universiteit',
    target4_4:'Tegen 2030 het aantal jongeren en volwassenen met relevante vaardigheden, met inbegrip van technische en beroepsvaardigheden, voor tewerkstelling, degelijke jobs en ondernemerschap aanzienlijk opdrijven',
    target4_5:'Tegen 2030 genderongelijkheden wegwerken in het onderwijs en zorgen voor gelijke toegang tot alle niveaus inzake onderwijs en beroepsopleiding voor de kwetsbaren, met inbegrip van mensen met een handicap, inheemse bevolkingen en kinderen in kwetsbare situaties',
    target4_6:'Er tegen 2030 voor zorgen dat alle jongeren en een groot aantal volwassenen, zowel mannen als vrouwen, geletterd en rekenvaardig zijn',
    target4_7:'Er tegen 2030 voor zorgen dat alle leerlingen kennis en vaardigheden verwerven die nodig zijn om duurzame ontwikkeling te bevorderen, onder andere via vorming omtrent duurzame ontwikkeling en duurzame levenswijzen, mensenrechten, gendergelijkheid, de bevordering van een cultuur van vrede en geweldloosheid, wereldburgerschap en de waardering van culturele diversiteit en van de bijdrage van de cultuur tot de duurzame ontwikkeling.',
    target4_a:'Bouwen en verbeteren van onderwijsfaciliteiten die aandacht hebben voor kinderen, mensen met een beperking en gendergelijkheid en die een veilige, geweldloze, inclusieve en doeltreffende leeromgeving bieden voor iedereen.',
    target4_b:'Tegen 2020 het aantal studiebeurzen wereldwijd en substantieel verhogen dat beschikbaar is voor ontwikkelingslanden, in het bijzonder de minst ontwikkelde landen, de kleine eilandstaten in ontwikkeling en de Afrikaanse landen, voor toegang tot het hoger onderwijs, met inbegrip van beroepsopleiding en programma`s omtrent informatie en communicatietechnologie, techniek, ingenieurswezen en wetenschappen, in ontwikkelde landen en andere ontwikkelingslanden.',
    target4_c:'Tegen 2030 op aanzienlijke wijze de toevloed verhogen van gekwalificeerde leraren, ook via internationale samenwerking voor lerarenopleidingen in ontwikkelingslanden, in het bijzonder in de minst ontwikkelde landen en de kleine eilandstaten in ontwikkeling.',
    desc5:'Wist je dat vrouwen meer dan de helft van de wereldbevolking uitmaken? Toch krijgen vrouwen nog vaak te maken met discriminatie. Zo zijn ze vaak het slachtoffer van geweld en hebben ze in veel landen geen toegang tot gezondheidszorg. Om deze problematiek aan te pakken, ontwikkelde de VN de vijfde Duurzame Ontwikkelingsdoelstelling (SDG 5). Hoewel vrouwen een belangrijke rol spelen bij alle SDG`s, is SDG 5 de enige doelstelling die zich specifiek op gender focust. Het hoofddoel van de doelstelling is om gendergelijkheid en de empowerment van alle vrouwen en meisjes te bereiken. Om dat doel te behalen, is SDG 5 onderverdeeld in een aantal subdoelstellingen.',
    5:'Gendergelijkheid',
    target5_1:'Een einde maken aan alle vormen van discriminatie jegens vrouwen en meisjes, overal',
    target5_2:'Alle vormen van geweld tegen vrouwen en meisjes in de openbare en de privésfeer uitroeien, ook inzake vrouwenhandel en seksuele en andere soorten uitbuiting',
    target5_3:'Uit de wereld helpen van alle schadelijke praktijken, zoals kind-, vroege en gedwongen huwelijken en vrouwelijke genitale verminking',
    target5_4:'Erkennen en naar waarde schatten van onbetaalde zorg en thuiswerk door het voorzien van openbare diensten, infrastructuur en een sociaal beschermingsbeleid en door de bevordering van gedeelde verantwoordelijkheden binnen het gezin en de familie, zoals dat nationaal van toepassing is',
    target5_5:'Verzekeren van de volledige en doeltreffende deelname van vrouwen en voor gelijke kansen inzake leiderschap op alle niveaus van de besluitvorming in het politieke, economische en openbare leven',
    target5_6:'Verzekeren van universele toegang tot seksuele en reproductieve gezondheid en reproductieve rechten zoals overeengekomen in het kader van het Actieprogramma van de Internationale Conferentie over Bevolking en Ontwikkeling en het Peking-Actieplatform en de slotdocumenten van hun desbetreffende conferenties',
    target5_a:'Hervormingen doorvoeren waarbij vrouwen gelijke rechten krijgen op economische middelen, naast toegang tot eigenaarschap en controle over land en andere vormen van eigendom, financiële diensten, erfenissen en natuurlijke hulpbronnen, in overeenstemming met nationaal recht',
    target5_b:'Het gebruik doen toenemen van innovatieve technologie, in het bijzonder de informatie- en communicatietechnologie, om te komen tot een grotere empowerment van vrouwen',
    target5_c:'Een gezond beleid en afdwingbare wetgeving goedkeuren en versterken voor de bevordering van gendergelijkheid en de empowerment van alle vrouwen en meisjes op alle niveaus',
    desc6:'Elk jaar sterven er drie miljoen mensen door slechte waterkwaliteit en een gebrekkige toegang tot drinkwater. De meerderheid van die slachtoffers zijn kinderen jonger dan vijf jaar. Water vormt de kern van duurzame ontwikkeling. Zo kunnen watervoorraden op verschillende manieren een bijdrage leveren aan armoedebestrijding, economische groei en milieubescherming. Van voedsel- en energiezekerheid tot de gezondheid van de mens en het milieu, water draagt bij aan de bevordering van sociale welvaart en gelijkaardige economische groei en heeft invloed op het levensonderhoud van miljarden mensen.',
    6:'Schoon water en sanitair',
    target6_1:'Tegen 2030 komen tot een universele en gelijke toegang tot veilig en betaalbaar drinkwater voor iedereen',
    target6_2:'Tegen 2030 komen tot toegang tot gepaste en degelijke sanitaire voorzieningen en hygiëne voor iedereen en een einde maken aan openbare ontlasting, waarbij speciale aandacht wordt besteed aan de behoeften van vrouwen en meisjes en mensen in kwetsbare situaties',
    target6_3:'Tegen 2030 de waterkwaliteit verbeteren door verontreiniging te beperken, de lozing van gevaarlijke chemicaliën en materialen een halt toe te roepen en de uitstoot ervan tot een minimum te beperken waarbij ook het aandeel van onbehandeld afvalwater wordt gehalveerd en recyclage en veilige hergebruik wereldwijd aanzienlijk worden verhoogd',
    target6_4:'Tegen 2030 in aanzienlijke mate de efficiëntie van het watergebruik verhogen in alle sectoren en het duurzaam winnen en verschaffen van zoetwater garanderen om een antwoord te bieden op de waterschaarste en om het aantal mensen dat af te rekenen heeft met waterschaarste, aanzienlijk te verminderen',
    target6_5:'Tegen 2030 het geïntegreerde beheer van de waterhulpbronnen implementeren op alle niveaus, ook via gerichte grensoverschrijdende samenwerking',
    target6_6:'Tegen 2020 de op water gebaseerde ecosystemen beschermen en herstellen, met inbegrip van bergen, bossen, moerassen, rivieren, grondwaterlagen en meren',
    target6_a:'Tegen 2030 de internationale samenwerking en de capaciteitsopbouwende ondersteuning uitbreiden voor de ontwikkelingslanden voor activiteiten die betrekking hebben op water en sanitaire voorzieningen en programma`s, met inbegrip van technologieën voor waterwinning, ontzilting, waterefficiëntie, afvalwaterzuivering, recyclage en hergebruik.',
    target6_b:'De deelname versterken en ondersteunen van plaatselijke gemeenschappen bij de verbetering van het waterbeheer en van de sanitaire voorzieningen',
    desc7:'In bijna elke grote uitdaging en kans in de wereld staat energie centraal. Zowel voor jobs, veiligheid, klimaatverandering, voedselproductie als voor het verhogen van de inkomens is toegang tot energie essentieel. Toch heeft één op vijf mensen in de wereld geen toegang tot moderne elektriciteit. Drie miljard mensen zijn voor koken en verwarming nog steeds afhankelijk van hout, steenkool, houtskool of dierlijk afval. Energie draagt het meeste bij aan de klimaatverandering, aangezien het verantwoordelijk is voor ongeveer 60 procent van de wereldwijde uitstoot van broeikasgassen. Het aandeel van CO2-uitstoot bij energie beperken, is een van de hoofddoelen om klimaatveranderingen op lange termijn onder controle te houden.',
    7:'Betaalbare en duurzame energie',
    target7_1:'Tegen 2030 universele toegang tot betaalbare, betrouwbare en moderne energiediensten garanderen',
    target7_2:'Tegen 2030 in aanzienlijke mate het aandeel hernieuwbare energie in de globale energiemix verhogen',
    target7_3:'Tegen 2030 de globale snelheid van verbetering in energie-efficiëntie verdubbelen',
    target7_a:'Tegen 2030 de internationale samenwerking verhogen om toegang te vergemakkelijken tot onderzoek en technologie inzake schone energie, met inbegrip van de hernieuwbare energie, de energiedoeltreffendheid en de geavanceerde en schonere fossiele brandstoffentechnologie, en de investering promoten in energie-infrastructuur en schone energietechnologie',
    target7_b:'Tegen 2030 de infrastructuur uitbreiden en de technologie upgraden om moderne en duurzame energiediensten te kunnen aanbieden aan alle ontwikkelingslanden, in het bijzonder de minst ontwikkelde landen, de kleine eilandstaten in ontwikkeling en door land ingesloten ontwikkelingslanden, in overeenstemming met hun respectieve steunprogramma`s',
    desc8:'Vandaag werken wereldwijd 168 miljoen kinderen, 74 miljoen jongvolwassenen zijn werkloos en 60% van de arbeiders werkt zonder contract. De arbeidsmarkt moet veranderen om rechtvaardiger, gelijkwaardiger en veiliger te worden. De achtste Duurzame Ontwikkelingsdoelstelling (SDG 8) streeft naar de afschaffing van dwangarbeid, de uitbanning van slavernij en mensenhandel, het verbod op de ergste vormen van kinderarbeid waaronder het werven en inzetten van kindsoldaten, en het beëindigen van alle vormen van kinderarbeid tegen 2025. Volgens de Internationale Arbeidsorganisatie (ILO) is de strijd tegen arbeidsonzekerheid een van de prioriteiten. In 2014 waren 201 miljoen mensen werkloos en waren 21 miljoen mensen het slachtoffer van dwangarbeid.',
    8:'Eerlijk werk en economische groei',
    target8_1:'De economische groei per capita in stand houden in overeenstemming met de nationale omstandigheden en, in het bijzonder, minstens 7% aangroei van het bruto binnenlands product per jaar in de minst ontwikkelde landen',
    target8_2:'Tot meer economische productiviteit komen door diversificatie, technologische modernisatie en innovatie, ook door de klemtoon te leggen op sectoren met hoge toegevoegde waarde en arbeidsintensieve sectoren',
    target8_3:'Bevorderen van op ontwikkeling toegespitste beleidslijnen die productieve activiteiten ondersteunen, alsook de creatie van waardige jobs, ondernemerschap, creativiteit en innovatie, en de formalisering en de groei aanmoedigen van micro-, kleine en middelgrote ondernemingen, ook via toegang tot financiële diensten',
    target8_4:'Tegen 2030 geleidelijk aan de wereldwijde efficiëntie, productie en consumptie van hulpbronnen verbeteren en streven naar de ontkoppeling van economische groei en achteruitgang van het milieu, volgens het 10-jarig Programmakader voor Duurzame Consumptie en Productie, waarbij de ontwikkelde landen de leiding nemen',
    target8_5:'Tegen 2030 komen tot een volledige en productieve tewerkstelling en waardig werk voor alle vrouwen en mannen, ook voor jonge mensen en personen met een handicap, alsook een gelijk loon voor werk van gelijke waarde',
    target8_6:'Tegen 2020 het aandeel aanzienlijk terugschroeven van jongeren die niet aan het werk zijn, geen onderwijs volgen en niet met een opleiding bezig zijn',
    target8_7:'Onmiddellijke en effectieve maatregelen nemen om gedwongen arbeid uit de wereld te helpen, een einde te maken aan moderne slavernij en mensensmokkel en het verbod en de afschaffing van de ergste vormen van kinderarbeid veiligstellen, met inbegrip van het rekruteren en inzetten van kindsoldaten, en tegen 2025 een einde stellen aan kinderarbeid in al haar vormen',
    target8_8:'De arbeidsrechten beschermen en veilige en gezonde werkomgevingen bevorderen voor alle werknemers, met inbegrip van migrerende werknemers, in het bijzonder vrouwelijke migranten, en zij die zich in precaire werkomstandigheden bevinden',
    target8_9:'Tegen 2030 beleidslijnen uitwerken en implementeren ter ondersteuning van het duurzaam toerisme dat jobs creëert en plaatselijke cultuur en producten bevordert',
    target8_10:'Versterken van de mogelijkheden van de plaatselijke financiële instellingen om toegang tot het bankwezen, de verzekeringen en financiële diensten voor allen aan te moedigen',
    target8_a:'Verhogen van de Aid for Trade voor ontwikkelingslanden, in het bijzonder de minst ontwikkelde landen, ook via het verbeterde geïntegreerde kader voor handelsgerelateerde bijstand aan de minst ontwikkelde landen',
    target8_b:'Tegen 2020 een globale strategie voor jongerentewerkstelling ontwikkelen en die operationeel maken en het Globale Jobspact van de Internationale Arbeidsorganisatie implementeren',
    desc9:'Investeringen in infrastructuur – transport, irrigatie, energie, informatie en communicatietechnologie – leiden tot groei in productiviteit en inkomen, en verbeteringen in gezondheidszorg en onderwijs. Technologische vooruitgang biedt namelijk duurzame oplossingen voor economische uitdagingen en milieuproblemen: het creëert nieuwe jobs en zorgt voor betere energie-efficiëntie. Nieuwe jobs en duurzame economische groei genereren meer inkomen, wat leidt tot een hogere levensstandaard. Daarenboven biedt technologische innovatie ook oplossingen voor ecologische uitdagingen.',
    9:'Industrie, innovatie en infrastructuur',
    target9_1:'Ontwikkelen van kwalitatieve, betrouwbare, duurzame en veerkrachtige infrastructuur, met inbegrip van regionale en grensoverschrijdende infrastructuur, ter ondersteuning van de economische ontwikkeling en het menselijk welzijn, met klemtoon op een betaalbare en billijke toegang voor iedereen',
    target9_2:'Bevorderen van inclusieve en duurzame industrialisering en, tegen 2030, het aandeel in de werkgelegenheid en het bruto binnenlands product van de industrie aanzienlijk doen toenemen, in overeenstemming met de nationale omstandigheden, en dat aandeel verdubbelen in de minst ontwikkelde landen',
    target9_3:'De toegang vergroten van kleinschalige industriële en andere ondernemingen, in het bijzonder in de ontwikkelingslanden, tot financiële diensten, inclusief betaalbare kredietverlening, alsook hun integratie in waardeketens en markten',
    target9_4:'Tegen 2030 de infrastructuur moderniseren en industrieën aanpassen om hen duurzaam te maken, waarbij de focus ligt op een grotere doeltreffendheid bij het gebruik van hulpbronnen en van schonere en milieuvriendelijke technologieën en industriële processen, waarbij alle landen de nodige actie ondernemen volgens hun eigen respectieve mogelijkheden',
    target9_5:'Verbeteren van het wetenschappelijk onderzoek, moderniseren van de technologische capaciteiten van industriesectoren in alle landen, in het bijzonder in ontwikkelingslanden, waarbij ook tegen 2030 innovatie wordt aangemoedigd en op aanzienlijke wijze het aantal onderzoeks- en ontwikkelingswerkers per miljoen inwoners wordt verhoogd en waarbij ook meer wordt uitgegeven aan publiek en privaat onderzoek en ontwikkeling',
    target9_a:'De duurzame en veerkrachtige ontwikkeling van infrastructuur mogelijk maken in ontwikkelingslanden aan de hand van extra financiële, technologische en technische steun aan Afrikaanse landen, de minst ontwikkelde landen, de door land ingesloten ontwikkelingslanden en de kleine eilandstaten in ontwikkeling.',
    target9_b:'Ondersteunen van de binnenlandse technologische ontwikkeling, onderzoek en innovatie in ontwikkelingslanden, ook door een gunstig beleidsklimaat te garanderen voor, onder andere, industriële diversificatie en waardetoevoeging aan handelsproducten',
    target9_c:' In aanzienlijke mate de toegang verhogen tot informatie- en communicatietechnologie en streven naar het verschaffen van universele en betaalbare toegang tot internet in de minst ontwikkelde landen tegen 2020',
    desc10:'In 2016 zal de gecumuleerde rijkdom van de rijkste 1% van de wereld groter zijn dan die van de overige 99%. Wereldwijd blijven ongelijkheden en extreme armoede bestaan, ook al neemt ze in het algemeen af. Vandaag leven nog steeds 700 miljoen mensen in extreme armoede, wat gelijk is aan net iets minder dan 10% van de wereldbevolking. De tiende Duurzame Ontwikkelingsdoelstelling (SDG 10) wil niet alleen de ongelijkheid tussen staten verminderen, maar ook de ongelijkheid in de staten zelf. Ondanks dat in de meeste opkomende landen de armoede in de voorbije decennia is gedaald, leven grote delen van de bevolking, zoals de boeren in China en Brazilië, nog steeds in armoede, terwijl een kleine groep een groot deel van de rijkdom bezit.',
    10:'Ongelijkheid verminderen',
    target10_1:'Tegen 2030 geleidelijk tot een inkomenstoename van de onderste 40% van de bevolking komen tegen een ritme dat hoger ligt dan het nationale gemiddelde, en die toename ook in stand houden',
    target10_2:'Tegen 2030 de sociale, economische en politieke inclusie van iedereen mogelijk maken en bevorderen, ongeacht leeftijd, geslacht, handicap, ras, etniciteit, herkomst, godsdienst of economische of andere status',
    target10_3:'Gelijke kansen verzekeren en ongelijkheden wegwerken, ook door het afvoeren van discriminerende wetten, beleidslijnen en praktijken en door het bevorderen van de geschikte wetgeving, beleidslijnen en acties in dit opzicht',
    target10_4:'Beleid voeren dat geleidelijk tot een grotere gelijkheid leidt, in het bijzonder inzake fiscaliteit, lonen en sociale bescherming',
    target10_5:'De regulering en monitoring verbeteren van de globale financiële markten en instellingen en de implementatie versterken van dergelijke reguleringen',
    target10_6:'Een verbeterde vertegenwoordiging verzekeren en een beter gehoor geven aan de ontwikkelingslanden bij de besluitvorming in mondiale, internationale economische en financiële instellingen om te komen tot meer doeltreffende, geloofwaardige, verantwoordelijke en legitieme instellingen',
    target10_7:'Een ordelijke, veilige, regelmatige en verantwoordelijke migratie en mobiliteit van mensen mogelijk maken, ook via de implementatie van geplande en degelijk beheerde migratiebeleidslijnen',
    target10_a:'Het beginsel implementeren van speciale en gedifferentieerde behandeling voor ontwikkelingslanden, in het bijzonder de minst ontwikkelde landen, in overeenstemming met de overeenkomsten van de Wereldhandelsorganisatie',
    target10_b:'Officiële ontwikkelingsbijstand en financiële stromen aanmoedigen, met inbegrip van directe buitenlandse investeringen, voor staten waar de behoefte het grootst is, in het bijzonder in de minst ontwikkelde landen, de Afrikaanse landen, de kleine eilandstaten in ontwikkeling en de door land ingesloten ontwikkelingslanden, in overeenstemming met hun nationale plannen en programma`s',
    target10_c:'Tegen 2030 de transactiekosten van overschrijvingen van migranten reduceren tot minder dan 3% en transfer vanuit landen met kosten hoger dan 5% elimineren',
    desc11:'Vandaag leven 2 op 3 Europeanen en bijna 3,9 miljard mensen wereldwijd – meer dan de helft van de wereldbevolking! – in steden. Dat aantal zal alleen maar toenemen en volgens de meest recente cijfers zou 60% van de wereldbevolking in een stedelijke omgeving leven tegen 2030. Om die groeiende bevolking te ondersteunen ontwikkelde de VN de elfde Duurzame Ontwikkelingsdoelstelling (SDG 11). De stedelijke bevolking zal het snelst toenemen in de ontwikkelingslanden. Daar heeft de huidige groei al geleid tot een boom in megasteden. In 1990 waren er 10 steden met 10 miljoen of meer inwoners, in 2014 waren dat er 28. In totaal wonen er in deze steden meer dan 485 miljoen mensen. In de volgende decennia zal 95% van de stedelijke groei plaatsvinden in ontwikkelingslanden.',
    11:'Duurzame steden en gemeenschappen',
    target11_1:'Tegen 2030 voor iedereen toegang voorzien tot adequate, veilige en betaalbare huisvesting en basisdiensten, en sloppenwijken verbeteren',
    target11_2:'Tegen 2030 toegang voorzien tot veilige, betaalbare, toegankelijke en duurzame vervoerssystemen voor iedereen, waarbij de verkeersveiligheid verbeterd wordt, met name door het openbaar vervoer uit te breiden, met aandacht voor de behoeften van mensen in kwetsbare situaties, vrouwen, kinderen, personen met een handicap en ouderen',
    target11_3:'Tegen 2030 inclusieve en duurzame stadsontwikkeling en capaciteit opbouwen voor participatieve, geïntegreerde en duurzame planning en beheer van menselijke nederzettingen in alle landen',
    target11_4:'De inspanningen verhogen om het culturele en natuurlijke erfgoed van de wereld te beschermen en veilig te stellen',
    target11_5:'Tegen 2030 het aantal doden en getroffenen aanzienlijk verminderen en in aanzienlijke mate de rechtstreekse economische impact op het bruto binnenlands product terugschroeven dat veroorzaakt wordt door rampen, met inbegrip van rampen die met water verband houden, waarbij de klemtoon ligt op het beschermen van de armen en van mensen in kwetsbare situaties',
    target11_6:'Tegen 2030 de nadelige milieu-impact van steden per capita reduceren, ook door bijzondere aandacht te besteden aan de luchtkwaliteit en aan het gemeentelijk en ander afvalbeheer',
    target11_7:'Tegen 2030 universele toegang voorzien tot veilige, inclusieve en toegankelijke, groene en openbare ruimtes, in het bijzonder voor vrouwen en kinderen, ouderen en personen met een handicap',
    target11_a:'Positieve economische, sociale en ecologische verbanden ondersteunen tussen stedelijke, voorstedelijke en landelijke gebieden door de nationale en regionale ontwikkelingsplanning te versterken',
    target11_b:'Tegen 2020 het aantal steden en menselijke nederzettingen aanzienlijk verhogen die geïntegreerde beleidslijnen en plannen goedkeuren en implementeren inzake inclusie, doeltreffendheid van hulpbronnengebruik, mitigatie en adaptatie aan klimaatverandering, weerbaarheid tegen rampen, en in overeenstemming met het kader van Sendai voor rampenrisicovermindering 2015-2030 een holistisch ramprisicobeheer ontwikkelen en implementeren op alle niveaus',
    target11_c:'De minst ontwikkelde landen steunen, ook via financiële en technische bijstand, in het opbouwen van duurzame en veerkrachtige gebouwen waarbij gebruik wordt gemaakt van lokale materialen',
    desc12:'We verspillen vandaag 30% van de wereldwijde voedselproductie. We produceren en consumeren zonder voldoende rekening te houden met de impact op de natuurlijke rijkdommen van de planeet. De huidige situatie is onhoudbaar en daarom moeten we “meer doen, met minder”. De wereldbevolking zou tegen 2050 9,6 miljard mensen tellen: als we de huidige levenswijze van de ontwikkelde landen behouden, zullen we grondstoffen voor drie planeten nodig hebben. Een andere sprekende vergelijking: ieder jaar verbruiken we 250 km³ water om levensmiddelen te produceren die verloren gaan of verspild worden. Dit komt overeen met een volume water dat drie maal groter is dan het volume van het meer van Genève, of vergelijkbaar is met het jaarlijkse debiet van de Wolga, de Russische rivier die de grootste van Europa is.',
    12:'Verantwoorde consumptie en productie',
    target12_1:'Het 10-jarig Programmakader inzake Duurzame Consumptie- en Productiepatronen implementeren, waarbij alle landen actie ondernemen, en waarbij de ontwikkelde landen de leiding nemen, rekening houdend met de ontwikkeling en de mogelijkheden van de ontwikkelingslanden',
    target12_2:'Tegen 2030 het duurzame beheer en het efficiënte gebruik van natuurlijke hulpbronnen realiseren',
    target12_3:'Tegen 2030 de voedselverspilling in winkels en bij consumenten per capita halveren en voedselverlies reduceren in de productie- en bevoorradingsketens, met inbegrip van verliezen na de oogst',
    target12_4:'Tegen 2020 komen tot een milieuvriendelijk beheer van chemicaliën en van alle afval gedurende hun hele levenscyclus, in overeenstemming met afgesproken internationale kaderovereenkomsten, en de uitstoot aanzienlijk beperken in lucht, water en bodem om hun negatieve invloeden op de menselijke gezondheid en het milieu zoveel mogelijk te beperken',
    target12_5:'Tegen 2030 de afvalproductie aanzienlijk beperken via preventie, vermindering, recyclage en hergebruik',
    target12_6:'Bedrijven aanmoedigen, in het bijzonder grote en transnationale bedrijven, om duurzame praktijken aan te nemen en duurzaamheidsinformatie te integreren in hun rapporteringscyclus',
    target12_7:'Duurzame praktijken bij overheidsopdrachten bevorderen in overeenstemming met nationale beleidslijnen en prioriteiten',
    target12_8:'Tegen 2030 garanderen dat mensen overal beschikken over relevantie informatie over en zich bewust zijn van duurzame ontwikkeling en levensstijlen die in harmonie zijn met de natuur',
    target12_a:'Ondersteunen van ontwikkelingslanden ter versterking van hun wetenschappelijke en technologische mogelijkheden om de richting uit te gaan van meer duurzame consumptie- en productiepatronen',
    target12_b:'Ontwikkelen en implementeren van instrumenten om de impact te monitoren van duurzame ontwikkeling op duurzaam toerisme dat werkgelegenheid creëert en de plaatselijke cultuur en producten promoot',
    target12_c:'Inefficiënte subsidies voor fossiele brandstoffen die afvalproducerende consumptie aanmoedigen rationaliseren, door storende marktinvloeden uit de wereld te helpen, in overeenstemming met de nationale omstandigheden, ook door het belastingsysteem te herstructureren en deze schadelijke subsidies te laten uitdoven, waar deze bestaan, waarbij rekening wordt gehouden met de specifieke noden en omstandigheden in de ontwikkelingslanden en waarbij de mogelijke negatieve invloeden worden geminimaliseerd op hun ontwikkeling op een manier die de armen en de getroffen gemeenschappen beschermt',
    desc13:'Klimaatverandering heeft een effect op elk land, op elk continent. Het ontwricht nationale economieën en beïnvloedt levens, met grote kosten voor mensen, gemeenschappen en landen, nu en in de toekomst. Iedereen kan de impact van klimaatverandering ondervinden, of het nu gaat om veranderende weerpatronen, de stijgende zeespiegel of om frequentere extreme weerverschijnselen. De uitstoot van broeikasgassen door menselijke activiteiten versnellen de klimaatverandering en blijven ondertussen nog stijgen. De uitstoot is nu 50% hoger dan het niveau van 1990 en staat dus op recordhoogte. Zonder maatregelen zal de temperatuur van de aarde met 3 graden Celcius stijgen, en op sommige plaatsen zelfs nog meer. De armste en meer kwetsbare mensen zullen daar het eerste en grootste slachtoffer van zijn.',
    13:'Klimaatactie',
    target13_1:'De veerkracht en het aanpassingsvermogen versterken van met klimaat in verband te brengen gevaren en natuurrampen in alle landen',
    target13_2:'Maatregelen inzake klimaatverandering integreren in nationale beleidslijnen, strategieën en planning',
    target13_3:'De opvoeding, bewustwording en de menselijke en institutionele capaciteit verbeteren met betrekking tot mitigatie, adaptatie, impactvermindering en vroegtijdige waarschuwing inzake klimaatverandering',
    target13_a:'De verbintenis  uitvoeren die door de ontwikkelde landen in het kader van het Raamverdrag van de Verenigde Naties inzake Klimaatverandering genomen werd omtrent de doelstelling om tegen 2020 gezamenlijk jaarlijks $ 100 miljard bijeen te brengen uit allerlei bronnen, om tegemoet te komen aan de behoeften van de ontwikkelingslanden in de context van aanzienlijke mitigatieacties en van transparantie inzake implementatie, en om door deze kapitalisatie het Groene Klimaatfonds zo snel mogelijk volledig operationeel te maken',
    target13_b:'Mechanismen promoten om de capaciteit te vergroten in het kader van doeltreffende aan klimaatverandering gekoppelde planning en beheer in de minst ontwikkelde landen en de kleine eilandstaten in ontwikkeling, waarbij ook wordt gefocust op vrouwen, jongeren en lokale en gemarginaliseerde gemeenschappen',
    desc14:'Waterbronnen, en de manier waarop ermee omgegaan wordt, hebben een impact op de maatschappij en de economie, vooral op vlak van gezondheid, voedselproductie, hygiëne, energie, industrie en de werking van ecosystemen. Daarnaast zijn visvangst en visteelt de bron van inkomsten voor ongeveer 540 miljoen personen (zo`n 8% van de wereldbevolking). Verontreiniging van de zee is een enorme plaag voor het milieu. Het kan schadelijke effecten veroorzaken voor in zee levende organismen en ecosystemen. De verandering van de waterkwaliteit kan leiden tot een verlies aan biodiversiteit, gezondheidsrisico`s voor de mens en kan activiteiten op zee belemmeren, waaronder vissen, toerisme en hobby`s. Naar schatting 70 tot 80% van het afval dat op zee en aan de kust teruggevonden wordt, is afkomstig van het vasteland, 60 tot 95% van het afval op de bodem van de zee is plastic, voornamelijk verpakkingen als boodschappentassen, flessen, etc.',
    14:'Leven in het water',
    target14_1:'Tegen 2025 de vervuiling van de zee voorkomen en in aanzienlijke mate verminderen, in het bijzonder als gevolg van activiteiten op het land, met inbegrip van vervuiling door ronddrijvend afval en voedingsstoffen',
    target14_2:'Tegen 2020 op een duurzame manier zee- en kustecosystemen beheren en beschermen om aanzienlijke negatieve gevolgen te vermijden, ook door het versterken van hun veerkracht, en actie ondernemen om deze te herstellen en om te komen tot gezonde en productieve oceanen',
    target14_3:'De impact van de verzuring van de oceanen minimaliseren en aanpakken, ook via verhoogde wetenschappelijke samenwerking op alle niveaus',
    target14_4:'Tegen 2020 op een doeltreffende manier de visvangst reguleren en een einde maken aan overbevissing, aan illegale, niet-aangegeven en ongereguleerde visserij en aan destructieve visserijpraktijken, en op wetenschap gebaseerde beheerplannen implementeren, om de visvoorraden zo snel mogelijk te herstellen, op zijn minst op niveaus die een maximale duurzame opbrengst kunnen garanderen zoals bepaald door hun biologische kenmerken',
    target14_5:'Tegen 2020 minstens 10% van de kust- en zeegebieden behouden, in overeenstemming met het nationale en internationale recht en gebaseerd op de beste beschikbare wetenschappelijke informatie',
    target14_6:'Tegen 2020 bepaalde vormen van visserijsubsidies afschaffen die bijdragen tot overcapaciteit en overbevissing, een einde maken aan subsidies die bijdragen tot illegale, niet-aangegeven en ongereguleerde visserij en geen nieuwe vergelijkbare subsidies invoeren, erkennen dat een passende en doeltreffende speciale en gedifferentieerde behandeling van de ontwikkelingslanden en van de minst ontwikkelde landen integraal deel zou moeten uitmaken van de onderhandelingen inzake visserijsubsidies van de Wereldhandelsorganisatie',
    target14_7:'Tegen 2030 de economische voordelen vergroten voor kleine eilandstaten in ontwikkeling en voor de minst ontwikkelde landen van het duurzaam gebruik van mariene rijkdommen, ook via het duurzaam beheer van visserij, aquacultuur en toerisme',
    target14_a:'De wetenschappelijke kennis vergroten, onderzoekscapaciteit ontwikkelen en mariene technologie overdragen, waarbij rekening wordt gehouden met de criteria en richtlijnen van de Intergouvernementele Oceanografische Commissie inzake de overdracht van mariene technologie, om de gezondheid van de oceaan te verbeteren en de bijdrage te verruimen van de mariene biodiversiteit tot de ontwikkeling van ontwikkelingslanden, in het bijzonder kleine eilandstaten in ontwikkeling en de minst ontwikkelde landen',
    target14_b:'Toegang verschaffen aan kleinschalige ambachtelijke vissers tot mariene hulpbronnen en markten',
    target14_c:'Het behoud en het duurzaam gebruik van oceanen en hulpbronnen versterken door het implementeren van internationaal recht zoals dat wordt weerspiegeld in het VN-Zeerechtverdrag, dat een wettelijk kader voorziet voor het behoud en het duurzaam gebruik van oceanen en hun hulpbronnen, zoals ook wordt vermeld in paragraaf 158 van “De toekomst die wij willen”',
    desc15:'“Pas als de laatste boom gestorven is, de laatste rivier vergiftigd en de laatste vis gevangen, zullen we realiseren dat we geen geld kunnen eten.” – Cree Indiaans gezegde. De mens heeft de aarde nodig om te kunnen overleven. Ongeveer 18% van onze voeding is plantaardig en landbouw vormt niet alleen een belangrijke economische hulpbron, maar ook een instrument voor ontwikkeling. Toch zien we vandaag een ongekende landdegradatie en de beschikbare landbouwgrond neemt sneller af dan ooit tevoren. Sinds 2008 lijden al meer dan 1,5 miljard mensen onder de gevolgen van landdegradatie. Om al het leven op het land te beschermen, ontwikkelde de VN de vijftiende Duurzame Ontwikkelingsdoelstelling (SDG 15). SDG 15 richt zich op de verschillende bedreigingen waar onze planeet mee te maken krijgt, zoals ontbossing, verwoestijning, landdegradatie en het verlies aan biodiversiteit.',
    15:'Leven op het land',
    target15_1:'Tegen 2020 het behoud, herstel en het duurzaam gebruik van terrestrische en inlandse zoetwaterecosystemen en hun diensten waarborgen, in het bijzonder bossen, moeraslanden, bergen en droge gebieden, in lijn met de verplichtingen van de internationale overeenkomsten',
    target15_2:'Tegen 2020 de implementatie bevorderen van het duurzaam beheer van alle soorten bossen, de ontbossing een halt toeroepen, verloederde bossen herstellen en op duurzame manier bebossing en herbebossing mondiaal opvoeren',
    target15_3:'Tegen 2030 de woestijnvorming tegengaan, aangetast land en gedegradeerde bodem herstellen, ook land dat wordt aangetast door woestijnvorming, droogte en overstromingen, en streven naar een wereld die qua landdegradatie neutraal is',
    target15_4:'Tegen 2030 het behoud garanderen van de ecosystemen in de bergen, met inbegrip van hun biodiversiteit, om hun vermogen te versterken voordelen te genereren die essentieel zijn voor duurzame ontwikkeling',
    target15_5:'Dringende en doortastende actie ondernemen om de aftakeling in te perken van natuurlijke leefgebieden, het verlies van biodiversiteit een halt toe te roepen en, tegen 2020, de met uitsterven bedreigde soorten te beschermen en hun uitsterven te voorkomen',
    target15_6:'Bevorderen van het eerlijk en billijk verdelen van de voordelen die voortvloeien uit het gebruik van genetische hulpbronnen en bevorderen van gepaste toegang tot dergelijke hulpbronnen, zoals internationaal overeengekomen',
    target15_7:'Dringend actie ondernemen om een einde te maken aan stroperij en de handel in beschermde planten- en diersoorten en zowel de vraag naar als het aanbod van illegale producten afkomstig van deze planten- en diersoorten aan te pakken',
    target15_8:'Tegen 2020 maatregelen invoeren om de invoering van invasieve uitheemse soorten in land- en waterecosystemen te beperken en hun impact op aanzienlijke wijze te beperken, en de prioritaire soorten controleren of uitroeien',
    target15_9:'Tegen 2020 ecosysteem- en biodiversiteitswaarden integreren in nationale en plaatselijke planning, ontwikkelingsprocessen, strategieën en plannen inzake armoedebestrijding',
    target15_a:'Financiële hulpbronnen mobiliseren en aanzienlijk verhogen vanuit allerlei bronnen om de biodiversiteit en de ecosystemen te vrijwaren en op duurzame wijze te gebruiken',
    target15_b:'Aanzienlijke middelen mobiliseren vanuit allerlei bronnen en op alle niveaus om duurzaam bosbeheer te financieren en gepaste stimuli te verschaffen aan ontwikkelingslanden om een dergelijk beheer te organiseren, ook voor behoud en herbebossing',
    target15_c:'De wereldwijde inspanningen ter bestrijding van stroperij en illegale handel in beschermde diersoorten opvoeren, ook door verhoging van de capaciteit van plaatselijke gemeenschappen in hun streven naar kansen inzake een duurzaam bestaan',
    desc16:'Het ultieme doel van de Verenigde Naties is het bewerkstelligen van vreedzame samenlevingen. Helaas moeten we vaststellen dat bepaalde regio`s gekenmerkt blijven door instabiliteit en conflicten. Het doel van de zestiende Duurzame Ontwikkelingsdoelstelling (SDG 16) is om wereldwijd geweld te verminderen, net als het aantal doden dat dit probleem met zich meebrengt. SDG 16 wil een einde maken aan mishandeling, uitbuiting en mensenhandel en alle vormen van geweld en marteling uitroeien. Daarom is het noodzakelijk de bronnen van geweld aan te pakken en de illegale geldstromen, wapenhandel en corruptie tegen 2030 aanzienlijk te verminderen. Dit wordt een enorme uitdaging: volgens een internationaal rapport van 2008 bedraagt de internationale wapenhandel naar schatting meer dan 1200 miljard dollar per jaar.',
    16:'Vrede, justitie en sterke publieke dienesten',
    target16_1:'Alle vormen van geweld en de daaraan gekoppelde sterftecijfers wereldwijd aanzienlijk terugschroeven',
    target16_2:'Een einde maken aan het misbruik, de exploitatie, de handel en van alle vormen van geweld tegen en het martelen van kinderen',
    target16_3:'De rechtsregels bevorderen op nationaal en internationaal niveau en gelijke toegang tot het rechtssysteem voor iedereen garanderen',
    target16_4:'Tegen 2030 ongewettigde financiële en wapenstromen aanzienlijk indijken, het herstel en de teruggave van gestolen goederen versterken en alle vormen van georganiseerde misdaad bestrijden',
    target16_5:'Op duurzame wijze een einde maken aan corruptie en omkoperij in al hun vormen',
    target16_6:'Doeltreffende, verantwoordelijke en transparante instellingen ontwikkelen op alle niveaus',
    target16_7:'Ontvankelijke, inclusieve, participatieve en representatieve besluitvorming op alle niveaus garanderen',
    target16_8:'Verruimen en versterken van de participatie van de ontwikkelingslanden in de instellingen van mondiaal bestuur',
    target16_9:'Tegen 2030 een wettelijke identiteit voorzien voor iedereen, met inbegrip van geboorteregistratie',
    target16_10:'Publieke toegang tot informatie en beschermen van fundamentele vrijheden, volgens de nationale wetgeving en internationale overeenkomsten garanderen',
    target16_a:'Versterken van de relevante nationale instellingen, ook via internationale samenwerking, voor het opbouwen van capaciteit op alle niveaus, in het bijzonder in de ontwikkelingslanden, om geweld te voorkomen en terrorisme en misdaad te bestrijden',
    target16_b:'Bevorderen en afdwingen van niet-discriminerende wetten en beleidslijnen voor duurzame ontwikkeling',
    desc17:'De Duurzame Ontwikkelingsdoelstellingen (SDG) kunnen enkel gerealiseerd worden met een sterk engagement voor internationale partnerschappen en samenwerking. Hoewel de officiële ontwikkelingshulp van de ontwikkelde landen tussen 2000 en 2014 met 66% is gestegen, blijven humanitaire crises door conflicten of natuurrampen financiële middelen en hulp vergen. Verscheidene landen hebben ontwikkelingshulp nodig om de groei en handel te stimuleren. Vandaag is de wereld meer dan ooit onderling verbonden. Een betere toegang tot technologie en kennis is een belangrijke manier om ideeën uit te wisselen en innovatie te bevorderen. Het beleid moet erop gericht zijn om ontwikkelingslanden te helpen met hun schuldbeheer en investeringen in die landen aan te moedigen. Dit is van vitaal belang om duurzame groei en ontwikkeling te bereiken.',
    17:'Partnerschap om doelstellingen te bereiken',
    target17_1:'Versterken van de binnenlandse middelenmobilisatie (DRM), ook via internationale steun aan ontwikkelingslanden, om de binnenlandse capaciteit te verbeteren voor het innen van belastingen en andere inkomsten',
    target17_2:'Ontwikkelde landen dienen ten volle hun verbintenissen aangaande officiële ontwikkelingshulp te implementeren, waaronder ook de verbintenis van vele ontwikkelde landen om 0,7% van het bruto nationaal inkomen te besteden aan officiële ontwikkelingshulp voor ontwikkelingslanden (ODA/GNI) en 0,15% tot 0,20% ontwikkelingshulp aan de minst ontwikkelde landen; ODA-donoren worden aangemoedigd om voor zichzelf een doelstelling te bepalen om minstens 0,2% van de ODA te besteden aan de minst ontwikkelde landen',
    target17_3:'Bijkomende financiële middelen voor ontwikkelingslanden mobiliseren vanuit verschillende bronnen',
    target17_4:'Ontwikkelingslanden bijstaan in hun streven naar schuldhoudbaarheid op lange termijn via gecoördineerde beleidslijnen waarbij aandacht wordt besteed aan het aanmoedigen van de schuldfinanciering, de schuldverlichting en de schuldherstructurering, indien van toepassing, en de externe schuld aanpakken van arme landen met een grote schuldenlast om hun schuldencrisis in te perken',
    target17_5:'Regelingen goedkeuren en uitvoeren die investeringen in de minst ontwikkelde landen moeten bevorderen',
    target17_6:'Versterken van de Noord-Zuid-, de Zuid-Zuid- en de regionale en internationale trilaterale samenwerking inzake wetenschap, technologie en innovatie en vergemakkelijken van de toegang daartoe; en het delen van kennis uitbreiden volgens voorwaarden die wederzijds worden bepaald, ook via de verbeterde coördinatie tussen bestaande mechanismen, in het bijzonder op het niveau van de Verenigde Naties, en via een mondiaal mechanisme voor de facilitering van technologie',
    target17_7:'De ontwikkeling, overdracht, verspreiding en verdeling van ecologische technologieën aan ontwikkelingslanden volgens gunstige voorwaarden, ook inzake gunstige en preferentiële bepalingen, zoals wederzijds overeengekomen',
    target17_8:'De technologiebank en het mechanisme voor het opbouwen van wetenschappelijke, technologische en innoverende capaciteit voor de minst ontwikkelde landen volledig operationeel maken tegen 2017 en het gebruik opdrijven van de technologie die dit mogelijk moet maken, in het bijzonder de informatie- en communicatietechnologie',
    target17_9:'De internationale steun verhogen voor het implementeren van doeltreffende en doelgerichte capaciteitsopbouw in ontwikkelingslanden ter ondersteuning van nationale plannen die erop gericht zijn om alle Duurzame Ontwikkelingsdoelstellingen te implementeren, ook via de Noord-Zuid-, Zuid-Zuid- en trilaterale samenwerking',
    target17_10:' Een universeel, op regels gebaseerd, open, niet-discriminerend en billijk multilateraal handelssysteem bevorderen onder de Wereldhandelsorganisatie, ook via het volbrengen van de onderhandelingen onder de Ontwikkelingsagenda van Doha van deze organisatie',
    target17_11:'De export van ontwikkelingslanden aanzienlijk doen toenemen, in het bijzonder met de bedoeling om het aandeel van de minst ontwikkelde landen in de mondiale export tegen 2020 te verdubbelen',
    target17_12:'Tijdig de implementatie realiseren van belasting- en quotavrije markttoegang op blijvende wijze voor alle minst ontwikkelde landen, in overeenstemming met de beslissingen van de Wereldhandelsorganisatie, ook door ervoor te zorgen dat de voorkeursregels die van oorsprong van toepassing zijn op import van de minst ontwikkelde landen, transparant en eenvoudig zijn, en bijdragen tot het vergemakkelijken van markttoegang',
    target17_13:' De globale macro-economische stabiliteit versterken, ook via beleidscoördinatie en beleidscoherentie',
    target17_14:'Beleidscoherentie voor duurzame ontwikkeling versterken',
    target17_15:'De beleidsruimte en het leiderschap van elke land respecteren om beleidslijnen uit te werken en om duurzame ontwikkeling te implementeren om een einde te maken aan armoede',
    target17_16:'Het Globaal Partnerschap voor duurzame ontwikkeling versterken, aangevuld door partnerschappen met meerdere belanghebbenden (multi-stakeholderpartnerschappen) en kennis, expertise, technologie en financiële hulpmiddelen mobiliseren en delen met het oog op het bereiken van de Duurzame Ontwikkelingsdoelstellingen in alle landen, in het bijzonder in de ontwikkelingslanden',
    target17_17:'Doeltreffende openbare, publiek-private en maatschappelijke partnerschappen aanmoedigen en bevorderen, voortbouwend op de ervaring en het netwerk van partnerschappen',
    target17_18:'Tegen 2020 de steun voor capaciteitsopbouw verhogen aan ontwikkelingslanden, inclusief de minst ontwikkelde landen en de kleine eilandstaten in ontwikkeling, om de beschikbaarheid van hoogwaardige, actuele en betrouwbare gegevens opgedeeld naar inkomen, gender, leeftijd, ras, etnische afkomst, migratiestatus, handicap, geografische locatie en andere kenmerken relevant in een nationale context, aanzienlijk op te drijven',
    target17_19:'Tegen 2030 voortbouwen op bestaande initiatieven om metingen te ontwikkelen met betrekking tot de vooruitgang van duurzame ontwikkeling die kunnen dienen als aanvulling op het bruto binnenlands product, en de statistische capaciteitsopbouw ondersteunen in ontwikkelingslanden',
    // Temporary:
    // Development areas
    Arbeid_sysselsettning:'Werk en werkgelegenheid',
    Bebyggelse:'Gebouwen',
    Digitalisering1:'Digitalisering',
    Energi:'Energie',
    Helse_sosial_og_velferd:'Gezondheid, sociaal en welzijn',
    Kultur:'Cultuur',
    Natur_og_miljø:'Natuur en milieu',
    Næring:'Industrie',
    Oppvekst_og_utdanning:'Opgroeien en onderwijs',
    Styring_og_demokrati:'Bestuur en democratie',
    Transport:'Transport',
    Trygghet_og_beredskap:'Veiligheid en paraatheid',
    Vann_og_søppel:'Water en afval',
    Økonomisk:'Economisch',
    // TBL:
    Miljø:'Milieu',
    Sosialt:'Sociaal',
    Økonomi:'Economie',
    // Perspectives in Trdheim
    Arealer_og_ressursforvaltning:'Gebieden en resourcebeheer',
    Det_grønne_skiftet:'De groene verschuiving',
    Digitalisering2:'Digitalisering',
    Forbruk:'Consumptie',
    Grønn_mobilitet:'Groene mobiliteit',
    Indentitet_og_kultur:'Identiteit en cultuur',
    Inkluderende_samfunn:'Inclusieve samenleving',
    Lokaldemokratiet: 'Lokale democratie',
    Nærmiljø_og_stedsutvikling:'Lokale omgeving en plaatsontwikkeling',
    Oppvekst_og_læring:'Opgroeien en leren',
    P1:'P1',
    Samarbeid_og_verdiskapning:'Samenwerking en waardecreatie',
    Samskapt_velferd:'Mede-gecreëerde welzijn',
    Økonomi1:'Economie',
    // Icons:
    icon_1:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305722539005834067f0/previews/5e3c305822539005834067f4/download/NL-SDG_Icon-RGB-01.png',
    icon_2:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c3058e695b32a098a83ef/previews/5e3c3059e695b32a098a8405/download/NL-SDG_Icon-RGB-02.png',
    icon_3:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305986e72126594c8200/previews/5e3c305986e72126594c820e/download/NL-SDG_Icon-RGB-03.png',
    icon_4:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305a35561d36d0b09848/previews/5e3c305a35561d36d0b0985e/download/NL-SDG_Icon-RGB-04.png',
    icon_5:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c308ff124010aece6e2db/previews/5e3c308ff124010aece6e3ba/download/NL-SDG_Icon-RGB-05.png',
    icon_6:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305c7c9d715606bb13e8/previews/5e3c305c7c9d715606bb140a/download/NL-SDG_Icon-RGB-06.png',
    icon_7:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305daf6de1300293f7fd/previews/5e3c305daf6de1300293f834/download/NL-SDG_Icon-RGB-07.png',
    icon_8:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305da2b2db5a229fc60b/previews/5e3c305ea2b2db5a229fc624/download/NL-SDG_Icon-RGB-08.png',
    icon_9:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305efef84686f8f51494/previews/5e3c305ffef84686f8f514ad/download/NL-SDG_Icon-RGB-09.png',
    icon_10:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c305f1b6d1645fcab7dfa/previews/5e3c30881b6d1645fcab89b0/download/NL-SDG_Icon-RGB-10.png',
    icon_11:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c3088f4142e56c8c78071/previews/5e3c3089f4142e56c8c78091/download/NL-SDG_Icon-RGB-11.png',
    icon_12:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c3089dd4f578c35b0eeec/previews/5e3c308add4f578c35b0eef0/download/NL-SDG_Icon-RGB-12.png',
    icon_13:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c308a15396a14c8622490/previews/5e3c308b15396a14c86225e8/download/NL-SDG_Icon-RGB-13.png',
    icon_14:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c308b79819532df800a66/previews/5e3c308c79819532df800a7f/download/NL-SDG_Icon-RGB-14.png',
    icon_15:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c308cebaa0c4420b0d00c/previews/5e3c308debaa0c4420b0d080/download/NL-SDG_Icon-RGB-15.png',
    icon_16:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c308dcb9ca1873cc71f3e/previews/5e3c308ecb9ca1873cc71f8c/download/NL-SDG_Icon-RGB-16.png',
    icon_17:'https://trello.com/1/cards/5ad951dc29b93798cd129098/attachments/5e3c308ff124010aece6e2db/previews/5e3c308ff124010aece6e3ba/download/NL-SDG_Icon-RGB-17.png',
};