export default {
    bg: 'bulgarsk',
    hr: 'kroatisk',
    cs: 'tsjekkisk', 
    da: 'dansk', 
    nl: 'nederlandsk',
    en: 'engelsk',
    et: 'estisk',
    fi: 'finsk',
    fr: 'fransk',
    de: 'tysk', 
    el: 'gresk',
    hu: 'ungarsk',
    ga: 'irsk', 
    it: 'italiensk',
    lv: 'latvisk',
    lt: 'litauisk',
    mt: 'maltesisk',
    no: 'norsk',
    pl: 'polsk',
    pt: 'portugisisk',
    ro:'rumensk',
    sk: 'slovakisk',
    sl: 'slovensk',
    es: 'spansk',
    sv: 'svensk',
    about: 'Om',
    changeLanguage: 'Bytt språk',
    dataUpload: 'Data opplasting',
    goalDistanceComputation: 'Beregn måldistanse',
    searchDocuments: 'Søk etter dokumenter',
    languagePriority: 'Språk prioritering',
    searchLanguages: 'Søk etter språk',
    multilingual: 'Flerspråklig?',
    openFMX4: 'Åpne som Formex',
    openHTML: 'Åpne som nettside',
    openPDF: 'Åpne som PDF',
    active: 'Aktiv',
    seeRelatedGoals: 'Se relaterte mål',

};