// https://www.fn.no/om-fn/fns-baerekraftsmaal
export default {
    bg: 'bulgarsk',
    hr: 'kroatisk',
    cs: 'tsjekkisk', 
    da: 'dansk', 
    nl: 'nederlandsk',
    en: 'engelsk',
    et: 'estisk',
    fi: 'finsk',
    fr: 'fransk',
    de: 'tysk', 
    el: 'gresk',
    hu: 'ungarsk',
    ga: 'irsk', 
    it: 'italiensk',
    lv: 'latvisk',
    lt: 'litauisk',
    mt: 'maltesisk',
    no: 'norsk',
    pl: 'polsk',
    pt: 'portugisisk',
    ro:'rumensk',
    sk: 'slovakisk',
    sl: 'slovensk',
    es: 'spansk',
    sv: 'svensk',
    NoDocuments:'Beklager, det finnes ingen dokumenter på noen av dine valgte språk',
    About: 'Om',
    Home: 'Hjem',
    Close: 'Lukk',
    GoTo: 'Gå til',
    TheRelation: 'Relasjonen',
    hasDevelopmentArea: 'harUtviklingsområde',
    hasTradeoffTo: 'harTradeOffTil',
    hasContributionTo: 'harBidragTil',
    Correlation:'Korrelasjon',
    Contribution:'Bidrag',
    TradeOff: 'TradeOff',
    To:'Til',
    DevelopmentAreaCamel:'Utviklingsområde',
    For:'For',
    isA: 'er en',
    binaryPositiveRelation: 'binær relasjon som beskriver at en klasse/instanse har en positiv påvirkning til en annen klasse/instanse. Styrken til denne relasjonen er ikke definert, hvor en sammenheng mellom to klasser/instanser hvor bare "harBidragTil" er definert, vil si at mengden bidrag er udefinert. Se henholdsvis "har(Høy/Moderat/Lav) - KorrelasjonTil" - under relasjonene av harBidragTil for mer veldefinerte positive påvirkninger.',   
    ShowTargets: 'Vis undermål',
    developmentAreaRelation: 'binær relasjon for konsepter som har utviklingsområder. I henhold til SSBs taxonomy er et utviklingsområde definert inn under perspektiver. Hvor et utviklingsområde er et konsept som ønskes å forbedres. For eksempel konseptene: Økonomi og Natur.',
    binaryNegativeRelation: 'binær relasjon som beskriver at en klasse/instanse har en negativ påvirkning til en annen klasse/instanse. Styrken til denne relasjonen er ikke definert, hvor en sammenheng mellom to klasser/instanser hvor bare "harBidragTil" er definert, vil si at mengden bidrag er udefinert. Se henholdsvis "har(Høy/Moderat/Lav) - KorrelasjonTil" - under relasjonene av harBidragTil for mer veldefinerte positive påvirkninger.',
    UknownMunicipality: 'Ukjent kommune',
    Loading: 'Laster',
    BackToHomePage: 'Tilbake til hjemsiden',
    Fullscreen: 'Fullskjerm',
    StandardColor: 'Standardfarge/startnode',
    Targets: 'Delmål',
    Target: 'Delmål',
    Tbl: 'Trippel bunnlinje',
    DevelopmentArea: 'Utviklingsområde',
    ShowEdgeLabels: 'Vis kanttekst',
    NameMissing: 'Mangler navn',
    HasPositiveEffectOn: 'Har en positiv virkning på',
    HasNoEstablishedPositiveContributions: 'Har ingen etablerte positive påvirkninger enda',
    HasNegativeEffectOn: 'Har en negativ virkning på',
    HasNoEstablishedNegativeContributions: 'Har ingen etablerte negative påvirkninger enda',
    HasDevelopmentAreasFor: 'Har utviklingsområder for',
    HasNoDevelopmentAreas: 'Har ingen utviklingsområder',
    has: 'har',
    aHigh: 'en høy',
    High: 'Høy',
    Low: 'Lav',
    Moderate: 'Moderat',
    aModerate: 'en moderat',
    aLow: 'en lav',
    to: 'til',
    on: 'på',
    UnlockNodes: 'Lås opp noder',
    Sdg:'Bærekraftsmål',
    positiveEffect: 'positiv virkning',
    negativeEffect: 'negativ virkning',
    ConceptUnderDevelopment: 'Dette konseptet er under utvikling',
    ChangeLanguage: 'Bytt språk',
    effects: 'virkninger',
    PositivePlural: 'Positive',
    NegativePlural: 'Negative',
    DataUpload: 'Data opplasting',
    ShowDocuments: 'Vis dokumenter',
    Documents: 'Dokumenter',
    ToTop: 'Til toppen',
    SeeMoreDocuments: 'Se flere',
    YourSearchReturned: 'Søket ditt ga',
    results: 'resultater',
    Show: 'Vis',
    GoalDistanceComputation: 'Beregn måldistanse',
    SearchDocuments: 'Søk etter dokumenter',
    LanguagePriority: 'Språk prioritering',
    SearchLanguages: 'Søk etter språk',
    Multilingual: 'Flerspråklig',
    MoreInfo: 'Mer informasjon finnes her',
    OpenAs: 'Åpne som',
    Active: 'Aktiv',
    SeeRelatedGoals: 'Se relaterte mål',
    Sdgs: 'Bærekraftsmålene',
    SdgOntology: 'Bærekraftsontologien',
    Search: 'Søk',
    desc1: 'Bærekraftsmål 1 har som mål å utrydde ekstrem fattigdom og halvere andelen mennesker som lever i relativ fattigdom. Koronapandemien har ført til at andelen fattige i verden har økt for første gang siden 1998. Flere har blitt fattigere, og i Norge har også flere fått dårligere råd. Men andelen mennesker som lever i ekstrem fattigdom er mindre i dag enn den var i 1990.',
    1: 'Utrydde fattigdom',
    target1_1: 'Innen 2030 utrydde all ekstrem fattigdom',
    target1_2: 'Innen 2030 minst halvere andelen menn, kvinner og barn i alle aldre som lever i fattigdom, i henhold til nasjonale definisjoner',
    target1_3: 'Innføre nasjonalt tilpassede sosiale velferdsordninger og tiltak for alle, inkludert minstestandarder, og innen 2030 oppnå en vesentlig dekning av fattige og sårbare',
    target1_4: 'Innen 2030 sikre at alle menn og kvinner, særlig fattige og sårbare, har lik rett til økonomiske ressurser og tilgang til grunnleggende tjenester, til å eie og kontrollere jord og andre former for eiendom, og til arv, naturressurser, ny teknologi og finansielle tjenester, inkludert mikrofinansiering',
    target1_5: 'Innen 2030 bygge opp motstandskraften til fattige og personer i utsatte situasjoner, slik at de blir mindre utsatt for og mindre sårbare for klimarelaterte ekstremhendelser og andre økonomiske, sosiale og miljømessige påkjenninger og katastrofer',
    target1_a: 'Sikre en betydelig mobilisering av ressurser fra ulike kilder, blant annet gjennom økt utviklingssamarbeid, for å gi utviklingslandene, s&aelig;rlig de minst utviklede landene, tilstrekkelige og forutsigbare midler til å gjennomføre programmer og politikk for å utrydde alle former for fattigdom',
    target1_b: 'Opprette gode politiske rammeverk på nasjonalt, regionalt og internasjonalt nivå basert på utviklingsstrategier som gagner de fattige og ivaretar kjønnsperspektivet, med sikte på å øke investeringer i tiltak som bekjemper fattigdom',
    desc2: 'Målet handler om at alle mennesker skal ha tilgang på næringsrik og bærekraftig mat hele året, og at ingen skal sulte. Det å få i seg nok mat til å leve et godt liv er en menneskerettighet. Likevel er det mange som sulter i verden. Etter tiår med nedgang, stiger nå tallene for antall mennesker som sulter.',
    2: 'Utrydde sult',
    target2_1:'Innen 2030 utrydde sult og sikre alle mennesker, særlig fattige og personer i utsatte situasjoner, inkludert spedbarn, tilgang til nok, trygg og sunn mat hele året',
    target2_2: 'Innen 2030 utrydde alle former for feilernæring, og innen 2025 nå de internasjonalt avtalte målene som omhandler veksthemming og avmagring hos barn under fem år, og ivareta ernæringsbehovene til unge jenter, gravide, ammende kvinner og eldre personer',
    target2_3: 'Innen 2030 doble produktiviteten og inntektene til småskala matprodusenter, særlig kvinner, urfolk, familiebruk, husdyrnomader og fiskere, blant annet gjennom sikker og lik tilgang til jord, andre produksjonsressurser og innsatsmidler, kunnskap, finansielle tjenester, markeder og muligheter for verdiøkning og for sysselsetting utenfor landbruket',
    target2_4: 'Innen 2030 sikre at det finnes bærekraftige systemer for matproduksjon, og innføre robuste metoder som gir økt produktivitet og produksjon, som bidrar til å opprettholde økosystemene, som styrker evnen til tilpasning til klimaendringer, ekstremvær, tørke, oversvømmelse og andre katastrofer, og som gradvis bedrer arealenes og jordas kvalitet',
    target2_5: 'Innen 2020 opprettholde det genetiske mangfoldet av frø, kulturplanter, husdyr og beslektede ville arter, blant annet gjennom veldrevne og rikholdige frø- og plantesamlinger nasjonalt, regionalt og internasjonalt, og fremme tilgang til og en rettferdig og likeverdig fordeling av de goder som følger av bruk av genressurser og tilhørende tradisjonell kunnskap, i tråd med internasjonal enighet',
    target2_a: 'Blant annet gjennom bedre internasjonalt samarbeid øke investeringene i infrastruktur på landsbygda, i forskning og veiledningstjenester innenfor landbruket, i teknologiutvikling og i genbanker for planter og husdyr, med sikte på å forbedre produksjonskapasiteten i landbruket i utviklingsland, særlig i de minst utviklede landene',
    target2_b: 'Korrigere og hindre handelsrestriksjoner og vridninger på verdens landbruksmarkeder, blant annet gjennom en parallell avvikling av alle former for eksportsubsidier på landbruksvarer og alle eksporttiltak med tilsvarende effekt, i samsvar med mandatet for Doha-runden',
    target2_c: 'Vedta tiltak for å sikre at råvare- og derivatmarkedene for matvarer er velfungerende og legge til rette for rask tilgang til markedsinformasjon, blant annet om matreserver, for å begrense ekstreme svingninger i matvareprisene',
    desc3: 'God helse er en grunnleggende forutsetning for menneskers mulighet til å nå sitt fulle potensial og for å bidra til utvikling i samfunnet. Hvordan helsen vår er, påvirkes av miljø, økonomi og sosiale forhold og mål 3 inkluderer mennesker i alle aldre og ivaretar alle dimensjonene.',
    3: 'God helse og livskvalitet',
    target3_1: 'Innen 2030 redusere mødredødeligheten i verden til under 70 per 100 000 levendefødte',
    target3_2: 'Innen 2030 få slutt på dødsfall som kan forhindres blant nyfødte og barn under fem år, med et felles mål for alle land om å redusere dødeligheten blant nyfødte til høyst 12 per 1 000 levendefødte og til høyst 25 per 1 000 levendefødte blant barn under fem år',
    target3_3: 'Innen 2030 stanse epidemiene av aids, tuberkulose, malaria og neglisjerte tropiske sykdommer, og bekjempe hepatitt, vannbårne sykdommer og andre smittsomme sykdommer',
    target3_4: 'Innen 2030 stanse epidemiene av aids, tuberkulose, malaria og neglisjerte tropiske sykdommer, og bekjempe hepatitt, vannbårne sykdommer og andre smittsomme sykdommer',
    target3_5: 'Styrke forebygging og behandling av rusmiddelmisbruk, blant annet misbruk av narkotiske stoffer og skadelig bruk av alkohol',
    target3_6: 'Innen 2020 halvere antall dødsfall og skader i verden forårsaket av trafikkulykker',
    target3_7: 'Innen 2030 sikre allmenn tilgang til tjenester knyttet til seksuell og reproduktiv helse, inkludert familieplanlegging og tilhørende informasjon og opplæring, og sikre at reproduktiv helse innarbeides i nasjonale strategier og programmer',
    target3_8: 'Oppnå allmenn dekning av helsetjenester, inkludert ordninger som beskytter mot økonomiske konsekvenser, og allmenn tilgang til grunnleggende og gode helsetjenester og trygge, virksomme og nødvendige medisiner og vaksiner av god kvalitet og til en overkommelig pris',
    target3_9: 'Innen 2030 betydelig redusere antall dødsfall og sykdomstilfeller forårsaket av farlige kjemikalier og forurenset luft, vann og jord',
    target3_a: 'Styrke gjennomføringen av Verdens helseorganisasjons rammekonvensjon om forebygging av tobakksskader i alle land',
    target3_b: 'Støtte forskning på og utvikling av vaksiner og medisiner mot smittsomme og ikke-smittsomme sykdommer som primært rammer utviklingsland, sørge for tilgang til nødvendige medisiner og vaksiner til en overkommelig pris, i samsvar med Doha-erklæringen om TRIPS-avtalen og folkehelse, som bekrefter utviklingslandenes rett til fullt ut å anvende bestemmelsene som gjelder adgangen til å verne om folkehelsen og særlig sørge for tilgang til medisiner for alle, i avtalen om handelsrelaterte aspekter ved immaterielle rettigheter',
    target3_c: 'Oppnå betydelig økt finansiering av helsetjenester og rekruttering, utvikling og opplæring av helsepersonell i utviklingsland, særlig i de minst utviklede landene og små utviklingsøystater, og arbeide for at slikt personell blir værende i landene',
    target3_d: 'Styrke kapasiteten i alle land, særlig i utviklingsland, for tidligvarsling, risikoredusering og håndtering av nasjonale og globale helserisikoer',
    desc4: 'Utdanning er en grunnleggende menneskerettighet, og  veldig mange flere går i dag på skole enn for bare få tiår siden. Før koronapandemien, gikk ni av ti barn på skolen. Til tross for dette, kan fremdeles over 750 millioner mennesker i verden fortsatt ikke lese eller skrive, hvorav to tredjedeler er kvinner. Inkluderende opplæring av god kvalitet for alle, er en  av de viktigste byggesteinene for velstand, helse og likeverd i alle samfunn.',
    4: 'God utdanning',
    target4_1: 'Innen 2030 sikre at alle jenter og gutter fullfører gratis og likeverdig grunnskole og videregående opplæring av høy kvalitet som kan gi dem et relevant og reelt læringsutbytte',
    target4_2: 'Innen 2030 sikre alle jenter og gutter mulighet for god tidlig utvikling og omsorg og tilgang til førskole, slik at de er forberedt på å begynne i grunnskolen',
    target4_3: 'Innen 2030 sikre kvinner og menn lik tilgang til god teknisk og yrkesfaglig opplæring og høyere utdanning, inkludert universitetsutdanning, til en overkommelig pris',
    target4_4: 'Innen 2030 oppnå en betydelig økning i antall unge og voksne som har kompetanse, blant annet i tekniske fag og yrkesfag, som er relevant for sysselsetting, anstendig arbeid og entreprenørskap',
    target4_5: 'Innen 2030 avskaffe kjønnsforskjeller i utdanning og opplæring og sikre lik tilgang til alle nivåer innenfor utdanning og yrkesfaglig opplæring for sårbare grupper, inkludert personer med nedsatt funksjonsevne, urfolk og barn i utsatte situasjoner',
    target4_6: 'Innen 2030 sikre at all ungdom og en betydelig andel voksne, både kvinner og menn, lærer å lese, skrive og regne',
    target4_7: 'Innen 2030 sikre at alle elever og studenter tilegner seg den kompetansen som er nødvendig for å fremme bærekraftig utvikling, blant annet gjennom utdanning i bærekraftig utvikling og livsstil, menneskerettigheter, likestilling, fremme av freds- og ikkevoldskultur, globalt borgerskap og verdsetting av kulturelt mangfold og kulturens bidrag til bærekraftig utvikling',
    target4_a: 'Etablere og oppgradere utdanningstilbud som er barnevennlige, og som ivaretar hensynet til kjønnsforskjeller og til personer med nedsatt funksjonsevne og sikrer trygge, ikke-voldelige, inkluderende og effektive læringsmiljø for alle',
    target4_b: 'Innen 2020 oppnå en vesentlig økning globalt i antall stipender som er tilgjengelige for studenter fra utviklingsland, særlig de minst utviklede landene, små utviklingsøystater og afrikanske land, for å gi dem tilgang til høyere utdanning, blant annet yrkesfaglig opplæring og programmer for informasjons- og kommunikasjonsteknologi, teknikk, ingeniørfag og vitenskap, både i andre utviklingsland og i utviklede land',
    target4_c: 'Innen 2030 oppnå en vesentlig økning i antall kvalifiserte lærere, blant annet gjennom internasjonalt samarbeid om lærerutdanning i utviklingsland, særlig i de minst utviklede landene og i små utviklingsøystater',
    desc5: 'Verden er langt mer likestilt enn for få tiår siden. Andelen kvinner som deltar i politikk og næringsliv øker, men det er fremdeles langt flere menn enn kvinner i maktposisjoner. Fattigdom er ofte tett knyttet til diskriminerende lover og sosiale normer som fører til at kvinner får dårligere økonomi og færre muligheter til å bestemme over egne liv. Mange kvinner er økonomisk avhengig av partneren sin, noe som fører til en skeiv maktbalanse i hjemmet og i samfunnet.',
    5: 'Likestilling mellom kjønnene',
    target5_1: 'Få slutt på alle former for diskriminering av jenter og kvinner i hele verden',
    target5_2: 'Avskaffe alle former for vold mot alle jenter og kvinner både i offentlig og privat sfære, inkludert menneskehandel, seksuell utnytting og andre former for utnytting',
    target5_3: 'Avskaffe all skadelig praksis, som barneekteskap, tidlige ekteskap og tvangsekteskap, og kjønnslemlestelse',
    target5_4: 'Anerkjenne og verdsette ubetalt omsorgs- og husholdsarbeid gjennom offentlige tjenester, infrastruktur og sosialpolitikk, og fremme delt ansvar i husholdet og familien, alt etter hva som passer i det enkelte land',
    target5_5: 'Sikre kvinner fullstendig og reell deltakelse og like muligheter til ledende stillinger på alle nivåer der beslutninger tas, i det politiske, det økonomiske og det offentlige liv',
    target5_6: 'Sikre tilgang til god seksuell og reproduktiv helse og reproduktive rettigheter for alle, i samsvar med handlingsprogrammet fra den internasjonale konferansen om befolkning og utvikling, handlingsplanen fra Beijing og sluttdokumentene fra deres respektive tilsynskonferanser',
    target5_a: 'Iverksette reformer for å gi kvinner lik rett til økonomiske ressurser, mulighet til å eie og kontrollere jord og andre former for eiendom samt tilgang til finansielle tjenester, arv og naturressurser, i samsvar med nasjonal lovgivning',
    target5_b: 'Styrke bruken av muliggjørende teknologi, særlig informasjons- og kommunikasjonsteknologi, for å styrke kvinners stilling i samfunnet',
    target5_c: 'Vedta og styrke god politikk og vedta gjennomførbar lovgivning for å fremme likestilling og styrke jenters og kvinners stilling på alle nivåer i samfunnet',
    desc6: 'Rent vann er kanskje den viktigste forutsetningen for god helse. Hele 1 av 4 personer i verden har ikke tilgang til trygge drikkevannskilder. Enda flere mangler toalett og ordentlige sanitære forhold. Ikke bare er det nedverdigende og ubehagelig å ikke ha mulighet til å gå på do, men det er også stor sjanse for spredning av farlige sykdommer når man ikke har mulighet til å ivareta god hygiene.',
    6: 'Rent vann og gode sanitærforhold',
    target6_1: 'Innen 2030 sørge for likeverdig tilgang til trygt drikkevann til en overkommelig pris for alle',
    target6_2: 'Innen 2030 sørge for tilgang til tilstrekkelige og likeverdige sanitær-, hygiene- og toalettforhold for alle, med særlig vekt på behovene til jenter og kvinner og personer i utsatte situasjoner',
    target6_3: 'Innen 2030 sørge for bedre vannkvalitet ved å redusere forurensning, avskaffe avfallsdumping og mest mulig begrense utslipp av farlige kjemikalier og materialer, halvere andelen ubehandlet spillvann og i vesentlig grad øke gjenvinning og trygg ombruk på verdensbasis',
    target6_4: 'Innen 2030 betydelig bedre utnyttelsen av vann i alle sektorer og sikre bærekraftig uttak av og tilgang til ferskvann for å avhjelpe vannmangel og i vesentlig grad redusere antall personer som rammes av vannmangel',
    target6_5: 'Innen 2030 innføre en integrert forvaltning av vannressurser på alle nivåer, blant annet gjennom samarbeid over landegrensene der det er aktuelt',
    target6_6: 'Innen 2020 verne og gjenopprette vannrelaterte økosystemer, inkludert fjell, skoger, våtmarker, elver, vannførende bergarter og innsjøer',
    target6_a: 'Innen 2030 utvide det internasjonale samarbeidet og støtten til å bygge opp kapasitet i utviklingsland innenfor virksomhet og programmer knyttet til vann- og sanitærforhold, blant annet teknologi for vannoppsamling, avsalting, effektiv bruk av vannressurser, behandling av avløpsvann, gjenvinning og ombruk',
    target6_b: 'Støtte og styrke lokalsamfunnenes medvirkning for å bedre forvaltningen av vann- og sanitærforhold',
    desc7: 'Bærekraftsmål 7 handler om at alle mennesker skal ha tilgang til energi. Energien skal være pålitelig, bærekraftig, moderne, og ikke altfor dyr.',
    7: 'Ren energi til alle',
    target7_1: 'Innen 2030 sikre allmenn tilgang til pålitelige og moderne energitjenester til en overkommelig pris',
    target7_2: 'Innen 2030 øke andelen fornybar energi i verdens samlede energiforbruk betydelig',
    target7_3: 'Innen 2030 få forbedringen av energieffektivitet på verdensbasis til å gå dobbelt så fort',
    target7_a: 'Innen 2030 styrke det internasjonale samarbeidet for å lette tilgangen til forskning og teknologi på området ren energi, inkludert fornybar energi, energieffektivisering og avansert og renere teknologi for fossilt brensel, og fremme investeringer i energiinfrastruktur og teknologi for ren energi',
    target7_b: 'Innen 2030 bygge ut infrastruktur og oppgradere teknologi for å tilby moderne og bærekraftige energitjenester til alle innbyggere i utviklingsland, særlig i de minst utviklede landene, små utviklingsøystater og kystløse utviklingsland, i samsvar med landenes respektive støtteprogram',
    desc8: 'Omtrent halvparten av verdens befolkning tjener så dårlig at ikke de kan leve av lønnen sin. Å skape arbeidsplasser av god kvalitet er en stor utfordring for alle land fram mot 2030.',
    8: 'Anstendig arbeid og økonomisk vekst',
    target8_1: 'Opprettholde en økonomisk vekst per innbygger som er i samsvar med forholdene i de respektive landene, og spesielt en vekst i bruttonasjonalproduktet på minst 7 prosent per år i de minst utviklede landene',
    target8_2: 'Øke den økonomiske produktiviteten gjennom diversifisering, teknologisk fremgang og innovasjon, blant annet med vekt på lønnsomme og arbeidsintensive sektorer',
    target8_3: 'Fremme en utviklingsrettet politikk som støtter produktive aktiviteter, opprettelse av anstendige arbeidsplasser, entreprenørskap, kreativitet og innovasjon, og stimulere til formalisering av og vekst i antallet svært små, små og mellomstore bedrifter, blant annet ved å gi dem tilgang til finansielle tjenester',
    target8_4: 'Til og med 2030 gradvis å bedre utnyttelsen av globale ressurser innenfor forbruk og produksjon, og arbeide for å oppheve koblingen mellom ;  økonomisk vekst og miljøødeleggelser, i samsvar med det tiårige handlingsprogrammet for bærekraftig forbruk og produksjon, der de utviklede landene går foran',
    target8_5: 'Innen 2030 oppnå full og produktiv sysselsetting og anstendig arbeid for alle kvinner og menn, inkludert ungdom og personer med nedsatt funksjonsevne, og oppnå lik lønn for likt arbeid',
    target8_6: 'Innen 2020 betydelig redusere andelen unge som verken er i arbeid, under utdanning eller opplæring',
    target8_7: 'Iverksette umiddelbare og effektive tiltak for å avskaffe tvangsarbeid, få slutt på moderne slaveri og menneskehandel og sikre at de verste formene for barnearbeid inkludert rekruttering og bruk av barnesoldater forbys og avskaffes, og innen 2025 avskaffe alle former for barnearbeid',
    target8_8: 'Beskytte arbeiderrettigheter og fremme et trygt og sikkert arbeidsmiljø for alle arbeidstakere, inkludert arbeidsinnvandrere og særlig kvinnelige innvandrere, og arbeidstakere i et usikkert arbeidsforhold',
    target8_9: 'Innen 2030 utarbeide og iverksette politikk for å fremme en bærekraftig turistnæring som skaper arbeidsplasser og fremmer lokal kultur og lokale produkter',
    target8_10: 'Styrke nasjonale finansinstitusjoners evne til å utvide tilgangen til og stimulere til bruk av bank- og forsikringstjenester og finansielle tjenester for alle',
    target8_a: 'Øke støtten til handelsrettet bistand («Aid for Trade») til utviklingsland, særlig til de minst utviklede landene, blant annet gjennom det styrkede, integrerte rammeverket for handelsrelatert faglig bistand til de minst utviklede landene (EIF)',
    target8_b: 'Innen 2020 utvikle og iverksette en global strategi for sysselsetting av ungdom og innføre «The Global Jobs Pact» utviklet i Den internasjonale arbeidsorganisasjonen (ILO)',
    desc9: 'Infrastruktur er den underliggende strukturen som må være på plass for at et samfunn skal fungere. Investeringer i transport, vanningssystemer, energi og informasjonsteknologi må på plass for å få til bærekraftig utvikling.',
    9: 'Industri, innovasjon og infrastruktur',
    target9_1: 'Utvikle pålitelig, bærekraftig og solid infrastruktur av høy kvalitet, inkludert regional og grensekryssende infrastruktur,    for å støtte økonomisk utvikling og livskvalitet med vekt på overkommelig pris og likeverdig tilgang for alle',
    target9_2: 'Fremme inkluderende og bærekraftig industrialisering og næringsutvikling, og innen 2030 øke industriens andel av sysselsetting og bruttonasjonalprodukt betydelig, i tråd med forholdene i de respektive landene, og doble industriens andel av sysselsetting og bruttonasjonalprodukt i de minst utviklede landene',
    target9_3: 'Øke tilgangen til finansielle tjenester, inkludert rimelig kreditt, for små industribedrifter og andre bedrifter, særlig i utviklingsland, og styrke disse bedriftenes posisjon og integrere dem i verdikjeder og markeder',
    target9_4: 'Innen 2030 oppgradere infrastruktur og omstille næringslivet til å bli mer bærekraftig, med mer effektiv bruk av ressurser og mer utstrakt bruk av rene og miljøvennlige teknologiformer og industriprosesser, der alle land gjør en innsats etter egen evne og kapasitet',
    target9_5: 'Styrke vitenskapelig forskning og oppgradere teknologien i næringslivssektorene i alle land, særlig i utviklingsland,  blant annet ved &ndash;innen 2030 å stimulere til innovasjon, betydelig øke antallet ansatte (per million innbyggere) innenfor forsknings- og utviklingsvirksomhet og betydelig øke bevilgningene til offentlig og privat forskning og utvikling',
    target9_a: 'Legge til rette for bærekraftig utvikling av infrastrukturen i utviklingsland ved å øke den finansielle, teknologiske og faglige bistanden til afrikanske land, de minst utviklede landene, kystløse utviklingsland og små utviklingsøystater',
    target9_b: 'Støtte nasjonal utvikling av teknologi, forskning og innovasjon i utviklingsland, blant annet ved å sikre politiske rammevilkår som fremmer mangfold i næringslivet og gir handelsvarer en merverdi',
    target9_c: 'Øke tilgangen til informasjons- og kommunikasjonsteknologi betydelig og arbeide for at de minst utviklede landene får allmenn og rimelig tilgang til internett innen 2020',
    desc10: 'Før pandemien gikk flere mål på ulikhet i riktig retning. Økonomisk vekst har bidratt til at flere land har blitt rikere, men ikke automatisk ført til mindre fattigdom. Pandemien har forverret eksisterende ulikhet mellom og i land, spesielt blant de fattigste.',
    10: 'Mindre ulikhet',
    target10_1: 'Innen 2030 oppnå en gradvis og varig inntektsøkning for de fattigste 40 prosentene av befolkningen som er raskere enn økningen for det nasjonale gjennomsnittet',
    target10_2: 'Innen 2030 sikre myndiggjøring og fremme sosial, økonomisk og politisk inkludering av alle, uavhengig av alder, kjønn, funksjonsevne, rase, etnisitet, nasjonal opprinnelse, religion eller økonomisk eller annen status',
    target10_3: 'Sikre like muligheter og redusere forskjeller i levekår, blant annet ved å avskaffe diskriminerende lover, politikk og praksis og ved å fremme lovgivning, politikk og tiltak som er egnet til å nå dette målet',
    target10_4: 'Vedta politikk, særlig når det gjelder skatter og avgifter, lønn og sosialomsorg, med sikte på å oppnå en gradvis utjevning av forskjeller',
    target10_5: 'Bedre reguleringen av og tilsynet med globale finansmarkeder og finansinstitusjoner, og styrke gjennomføringen av regelverket',
    target10_6: 'Sikre at utviklingslandene blir bedre representert og får større grad av medbestemmelse i beslutningsprosessene i globale finansinstitusjoner, slik at institusjonene fungerer bedre og blir mer pålitelige, ansvarlige og legitime',
    target10_7: 'Legge til rette for migrasjon og mobilitet i ordnede, trygge, regulerte og ansvarlige former, blant annet ved å føre en planmessig og godt forvaltet migrasjonspolitikk',
    target10_a: 'Gjennomføre prinsippet om særbehandling og differensiert behandling av utviklingsland, særlig de minst utviklede landene, i samsvar med avtaler inngått med Verdens handelsorganisasjon',
    target10_b: 'Stimulere til offentlig utviklingsbistand og kapitalflyt, blant annet direkte utenlandske investeringer, til statene der behovet er størst, særlig de minst utviklede landene, afrikanske land, små utviklingsøystater og kystløse utviklingsland, i samsvar med landenes egne planer og programmer',
    target10_c: 'Innen 2030 redusere transaksjonsgebyrene til under 3 prosent ved pengeoverføringer fra migranter til hjemlandet og avskaffe overføringsordninger med gebyrer som overstiger 5 prosent',
    desc11: 'Mer enn halvparten av verdens befolkning bor i dag i byer, og andelen kommer trolig til å øke til 60 prosent i 2030. Byene fungerer som møteplasser for handel, kultur, innovasjon og sosial samhandling. Samtidig står byene for 75 prosent av alle klimagassutslipp og slumområder hindrer gode levekår.',
    11: 'Bærekraftige byer og lokalsamfunn',
    target11_1: 'Innen 2030 sikre at alle har tilgang til tilfredsstillende og trygge boliger og grunnleggende tjenester til en overkommelig pris, og bedre forholdene i slumområder',
    target11_2: 'Innen 2030 sørge for at alle har tilgang til trygge, tilgjengelige og bærekraftige transportsystemer til en overkommelig pris og bedre sikkerheten på veiene, særlig ved å legge til rette for kollektivtransport og med særlig vekt på behovene til personer i utsatte situasjoner, kvinner, barn, personer med nedsatt funksjonsevne og eldre',
    target11_3: 'Innen 2030 styrke inkluderende og bærekraftig urbanisering og muligheten for en deltakende, integrert og bærekraftig samfunnsplanlegging og forvaltning i alle land',
    target11_4: 'Styrke innsatsen for å verne og sikre verdens kultur- og naturarv',
    target11_5: 'Innen 2030 oppnå en betydelig reduksjon i antall dødsfall og antall personer som rammes av katastrofer, inkludert vannrelaterte katastrofer, og i betydelig grad minske de direkte økonomiske tapene i verdens samlede bruttonasjonalprodukt som følge av slike katastrofer, med vekt på å beskytte fattige og personer i utsatte situasjoner',
    target11_6: 'Innen 2030 redusere byenes og lokalsamfunnenes negative påvirkning på miljøet (målt per innbygger), med særlig vekt på luftkvalitet og avfallshåndtering i offentlig eller privat regi',
    target11_7: 'Innen 2030 sørge for at alle, særlig kvinner og barn, eldre og personer med nedsatt funksjonsevne, har tilgang til trygge, inkluderende og tilgjengelige grøntområder og offentlige rom',
    target11_a: 'Støtte positive økonomiske, sosiale og miljømessige forbindelser mellom byområder, omland og spredtbygde områder ved  å styrke nasjonale og regionale planer',
    target11_b: 'Innen 2020 oppnå en betydelig økning i antall byer og lokalsamfunn som vedtar en integrert politikk og gjennomfører planer med  sikte  på inkludering, bedre ressursbruk, begrensning av og tilpasning til klimaendringer samt evne til å stå imot og håndtere katastrofer, og dessuten utvikle og iverksette et helhetlig system for risikostyring og katastrofehåndtering på alle nivå, i tråd med Sendai-rammeverket for katastrofeberedskap for 2015-2030',
    target11_c: 'Bistå de minst utviklede landene med å oppføre bærekraftige og solide bygg ved bruk av lokale materialer, blant annet   gjennom  økonomisk og faglig bistand',
    desc12: 'Bærekraftig forbruk og produksjon handler om å gjøre mer med mindre ressurser. I dag forbruker vi mye mer enn hva som er bærekraftig for kloden. For eksempel går en tredjedel av maten som blir produsert bort, uten å bli spist.',
    12: 'Ansvarlig forbruk og produksjon',
    target12_1: 'Gjennomføre det tiårige handlingsprogrammet for bærekraftig forbruk og produksjon ved at alle land deltar, men slik at de utviklede landene går foran, samtidig som det tas hensyn til utviklingslandenes utviklingsnivå og muligheter',
    target12_2: 'Innen 2030 oppnå bærekraftig forvaltning og effektiv bruk av naturressurser',
    target12_3: 'Innen 2030 halvere matsvinn per innbygger på verdensbasis, både i detaljhandelen og blant forbrukere, og redusere svinn i produksjons- og forsyningskjeden, inkludert svinn etter innhøsting',
    target12_4: 'Innen 2020 oppnå en mer miljøvennlig forvaltning av kjemikalier og alle former for avfall gjennom hele livssyklusen, i samsvar med internasjonalt vedtatte rammeverk, og betydelig redusere utslipp av kjemikalier og avfall til luft, vann og jord for mest mulig å begrense skadevirkningene for folkehelsen og for miljøet',
    target12_5: 'Innen 2030 redusere avfallsmengden betydelig gjennom forebygging, reduksjon, materialgjenvinning og ombruk',
    target12_6: 'Stimulere selskaper, særlig store og flernasjonale selskaper, til å ta i bruk bærekraftige metoder og integrere informasjon om egen  bærekraft i sine rapporteringsrutiner',
    target12_7: 'Fremme bærekraftige ordninger for offentlige anskaffelser, i samsvar med de enkelte landenes politikk og prioriteringer',
    target12_8: 'Innen 2030 sikre at alle mennesker i hele verden har relevant informasjon om og forståelse av bærekraftig utvikling og et levesett som er i harmoni med naturen',
    target12_a: 'Støtte utviklingslandene i å styrke deres vitenskapelige og tekniske kapasitet til å innføre mer bærekraftige forbruks- og produksjonsmønstre',
    target12_b: 'Utvikle og innføre metoder for å måle effekten av bærekraftig reiseliv som skaper arbeidsplasser og fremmer lokal kultur og lokale produkter',
    target12_c: 'Redusere ineffektive subsidier til fossilt brensel ved å fjerne markedsvridninger som oppmuntrer til overforbruk, i samsvar med nasjonale forhold, blant annet ved å legge om skatter og avgifter og avvikle skadelige subsidier der de finnes, slik at konsekvensene for miljøet avdekkes, og samtidig fullt ut ta hensyn til utviklingslandenes særlige behov og situasjon og begrense eventuelle negative konsekvenser for deres utvikling mest mulig og på en måte som beskytter de fattige og de berørte lokalsamfunnene',
    desc13: 'Mengden klimagasser fortsetter å øke og klimaendringene skjer raskere enn antatt. Effektene av klimaendringene er synlige over hele verden. Den globale gjennomsnittstemperaturen har steget omtrent 1 °C siden den før-industriell tid, i tillegg fortsetter havnivået å stige. De fattigste rammes hardest. Land har levert nasjonale planer for reduksjon, men de er ikke omfattende nok.',
    13: 'Stoppe klimaendringene',
    target13_1: 'Styrke evnen til å stå imot og tilpasse seg klimarelaterte farer og naturkatastrofer i alle land',
    target13_2: 'Innarbeide tiltak mot klimaendringer i politikk, strategier og planlegging på nasjonalt nivå',
    target13_3: 'Styrke enkeltpersoners og institusjoners evne til å motvirke, tilpasse seg og redusere konsekvensene av klimaendringer og deres evne til tidlig varsling, samt styrke kunnskapen og bevisstgjøringen om dette',
    target13_a: 'Gjennomføre forpliktelsene de utviklede landene som er part i FNs rammekonvensjon om klimaendringer, har påtatt seg, for å  nå;  målet om i fellesskap å skaffe 100 milliarder dollar årlig innen 2020 fra alle kilder for å dekke utviklingslandenes behov for å innføre hensiktsmessige klimatiltak og gjennomføre dem på en åpen måte, og fullt ut operasjonalisere Det grønne klimafondet ved at fondet snarest mulig tilføres kapital',
    target13_b: 'Fremme mekanismer for å styrke evnen til effektiv klimarelatert planlegging og forvaltning i de minst utviklede landene og små  utviklingsøystater, blant annet med vekt på kvinner, ungdom og lokale og marginaliserte samfunn',
    desc14: 'Livet på jorden er avhengig av havet. Temperaturen, kjemien, strømningene og livet i havet er det som driver de globale systemene som gjør det mulig for menneskene å leve på jorda. Over halvpartene av oksygenet vi puster inn kommer fra havet. Til tross for viktigheten av havet fortsetter menneskene på jorden å ødelegge det, som medfører at det ikke lenger kan beskytte jorden som det skal.',
    14: 'Livet i havet',
    target14_1: 'Innen 2025 forhindre og i betydelig grad redusere alle former for havforurensning, særlig fra landbasert virksomhet, inkludert marin forsøpling og utslipp av næringssalter',
    target14_2: 'Innen 2020 forvalte og beskytte økosystemene i havet og langs kysten på en bærekraftig måte for å unngå betydelig skadevirkninger, blant annet ved å styrke økosystemenes motstandsevne og ved å iverksette tiltak for å gjenoppbygge dem, slik at havene kan bli sunne og produktive',
    target14_3: 'Begrense mest mulig og sørge for håndtering av konsekvensene av havforsuring, blant annet gjennom styrket vitenskapelig samarbeid på alle nivåer',
    target14_4: 'Innen 2020 innføre effektive tiltak for å regulere uttaket av fiskebestandene, få slutt på overfiske og ulovlig, urapportert og uregulert fiske og ødeleggende fiskemetoder, og iverksette vitenskapelig baserte forvaltningsplaner for å gjenoppbygge fiskebestandene på kortest mulig tid, i det minste til de nivåene som kan gi høyest mulig bærekraftig avkastning ut fra bestandenes biologiske særtrekk',
    target14_5: 'Innen 2020 bevare minst 10 prosent av kyst- og havområdene, i samsvar med nasjonal rett og folkeretten og på grunnlag av den beste vitenskapelige kunnskapen som er tilgjengelig',
    target14_6: 'Innen 2020 forby visse former for fiskerisubsidier som bidrar til overkapasitet og overfiske, avskaffe subsidier som bidrar til ulovlig, urapportert og uregulert fiske, og dessuten unngå å innføre nye tilsvarende subsidier, samtidig som man erkjenner at en hensiktsmessig og effektiv særskilt og differensiert behandling av utviklingslandene og de minst utviklede landene bør være en integrert del av Verdens handelsorganisasjons forhandlinger om fiskerisubsidier(*)(*) Samtidig som det tas hensyn til de pågående forhandlingene i Verdens handelsorganisasjon, Doha-runden og erklæringen fra ministermøtet i Hongkong',
    target14_7: 'Innen 2030 sikre at de økonomiske fordelene ved bærekraftig bruk av havets ressurser, blant annet gjennom bærekraftig forvaltning av fiskeri, akvakultur og turistnæring, i større grad kommer små utviklingsøystater og de minst utviklede landene til gode',
    target14_a: 'Styrke vitenskapelig kunnskap, bygge opp forskningskapasitet og overføre marin teknologi og samtidig ta hensyn til kriterier og retningslinjer fra Den mellomstatlige oseanografiske kommisjon for overføring av marin teknologi med sikte på å bedre tilstanden i havet og øke det marine artsmangfoldets bidrag til utviklingen i utviklingslandene, særlig i små utviklingsøystater og de minst utviklede landene',
    target14_b: 'Gi fiskere som driver småskala fiske, tilgang til marine ressurser og markeder',
    target14_c: 'Styrke bevaring og bærekraftig bruk av havene og de marine ressursene ved å implementere folkeretten slik den er reflektert i FNs havrettskonvensjon, som utgjør rettsgrunnlaget for bevaring og bærekraftig bruk av havene og de marine ressursene, slik det framgår av punkt 158 i FN-rapporten «The Future We Want»',
    desc15: 'Mennesker fortsetter med å ødelegge helsen til jordas økosystem på land, som hele jordkloden er avhengig av. Skogen dekker 30 prosent av jordas overflate, og gir mat og ly til over 80 prosent av alle dyr.',
    15: 'Livet på land',
    target15_1: 'Innen 2020 bevare og gjenopprette bærekraftig bruk av ferskvannsbaserte økosystemer og tjenester som benytter seg av disse økosystemene, på land og i innlandsområder, særlig skoger, våtmarker, fjell og tørre områder, i samsvar med forpliktelser i internasjonale avtaler',
    target15_2: 'Innen 2020 fremme innføringen av en bærekraftig forvaltning av all slags skog, stanse avskoging, gjenopprette forringede skoger, og i betydelig grad øke gjenreising og nyplanting av skog på globalt nivå',
    target15_3: 'Innen 2030 bekjempe ørkenspredning, restaurere forringet land og matjord, inkludert landområder som er rammet av ørkenspredning, tørke og flom, og arbeide for en verden uten landforringelse',
    target15_4: 'Innen 2030 bevare økosystemer i fjellområder, inkludert det biologiske mangfoldet der, slik at de skal bli bedre i stand til å bidra til en bærekraftig utvikling',
    target15_5: 'Iverksette umiddelbare og omfattende tiltak for å redusere ødeleggelsen av habitater, stanse tap av biologisk mangfold og innen 2020 verne truede arter og forhindre at de dør ut',
    target15_6: 'Fremme en rettferdig og likeverdig deling av godene knyttet til bruk av genressurser, og fremme formålstjenlig tilgang til slike ressurser i  tråd med internasjonal enighet',
    target15_7: 'Iverksette umiddelbare tiltak for å stanse krypskyting og ulovlig handel med vernede plante- og dyrearter, og håndtere både tilbuds- og etterspørselssiden ved handelen med ulovlige produkter fra viltlevende dyr',
    target15_8: 'Innen 2020 innføre tiltak for å unngå innføring og spredning av fremmede arter for å redusere fremmede arters påvirkning på land- og vannbaserte økosystemer i betydelig grad, og dessuten kontrollere eller utrydde prioriterte fremmede arter',
    target15_9: 'Innen 2020 integrere verdien av økosystemer og biologisk mangfold i nasjonale og lokale planleggingsprosesser, i strategier for fattigdomsbekjempelse og i regnskap',
    target15_a: 'Mobilisere en betydelig økning i finansielle ressurser fra alle kilder for å bevare og utnytte biologisk mangfold og økosystemer på en bærekraftig måte',
    target15_b: 'Mobilisere betydelige ressurser fra alle kilder og på alle nivåer for å finansiere en bærekraftig skogforvaltning, og sørge for virkemidler som er egnet til å fremme slik forvaltning i utviklingslandene, blant annet virkemidler for bevaring og nyplanting av skog',
    target15_c: 'Øke den globale støtten til tiltak for å bekjempe krypskyting og ulovlig handel med vernede arter, blant annet ved å styrke lokalsamfunnenes evne til å benytte de muligheter som finnes for å opprettholde et bærekraftig livsgrunnlag',
    desc16: 'Å sikre internasjonal fred og sikkerhet har alltid vært FNs hovedoppgave. Derfor er mål 16 viet til å skape fredelige og inkluderende samfunn. Fred er en forutsetning for å skape bærekraftig utvikling. Dessverre har utviklingen innenfor dette bærekraftsmålet ikke gått i riktig retning. 82 millioner av mennesker levde i 2020 som flyktninger, det er et antall som er det høyeste FN noen gang har registrert.',
    16: 'Fred, rettferdighet og velfungerende institusjoner',
    target16_1: 'Betydelig redusere alle former for vold og dødelighet knyttet til vold i hele verden',
    target16_2: 'Stanse overgrep, utnytting, menneskehandel og alle former for vold og tortur mot barn',
    target16_3: 'Fremme rettsstaten nasjonalt og internasjonalt, og sikre likhet for loven, rettsikkerhet og rettsvern for alle',
    target16_4: 'Innen 2030 oppnå en betydelig reduksjon av ulovlige finans- og våpenstrømmer, gjøre det enklere å spore opp og returnere stjålne eiendeler og bekjempe alle former for organisert kriminalitet',
    target16_5: 'Betydelig redusere korrupsjon og bestikkelser i alle former',
    target16_6: 'Utvikle effektive, ansvarlige og åpne institusjoner på alle nivåer',
    target16_7: 'Sikre lydhøre, inkluderende, deltakelsesbaserte og representative beslutningsprosesser på alle nivåer',
    target16_8: 'Utvide og styrke utviklingslandenes deltakelse i institusjoner for global styring',
    target16_9: 'Innen 2030 sikre juridisk identitet for alle, blant annet gjennom fødselsregistrering',
    target16_10: 'Sikre allmenn tilgang til informasjon og beskytte grunnleggende friheter, i samsvar med nasjonal lovgivning og internasjonale avtaler',
    target16_a: 'Styrke relevante nasjonale institusjoner, blant annet gjennom internasjonalt samarbeid, med sikte på å bygge kapasitet på alle nivåer, særlig i utviklingsland, for å forebygge vold og bekjempe terrorisme og kriminalitet',
    target16_b: 'Fremme og håndheve ikke-diskriminerende lover og politikk for bærekraftig utvikling',
    desc17: 'For å lykkes med bærekraftsmålene trengs det nye og sterke partnerskap. Myndigheter, næringslivet og sivilsamfunnet må samarbeide for å oppnå bærekraftig utvikling. Bærekraftsmålene skal fungere som en felles, global retning og prioritert innsats de neste 15 årene. Erfaring fra Tusenårsmålene viser at denne typen målrettet innsats virker.',
    17: 'Samarbeid for å nå målene',
    target17_1: 'Styrke og mobilisere nasjonale ressurser, blant annet gjennom internasjonal støtte til utviklingsland, med sikte på å bedre landenes evne til å kreve inn skatter og andre avgifter',
    target17_2: 'Påse at de utviklede landene fullt ut gjennomfører sine offisielle bistandsforpliktelser (ODA) overfor utviklingslandene, blant annet forpliktelsen som mange av dem har påtatt seg til å gi 0,7 prosent av ODA/BNI i bistand til utviklingsland og 0,15-0,20 prosent av ODA/BNI til de minst utviklede landene; ODA-ytere oppfordres til å vurdere å gi minst 0,20 prosent av ODA/BNI i bistand til de minst utviklede landene',
    target17_3: 'Mobilisere ytterligere finansielle ressurser til utviklingslandene fra flere kilder',
    target17_4: 'Bistå utviklingslandene med å oppnå langsiktige og bærekraftige gjeldsvilkår gjennom en samordnet politikk for å fremme gjeldsfinansiering, gjeldslette eller omstrukturering av gjeld, og behandle de fattigste og mest gjeldstyngede landenes utenlandsgjeld på en måte som reduserer gjeldsrelatert nød',
    target17_5: 'Vedta og gjennomføre investeringsfremmende ordninger for de minst utviklede landene',
    target17_6: 'Bedre tilgangen til og styrke nord-sør-samarbeidet, sør-sør-samarbeidet og det triangulære samarbeidet regionalt og internasjonalt om vitenskap, teknologi og innovasjon, og forbedre kunnskapsdelingen på gjensidig avtalte vilkår, blant annet gjennom å samordne eksisterende ordninger bedre, særlig på FN-nivå, og gjennom en global mekanisme for tilgjengeliggjøring av teknologi', 
    target17_7: 'Fremme utvikling, overføring, spredning og formidling av miljøvennlig teknologi til utviklingsland på fordelaktige vilkår, blant annet på ikke-markedsmessige vilkår eller på vilkår som på andre måter er gunstigere enn det andre land får, etter gjensidige avtaler',
    target17_8: 'Igangsette teknologibanken og ordningen for kapasitetsbygging innenfor vitenskap, teknologi og innovasjon for de minst utviklede landene innen 2017,  og  øke bruken av muliggjørende teknologi, særlig informasjons- og kommunikasjonsteknologi',
    target17_9: 'Øke den internasjonale støtten til å gjennomføre en effektiv og målrettet kapasitetsbygging i utviklingsland og  dermed støtte nasjonale planer for gjennomføring av alle bærekraftsmålene, blant annet gjennom nord-sør-samarbeid, sør-sør-samarbeid og trepartssamarbeid',
    target17_10: 'Fremme et allment, regelbasert, åpent, ikke-diskriminerende og likeverdig multilateralt handelssystem underlagt Verdens handelsorganisasjon, blant annet ved å sluttføre forhandlingene under organisasjonens Doha-runde',
    target17_11: 'Øke utviklingslandenes eksport betydelig, særlig med sikte på å doble de minst utviklede landenes andel av verdens eksport innen 2020',
    target17_12: 'Innen gitte tidsrammer gi alle de minst utviklede landene varig avgiftsfri og kvotefri markedsadgang, i samsvar med beslutninger i Verdens handelsorganisasjon, blant annet ved å sikre at preferanseopprinnelsesregler for importvarer fra de minst utviklede landene er klare og enkle, slik at de bidrar til å lette markedsadgangen',
    target17_13: 'Styrke stabiliteten i verdens makroøkonomi, blant annet gjennom politisk samordning og samstemthet',
    target17_14: 'Oppnå en mer samstemt og helhetlig politikk for bærekraftig utvikling',
    target17_15: 'Respektere hvert lands politiske handlingsrom og lederskap med hensyn til å etablere og gjennomføre egen politikk for fattigdomsbekjempelse og bærekraftig utvikling',
    target17_16: 'Styrke det globale partnerskapet for bærekraftig utvikling og understøtte det med partnerskap mellom flere interessenter som kan mobilisere og dele kunnskap, ekspertise, teknologi og finansielle ressurser, for å bidra til at alle land, særlig utviklingslandene, oppnår bærekraftsmålene',
    target17_17: 'Stimulere til og fremme velfungerende partnerskap i det offentlige, mellom det offentlige og det private og i det sivile samfunn som bygger på partnerskapenes erfaringer og ressursstrategier',
    target17_18: 'Innen 2020 øke støtten til kapasitetsbygging i utviklingsland, også i de minst utviklede landene og små utviklingsøystater, for i betydelig grad å bedre tilgangen til pålitelige og aktuelle data av høy kvalitet fordelt etter inntekt, kjønn, alder, rase, etnisitet, migrasjonsstatus, funksjonsevne, geografisk plassering og andre nasjonalt relevante kjennetegn',
    target17_19: 'Innen 2030 bygge videre på eksisterende initativer for å utvikle målemetoder for bærekraftig utvikling som supplerer bruttonasjonalprodukt, og støtte kapasitetsbygging på statistikkområdet i utviklingsland',
    // Temporary:
    // Development areas:
    Arbeid_sysselsettning:'Arbeid og sysselsetting',
    Bebyggelse:'Bebyggelse',
    Digitalisering1:'Digitalisering',
    Energi:'Energi',
    Helse_sosial_og_velferd:'Helse, sosial og velferd',
    Kultur:'Kultur',
    Natur_og_miljø:'Natur og miljø',
    Næring:'Næring',
    Oppvekst_og_utdanning:'Oppvekst og utdanning',
    Styring_og_demokrati:'Styring og demokrati',
    Transport:'Transport',
    Trygghet_og_beredskap:'Trygghet og beredskap',
    Vann_og_søppel:'Vann og søppel',
    Økonomisk:'Økonomisk',
    // TBL:
    Miljø:'Miljø',
    Sosialt:'Sosialt',
    Økonomi:'Økonomi',
    // Perspectives in Trdheim
    Arealer_og_ressursforvaltning:'Arealer og ressursforvaltning',
    Det_grønne_skiftet:'Det grønne skiftet',
    Digitalisering2:'Digitalisering',
    Forbruk:'Forbruk',
    Grønn_mobilitet:'Grønn mobilitet',
    Indentitet_og_kultur:'Identitet og kultur',
    Inkluderende_samfunn:'Inkluderende samfunn',
    Lokaldemokratiet: 'Lokaldemokratiet',
    Nærmiljø_og_stedsutvikling:'Nærmiljø og stedsutvikling',
    Oppvekst_og_læring:'Oppvekst og læring',
    P1:'P1',
    Samarbeid_og_verdiskapning:'Samarbeid og verdiskapning',
    Samskapt_velferd:'Samskapt velferd',
    Økonomi1:'Økonomi',
    // Icons:
    icon_1:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/2/0/7/1/831702-60-nor-NO/M%C3%A5l%201%20RGB.png',
    icon_2:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/9/1/7/1/831719-77-nor-NO/m%C3%A5l%202-%20bokm%C3%A5l.png',
    icon_3:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/6/3/7/1/831736-44-nor-NO/M%C3%A5l%203%20RGB@4x.png',
    icon_4:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/3/5/7/1/831753-34-nor-NO/M%C3%A5l%204%20RGB.png',
    icon_5:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/0/7/7/1/831770-32-nor-NO/M%C3%A5l%205%20RGB.png',
    icon_6:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/7/8/7/1/831787-30-nor-NO/M%C3%A5l%206%20RGB.png',
    icon_7:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/4/0/8/1/831804-32-nor-NO/M%C3%A5l%207%20RGB@4x.png',
    icon_8:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/1/2/8/1/831821-23-nor-NO/M%C3%A5l%208%20RGB.png',
    icon_9:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/8/3/8/1/831838-32-nor-NO/M%C3%A5l%209%20RGB@4x.png',
    icon_10:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/5/5/8/1/831855-30-nor-NO/M%C3%A5l%2010%20RGB.png',
    icon_11:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/2/7/8/1/831872-28-nor-NO/M%C3%A5l%2011%20RGB@4x.png',
    icon_12:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/9/8/8/1/831889-22-nor-NO/M%C3%A5l%2012%20RGB.png',
    icon_13:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/6/0/9/1/831906-31-nor-NO/Alle%20ikoner%20RGB_Norsk_V04_Side_18.png',
    icon_14:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/3/2/9/1/831923-30-nor-NO/Alle%20ikoner%20RGB_Nynorsk_V04_Side_19.png',
    icon_15:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/0/4/9/1/831940-22-nor-NO/Alle%20ikoner%20RGB_Nynorsk_V04_Side_20.png',
    icon_16:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/7/5/9/1/831957-27-nor-NO/M%C3%A5l%2016%20RGB@2x.png',
    icon_17:'https://www.fn.no/var/globalis/storage/images/_aliases/medium/4/7/9/1/831974-29-nor-NO/M%C3%A5l%2017%20RGB.png',

};