export default {
    bg: 'bułgarski',
    hr: 'chorwacki',
    cs: 'czeski', 
    da: 'duński', 
    nl: 'niderlandzki',
    en: 'angielski',
    et: 'estoński',
    fi: 'fiński',
    fr: 'francuski',
    de: 'niemiecki', 
    el: 'grecki',
    hu: 'węgierski',
    ga: 'irlandzki', 
    it: 'włoski',
    lv: 'łotewski',
    lt: 'litewski',
    mt: 'maltański',
    no: 'norweski',
    pl: 'polski',
    pt: 'portugalski',
    ro:'rumuński',
    sk: 'słowacki',
    sl: 'słoweński',
    es: 'hiszpański',
    sv: 'szwedzki',
};