export default {
    bg: 'búlgaro',
    hr: 'croata',
    cs: 'checo', 
    da: 'dinamarquês', 
    nl: 'neerlandês',
    en: 'inglês',
    et: 'estónio',
    fi: 'finlandês',
    fr: 'francês',
    de: 'alemão', 
    el: 'grego',
    hu: 'húngaro',
    ga: 'irlandês', 
    it: 'italiano',
    lv: 'letão',
    lt: 'lituano',
    mt: 'maltês',
    no: 'norueguês',
    pl: 'polaco',
    pt: 'português',
    ro:'romeno',
    sk: 'eslovaco',
    sl: 'esloveno',
    es: 'espanhol',
    sv: 'sueco',
};