export default {
    bg: 'bulgară',
    hr: 'croată',
    cs: 'cehă', 
    da: 'daneză', 
    nl: 'neerlandeză',
    en: 'engleză',
    et: 'estonă',
    fi: 'finlandeză',
    fr: 'franceză',
    de: 'germană', 
    el: 'greacă',
    hu: 'maghiară',
    ga: 'irlandeză', 
    it: 'italiană',
    lv: 'letonă',
    lt: 'lituaniană',
    mt: 'malteză',
    no: 'norvegiană',
    pl: 'polonă',
    pt: 'portugheză',
    ro:'română',
    sk: 'slovacă',
    sl: 'slovenă',
    es: 'spaniolă',
    sv: 'suedeză'
}