export default {
    bg: 'bulharčina',
    hr: 'chorvátčina',
    cs: 'čeština', 
    da: 'dánčina', 
    nl: 'holandčina',
    en: 'angličtina',
    et: 'estónčina',
    fi: 'fínčina',
    fr: 'francúzština',
    de: 'nemčina', 
    el: 'gréčtina',
    hu: 'maďarčina',
    ga: 'írčina', 
    it: 'taliančina',
    lv: 'lotyština',
    lt: 'litovčina',
    mt: 'maltčina',
    no: 'nórčina',
    pl: 'poľština',
    pt: 'portugalčina',
    ro:'rumunčina',
    sk: 'slovenčina',
    sl: 'slovinčina',
    es: 'španielčina',
    sv: 'švédčina'
}