export default {
    bg: 'bulgariska',
    hr: 'kroatiska',
    cs: 'tjeckiska', 
    da: 'danska', 
    nl: 'nederländska',
    en: 'engelska',
    et: 'estniska',
    fi: 'finska',
    fr: 'franska',
    de: 'tyska', 
    el: 'grekiska',
    hu: 'ungerska',
    ga: 'iriska', 
    it: 'italienska',
    lv: 'lettiska',
    lt: 'litauiska',
    mt: 'maltesiska',
    no: 'norska',
    pl: 'polska',
    pt: 'portugisiska',
    ro:'rumänska',
    sk: 'slovakiska',
    sl: 'slovenska',
    es: 'spanska',
    sv: 'svenska',
};