export default {
    bg: 'bolgarščina',
    hr: 'hrvaščina',
    cs: 'češčina', 
    da: 'danščina', 
    nl: 'nizozemščina',
    en: 'angleščina',
    et: 'estonščina',
    fi: 'finščina',
    fr: 'francoščina',
    de: 'nemščina', 
    el: 'grščina',
    hu: 'madžarščina',
    ga: 'irščina', 
    it: 'italijanščina',
    lv: 'latvijščina',
    lt: 'litovščina',
    mt: 'malteščina',
    no: 'norveščina',
    pl: 'poljščina',
    pt: 'portugalščina',
    ro:'romunščina',
    sk: 'slovaščina',
    sl: 'slovenščina',
    es: 'španščina',
    sv: 'švedščina'
}